### ISSUE TITLE
Not taking sourcesContent entry into account when uploaded.

### ISSUE THREAD

**Issue by codebymikey** [bugsnag/bugsnag-react-native#100]
It doesn't seem to be taking the `sourcesContent` entry in the sourcemap into account.

The [sources](https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#uploading-source-maps-to-bugsnag) documentation says otherwise.

**Comment by kattrali** [comment]
Thanks for the report, @codebymikey. Can you send a note via support@bugsnag.com with a link to an example error which isn't working correctly? Then we can take a look at your source maps to determine what is going on.
