### ISSUE TITLE
modify report on beforeSendCallbacks

### ISSUE THREAD

**Issue by stereodenis** [bugsnag/bugsnag-react-native#103]
is it possible to modify report on beforeSendCallbacks?

```
const configuration = new Configuration()
configuration.apiKey = 'someToken'
configuration.releaseStage = Config.mode
configuration.beforeSendCallbacks.push((report) => {
  report.metadata = {
    store: Store,
  }
  return report
})

const bugsnag = new Client(configuration)
```

**Comment by kattrali** [comment]
Yes. There is an example documented [here](https://docs.bugsnag.com/platforms/react-native/customizing-error-reports/#adding-custom-diagnostics) in the "Adding custom diagnostics" section.

**Comment by yaronlevi** [comment]
Is this the right way of attaching metadata?
The Configuration dose not have the registerBeforeSendCallback property in in.
Only the beforeSendCallbacks property.
