### ISSUE TITLE
ESLint no-param-reassign

### ISSUE THREAD

**Issue by stereodenis** [bugsnag/bugsnag-react-native#105]
![busfor-app - webstorm 2017 2 eap 2017-06-08 00-02-20](https://user-images.githubusercontent.com/1406461/26901326-19447164-4bde-11e7-95a3-20c19fd5045e.png)

**Comment by kattrali** [comment]
Thanks for the report, @stereodenis. I'm not sure what would need to be remedied here, assignment to the function parameter properties is part of the design. Maybe the `no-param-reassign` rule can be tweaked in your `.eslintrc`?
