### ISSUE TITLE
Not dispatching errors to previous globalHandler

### ISSUE THREAD

**Issue by demianscv** [bugsnag/bugsnag-react-native#106]
It seems that the ErrorUtils.getGlobalHandler is not handled properly. I have set this configuration:
```
configuration.beforeSendCallbacks.push((report) => !__DEV__)
```

which seems to work properly on the bugsnag site, but when I am in dev bugsnag seems to not continue executing the previous handler, and thus the regular react native error doesn't appear (and leaves the app in a inconsistent state).
Digging a bit into bugsnag library, it seems that if for some reason it doesn't need to notify to bugsnag, it just returns the `notify` function and doesn't call the `previousHandler` / `postSendCallback`.

Does that makes sense or is it missing the previous global handler by design?
Thanks!

**Comment by kattrali** [comment]
This was definitely an oversight. Due to be released in 2.2.6.
