### ISSUE TITLE
Change import "RCTBridgeModule.h" to <React/RCTBridgeModule.h>

### ISSUE THREAD

**Issue by leandro-a-silva** [bugsnag/bugsnag-react-native#111]
This change has been necessary for me. Happens to something else?

**Comment by kattrali** [comment]
Thanks for the report, @leandro-a-silva. What version of react native are you using, and how did you install the library?

**Comment by tysoncadenhead** [comment]
I had the same issue using:
- React Native 0.44.0
- React 16.0.0-alpha.6
- bugsnag-react-native 1.3.0

Changing the import fixed the issue for me as well.

**Comment by kattrali** [comment]
@tysoncadenhead `bugsnag-react-native@1` supports React Native v0.39 and below. Use `bugsnag-react-native@2` for newer versions (though we may have a new major version for RN v0.46, pending https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8). There was a breaking change in React Native v0.40 which required all modules to make a breaking change. This was resolved in https://github.com/bugsnag/bugsnag-react-native/pull/60/commits/f0e2dd86af82ce450b16700ce4afc1f377eefbaf
