### ISSUE TITLE
Secure authentication with bugsnag-sourcemaps

### ISSUE THREAD

**Issue by bencollab** [bugsnag/bugsnag-react-native#112]
It's my understanding that anything distributed as part of my app's binary cannot be considered "secret". This includes values (such as API keys) stored in an iOS app's Info.plist file.

As such, the Bugsnag project API Key is, for all intents and purposes, a public token. This is fine in the context of reporting bugs from my app since a malicious actor would only be able to use that API Key to submit data to the server (rather than retrieve data).

However, it looks like the `bugsnag-sourcemaps` tool currently uses that same (public) API Key for authentication, meaning that anyone who has access to my app binary (the public) can presumably upload (and overwrite) sourcemaps to the Bugsnag servers for my app. While this may not represent  any (direct) potential for unauthorized disclosure of private information, it *does* present the possibility for sourcemaps/stacktraces to be manipulated by malicious parties as part of a more elaborate attack.

Would it be possible for future versions of `bugsnag-sourcemaps` to employ the same API authentication mechanism used by the Data access API?

**Comment by kattrali** [comment]
Thank you for the detailed report and the suggestion, @bencollab. Its certainly possible that there may be other supported means of authentication in the future, and I'll raise it with the product team. However, similar to how a malicious actor could send error reports using the API key but never know if it had any effect, the same is true for uploading source maps. Would the ability to delete uploaded source maps be a good workaround in the meantime?

**Comment by bencollab** [comment]
Thanks for looking into it. The ability to delete source maps would be a nice addition, but it wouldn't really do anything to resolve the core issue.

I do agree that the potential for harm in this case is (as far as I can tell) relatively minimal, so probably not a super high priority. The main concern for me is just the idea that someone *could* be messing with my sourcemaps. To fully resolve the issue, I believe it would require not only added support for different authentication methods in the client, but also the ability to enforce *only* a certain kind of authentication at the account level.
