### ISSUE TITLE
Source maps not working in development environment

### ISSUE THREAD

**Issue by jinxac** [bugsnag/bugsnag-react-native#113]
I tried the steps in [documentation](https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#uploading-source-maps)  of source maps multiple times and I am pretty sure I covered it all. 

Following are the steps I tried:-

1. Creating source map in debug mode 
`
 react-native bundle   --platform ios   --dev true   --entry-file index.ios.js   --bundle-output ios/main.jsbundle.js --sourcemap-output ios/main.jsbundle.map.js
`

2. Uploading the source map to bugsnag:-

`
bugsnag-sourcemaps upload  --api-key <api-key>   --source-map ios/main.jsbundle.map.js   --strip-project-root   --minified-file ios/main.jsbundle.js --app-version 1.1.3 --overwrite --upload-sources --minified-url http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false
`

P.S: Under Sourcemaps I can see the Source URL as `http://localhost:8081/index.ios.bundle?platform=ios` instead of `http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false`.

3.  App version matches in bug and source map(1.1.3)
![screen shot 2017-06-30 at 2 56 38 pm](https://user-images.githubusercontent.com/15068096/27729692-5b7f8a6e-5da4-11e7-87c1-7c325e6272ca.png) but still I see source maps not getting reflected at all

![screen shot 2017-06-30 at 2 56 04 pm](https://user-images.githubusercontent.com/15068096/27729665-48a4f190-5da4-11e7-9a37-f701cd629ea1.png)

I tried going through FAQs [https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#why-isn-39-t-the-uploaded-source-map-getting-applied-to-my-error](url) and see that all my conditions are satisfied. 

Am i missing something  here or is this suppose to be an issue?

P.S: This is working fine in **production** environment. I get a proper backtrack. I am sure whats going wrong in the development environment :(

**Comment by kattrali** [comment]
@jinxac Thanks for the report. Based on the screenshot, it looks like your minified URL should be `http://192.168.1.39:8081/index.ios.bundle`, which should resolve the source mapping issue. Which version of react native are you running?

**Comment by jinxac** [comment]
Hi @kattrali i tried this but is not working with that too.. version of react native is 0.40

**Comment by kattrali** [comment]
@jinxac Ah, thanks for the update. I see another issue. Are you running through a chrome debugger? Using the external debugger changes the stacktrace format to use Chrome's instead of the native one. Does it work without the debugger attached?

**Comment by jinxac** [comment]
sure @kattrali  let me try it once

**Comment by kattrali** [comment]
Feel free to reopen if this issue is still a problem

**Comment by javiercr** [comment]
I ran into the same problem, maybe the docs should mention that sourcemaps won't work if Remote debugging is enabled :)
