### ISSUE TITLE
How to disable BugSnag for ReactNative App Debug Builds

### ISSUE THREAD

**Issue by maheswaranapk** [bugsnag/bugsnag-react-native#114]
We had integrated BugSnag SDK to out React Native Application and it works fine.

How to disable BugSnag only for Debug Build for React Native Android and iOS Application ?

Version : "bugsnag-react-native": "^2.2.3",

**Comment by kattrali** [comment]
Thanks for the report, @maheswaranapk. You can use the [`notifyReleaseStages` configuration option](https://docs.bugsnag.com/platforms/react-native/configuration-options/#notifyreleasestages) to enable or disable reports during development (or other phases of the release cycle.

Your initialization code would then look something like this:

```js
import { Client, Configuration } from "bugsnag-react-native";

const configuration = new Configuration();
configuration.notifyReleaseStages = ['production'];
// ... other options
const bugsnag = new Client(configuration);
```
