### ISSUE TITLE
RCTFatalExceptions are reported when using CodePush

### ISSUE THREAD

**Issue by kattrali** [bugsnag/bugsnag-react-native#115]
From @andriantosg (split from #35):

Hi, does anyone know why I still got `RCTFatalException: Unhandled JS Exception:` while using CodePush? I've tried using `*main.jsbundle` on minified-url but unfortunately It didn't work. Am I missing something?

**Comment by kattrali** [comment]
@andriantosg Which versions of React Native, bugsnag-react-native, and Code Push are you using?

**Comment by andriantosg** [comment]
Hi @kattrali, I'm sorry forgot to update here. I've found the solution for this problem. It seems I failed  to set `codeBundleId` in my RN code so It couldn't mapping to uploaded sourcemaps, but now It works well. 

But I got another question now. Before I do any codepush, Bugsnag can visualize me exactly where is error code with file names and line of code. But after I do codepush, Bugsnag only show me file names and line of code. It doesn't visualize where exactly the error code is. Is this expected?

I'm using RN 0.44.0, latest bugsnag and code push version.

**Comment by kattrali** [comment]
Thanks for the update. My guess is that the source file contents are not being uploaded. There's more explanation and a possible fix [in the troubleshooting FAQ](https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#why-can-39-t-i-see-the-code-context-for-my-mapped-javascript-error)

**Comment by andriantosg** [comment]
Thanks for the information. It suggest me to use the `--upload-sources` flag in `bugsnag-sourcemaps` to upload all files referenced by the source map. But I've used it and code context still didn't appear. Is there any workaround?

And how do I ensure that the `sourcesContent` field in the source map file is populated correctly?

FYI, I used this CLI command to upload my codepush bundle.
```
bugsnag-sourcemaps upload \
  --api-key [API_KEY] \
  --code-bundle-id [BUNDLE_ID] \
  --minified-url main.jsbundle \
  --source-map ios/build/main.jsbundle.map \
  --minified-file ios/build/main.jsbundle \
  --upload-sources \
  --add-wildcard-prefix \
  --overwrite
```

**Comment by kattrali** [comment]
The command looks correct to me. 🤔 I'll be able to take a look at what's happening on our end on Monday. I'm working on some improvements to the documentation as well to make this process clearer.

**Comment by andriantosg** [comment]
That's great. I'm waiting for your updates. Thank you.

**Comment by andriantosg** [comment]
Hi @kattrali, is there any updates?

**Comment by kattrali** [comment]
It looks like this happens if the [JavaScript portion of configuration](https://docs.bugsnag.com/platforms/react-native/#javascript-configuration) is not completed. Each platform requires the native portion of configuration as well as the JS section. I'm restructuring the docs a bit to better explain how this happens.

**Comment by kattrali** [comment]
Fixed by updating the [integration guide](https://docs.bugsnag.com/platforms/react-native/#basic-configuration) to indicate that JS + native config is required for each platform
