### ISSUE TITLE
source map not working

### ISSUE THREAD

**Issue by alexeyMohnatkin** [bugsnag/bugsnag-react-native#117]
I uploaded source map, but it's not applying to my errors. I checked twice all possible mistakes described here: https://docs.bugsnag.com/api/js-source-map-upload/#why-can-39-t-i-see-the-code-context-for-my-mapped-javascript-error

react-native bundle \
  --dev false \
  --platform android \
  --entry-file index.android.js \
  --bundle-output ./build/main.jsbundle \
  --sourcemap-output ./build/main.jsbundle.map

curl https://upload.bugsnag.com/ \
   -F apiKey=<apiKey> \
   -F appVersion=1.4.0 \
   -F minifiedUrl=index.android.jsbundle \
   -F sourceMap=@<absolutePathToFolder>/main.jsbundle.map \
   -F minifiedFile=@<absolutePathToFolder>/main.jsbundle \
   -F overwrite=true

After upload I see 'Ok' in response from bugsnag.

**Comment by jmshal** [comment]
Here's a few other common & simple things just to check too.

- Are you providing the Bugsnag notifier with your app version, and if so, does it match the one you're providing through curl?
- Uploading sourcemaps doesn't backfill errors already sent to Bugsnag, only new errors.
- Have you tried using the `bugsnag-sourcemaps` cli [(more info)](https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#uploading-source-maps-to-bugsnag), and making use of the `--add-wildcard-prefix` flag, to upload your sourcemaps?

Also, if you are able to - it may help to provide a screenshot of what you're seeing when viewing an error in Bugsnag, specifically the stacktrace view.

**Comment by alexeyMohnatkin** [comment]
> Uploading sourcemaps doesn't backfill errors already sent to Bugsnag, only new errors.
Yes, it was old error, sorry

**Comment by jmshal** [comment]
Just to confirm, is this issue resolved, or are you still experiencing issues viewing source code from sourcemaps in Bugsnag?

**Comment by alexeyMohnatkin** [comment]
resolved, close it
