### ISSUE TITLE
Installation for 2.2.3

### ISSUE THREAD

**Issue by dharik** [bugsnag/bugsnag-react-native#118]
Current docs say that we need to edit

For android: 
* AndroidManifest.xml
* MainActivity.java

For ios:
* Info.plist
* AppDelegate

The example, however, only modifies MainAppliation.java and then calls new Client('API_KEY').  What are the correct steps for a proper installation of 2.2.3?

**Comment by kattrali** [comment]
Thanks for the report, @dharik. The docs are correct, and the example app has not yet been updated for 2.2.3.
