### ISSUE TITLE
MainActivity.java template

### ISSUE THREAD

**Issue by dharik** [bugsnag/bugsnag-react-native#119]
Documentation shows that you need to edit MainActivity.java, but there is no onCreate() function in my MainActivity.java.

**Comment by kattrali** [comment]
No problem, @dharik. You can override and add the [`onCreate`](https://developer.android.com/reference/android/app/Activity.html?hl=ru#onCreate(android.os.Bundle)) method to your existing class:

```java
import com.bugsnag.BugsnagReactNative;
import android.os.Bundle;

public class MainActivity extends ReactActivity {
  // ...

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    BugsnagReactNative.start(this);
  }
}
```
