### ISSUE TITLE
2.3.0 Release

### ISSUE THREAD

**Issue by jpokrzyk** [bugsnag/bugsnag-react-native#125]
@kattrali  Sorry if this sounds like I'm impatient.... ;)

What's the release process to get this up on NPM? I'm more curious than anything. v2.3.0 looks good to me. 

It's not super urgent for us. Although it would be great if it gets up there in the next day or two. Thanks.

**Comment by kattrali** [comment]
lol no worries. I didn't notice that `npm publish` failed. cheers!
