### ISSUE TITLE
codeBundleId setting ignored

### ISSUE THREAD

**Issue by grigored** [bugsnag/bugsnag-react-native#127]
I'm using bugsnag with codepush.
Here's my code to upload source maps
```
bugsnag-sourcemaps upload \
    --api-key API_KEY \
    --code-bundle-id 1.0.0-b12 \
    --source-map codePushBuild/main.jsbundle.map \
    --minified-file codePushBuild/main.jsbundle \
    --minified-url main.jsbundle \
    --upload-sources \
    --add-wildcard-prefix
```
I'm pretty sure this is fine, as I can see on the bugsnag dashboard the `app version: -`  and `Code Bundle ID: 1.0.0-b12`. 

Here's my js code:
```
const config = new Configuration('API_KEY');
config.codeBundleId = '1.0.0-b12';
const bugsnag = new Client(config);
```
Whenever a crash happens, i can see in the App tab of the crash the app-version, but i don't see anything about the codeBundleId, and it also doesn't use the right sourcemaps. 

If I use appVersion instead of the codeBundleId, it works fine.

**Comment by kattrali** [comment]
This is resolved in bugsnag-react-native v2.3.1. Funnily enough, it was the combination of this issue, #128 and our conversation in #129 which led to the solution. Thanks again! 🎉
