### ISSUE TITLE
show more code in the exception report

### ISSUE THREAD

**Issue by grigored** [bugsnag/bugsnag-react-native#128]
With Sentry I see the line that caused the crash, 5 lines of code above and 5 lines below it. This way I can quickly understand what caused the crash.

With Bugsnag, all I have is the file name and line number, and i have to then git checkout to the right commit to see the code. I did upload sourcemaps, the files are indeed the ones i'm looking for. It's not a big deal, but this would be nice to have.

**Comment by kattrali** [comment]
It sounds like when the source maps are uploaded, the source files are not included. Are you following the guide in [Showing Full Stacktraces](https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/)? The `--upload-sources` option show allow release builds to include a code snippet in stack traces shown on the Bugsnag dashboard.

**Comment by kattrali** [comment]
Ah, saw in your other ticket that you're using CodePush. I'll verify that the sources upload is working correctly since what you're doing should be generating source code snippets.

**Comment by grigored** [comment]
Ok, thanks! Yes, I am using Codepush, and I followed that guide. Here's what codepush generates:
`assets, main.jsbundle, main.jsbundle.map, main.jsbundle.meta`. I used `--minified-file codePushBuildIOS/main.jsbundle `. Should i put a different file there?

**Comment by kattrali** [comment]
That sounds correct. Which version of `code-push-cli` are you using? I'll update my setup.

**Comment by grigored** [comment]
Thanks. I have `code-push-cli@2.0.2-beta`

**Comment by grigored** [comment]
any updates on this? Am i doing anything wrong, or the code snippets feature is not there yet?

**Comment by kattrali** [comment]
Working on testing this properly and setting something up to ensure its working in the future. There are quite a few different packages in the mix to ensure every configuration works. Also getting #127, #130, #131 queued up.

**Comment by grigored** [comment]
Ok, thanks 😃 . Looking fwd for your answer.

**Comment by kattrali** [comment]
This is fixed in `bugsnag-sourcemaps` v1.0.1

**Comment by grigored** [comment]
Great, thanks for the quick fix. How do I update `bugsnag-sourcemaps` ?

**Comment by jmshal** [comment]
Running `npm install bugsnag-sourcemaps@latest` either with `--save` or `--global` depending if you installed `bugsnag-sourcemaps` as a dependency in your project or globally, should do the trick 😃

**Comment by grigored** [comment]
Yes, I just figured out bugsnag-sourcemaps is the tool I use for uploading the sourcemaps 😜  I confirm it's working like a charm now!

**Comment by kattrali** [comment]
Awesome! Cheers 🎉
