### ISSUE TITLE
Coerce non-Errors thrown in JavaScript into Error objects

### ISSUE THREAD

**Issue by kattrali** [bugsnag/bugsnag-react-native#131]
Currently, when `throw` is used with an object which isn't an `Error`, a warning is issue from Bugsnag.js, indicating that the potential report is being discarded. We should keep the warning but attempt to coerce the object into a `RuntimeError`, where the message or perhaps custom metadata includes the thrown object. The stacktrace may not be particularly useful in this case, but we have something appended by the React Native global handler, which is something to investigate. The report `context` should include that the coercion into an error was done automatically by the Bugsnag library, to reduce confusion.

Further discussion in #129

**Comment by mifi** [comment]
I worked around this by creating a helper function that allows me to send almost anything into my error logger:

```js
export function logError(...args) {
  if (__DEV__) console.error(...args);

  if (args.length === 0) return;

  const errors = [];
  const nonErrors = [];
  args.forEach((a) => {
    if (a instanceof Error) errors.push(a);
    else nonErrors.push(a);
  });

  const error = errors.length > 0 ? errors[0] : new Error(String(nonErrors[0]));

  bugsnag.notify(error, (report) => {
    report.metadata = {
      args: nonErrors.map(nonError => String(nonError)),
    };
  });
}
```

**Comment by whalemare** [comment]
@mifi Thank you for snipper.
I am improve your solution by add typings required for TypeScript projects

```ts
export function logError(...args: any) {
  if (__DEV__) console.error(...args)

  if (args.length === 0) return

  const errors: Error[] = []
  const nonErrors: any[] = []
  args.forEach((a: any) => {
    if (a instanceof Error) errors.push(a)
    else nonErrors.push(a)
  })

  const error = errors.length > 0 ? errors[0] : new Error(String(nonErrors[0]))
  bugsnag.notify(error, report => {
    report.metadata = {
      args: nonErrors.map(nonError => String(nonError)).join("\n"),
    }
  })
}
```

**Comment by johnkiely1** [comment]
The [latest release](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.4) of the Bugsnag React native library includes support for this. 
As of v7.3 the library itself has now become part of the [bugsnag-js](https://github.com/bugsnag/bugsnag-js) repository.
An upgrade guide can be found [here](https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/UPGRADING.md) with full documentation available [here](https://docs.bugsnag.com/platforms/react-native/react-native/).
