### ISSUE TITLE
Bugsnag: The metadata recorded for key 'app' is not formatted as key/value pairs. Discarding.

### ISSUE THREAD

**Issue by SudoPlz** [bugsnag/bugsnag-react-native#133]
For some reason the metadata stopped getting attached.

https://github.com/bugsnag/bugsnag-react-native/blob/cb360fdad958e2284fc3ef3adb7bf8e4efe83c62/cocoa/BugsnagReactNative.m#L163

I've tried this way:

```
bugsnagConfig.registerBeforeSendCallback((report) => {
        const metadata = report.metadata || {};
        metadata.clients = {
             clientName: 'foo'
        };
        report.metadata = metadata;
      });
```

and that way:

```
bugsnagConfig.registerBeforeSendCallback((report) => {
        report.addMetadata('state', 'device', 'test')
      });
```

I get both:
`Bugsnag: The metadata recorded for key 'app' is not formatted as key/value pairs. Discarding.`
and 
`Bugsnag: The metadata recorded for key 'clients' is not formatted as key/value pairs. Discarding.`

in both cases.

What's going on? That same code used to work a while ago.

**Comment by kattrali** [comment]
Thanks for the report, @SudoPlz. Which versions of react native and bugsnag-react-native are you using? I'll reproduce.

**Comment by SudoPlz** [comment]
Follow up: I tried changing that NSLog to:
```
NSLog(@"Bugsnag: The metadata recorded for key '%@' is not formatted as key/value pairs for data %@ which is of type %@. Discarding.", sectionKey, metadata[sectionKey],NSStringFromClass( [metadata[sectionKey] class]));
```
and I now receive:
` Bugsnag: The metadata recorded for key 'app' is not formatted as key/value pairs for data [object Object] which is of type __NSCFString. Discarding.`

Heeeeeelp, I need that metadata.

Thanks

**Comment by kattrali** [comment]
Merging this into #132
