### ISSUE TITLE
Hey , can we show some custom alert , and close the app

### ISSUE THREAD

**Issue by ashrithks** [bugsnag/bugsnag-react-native#138]
can we show some custom alert , and close the app ,whenever there is a uncaught exceptions in js..

what I mean is ,

    errorHandler = (e, isFatal) => {
        if (isFatal) {
          this.reporter(e);
          Alert.alert(
            'Unexpected error occurred',
            `
              Error: ${(isFatal) ? 'Fatal:' : ''} ${e.name} ${e.message}${e}
              We have reported this to our team ! Please close the app and start again!
              `,
            [{
              text: 'Close',
              onPress: () => {
                BackAndroid.exitApp();
              }
            }]
          );
        } else {
          console.log(e); // So that we can see it in the ADB logs in case of Android if needed
        }
      };

then accept this method in,,

     setJSExceptionHandler = (customHandler = this.noop, allowedInDevMode = false) => {
        const allowed = allowedInDevMode ? true : !__DEV__;
        if (allowed) {
          global.ErrorUtils.setGlobalHandler(customHandler);
        } else {
          console.log('Skipping setJSExceptionHandler: Reason: In DEV mode and allowedInDevMode = false');
        }
      };

**Comment by kattrali** [comment]
Thanks for the report, @ashrithks. I think this is doable with a small adjustment - I'll try making an example.

**Comment by fractalwrench** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hey , can we show some custom alert , and close the app](https://trello.com/c/1qO5iNcE/14-hey-can-we-show-some-custom-alert-and-close-the-app)

**Comment by johnkiely1** [comment]
Hi @ashrithks,

Is this still something you are trying to achieve or have you found a way to make it work for your use case? I appreciate this is a rather old issue, are you now using the latest version of the library? If you still need assistance with this could you contact support@bugsnag.com and include all the relevant details and we will be happy to take a further look for you.
