### ISSUE TITLE
Bugsnag is polluting build log with warnings on IOS

### ISSUE THREAD

**Issue by tlvenn** [bugsnag/bugsnag-react-native#140]
When building the ios archive, xcode is emitting a lot of warnings because of bugsnag such as:

```
/Users/vagrant/git/node_modules/bugsnag-react-native/cocoa/vendor/kscrash/Source/KSCrash/Recording/Tools/NSString+Demangle.h:38:11: parameter 'symbol' not found in the function declaration [-Wdocumentation]
@param symbol The symbol to demangle.
```

```
/Users/vagrant/git/node_modules/bugsnag-react-native/cocoa/vendor/kscrash/Source/KSCrash/Recording/Tools/NSString+Demangle.h:46:11: parameter 'symbol' not found in the function declaration [-Wdocumentation]
@param symbol The symbol to demangle.
```

Etc..

This amount for a fairly big number of lines and literally cluter the build log.

BugsnagReactNative (2.3.2)
Xcode 8.3.3

**Comment by fractalwrench** [comment]
Thanks for the report @tlvenn - it looks like this is down to KSCrash, which is an external library we use within Bugsnag. We're currently in the process of forking KSCrash, so it should be possible to fix these documentation errors.
