### ISSUE TITLE
Android native exceptions not being reported

### ISSUE THREAD

**Issue by mobitar** [bugsnag/bugsnag-react-native#144]
Android native exceptions are not being reported for me. I've created a simple project to reproduce. The exception in particular is the "unexpected url" exception for XMLHttpRequest. To replicate, simply run this code:

```
// will create "unexpected url" error
var xmlhttp = new XMLHttpRequest();
var url = "http://localhost:3000d";
xmlhttp.open("GET", url, true);
xmlhttp.send();
```

The repro project is available here: https://github.com/mobitar/bugsnag-repro

I simply added the above code to index.android.js on a brand new project:
https://github.com/mobitar/bugsnag-repro/blob/master/index.android.js#L25

Any ideas why this is not reported?

P.S. JavaScript exceptions are being reported just fine. Only native aren't.

**Comment by fractalwrench** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Android native exceptions not being reported](https://trello.com/c/mRtHBa74/22-android-native-exceptions-not-being-reported)

**Comment by kattrali** [comment]
Thanks for the report and detailed example app, @mobitar. I'm able to reproduce what you're seeing in your example in debug mode. It seems that the react native handling which generates the red box interferes with detecting and delivering android crash reports. However, in a release build, crash reports are delivered as expected. I'll investigate further to see if there's a way to avoid this side effect, or if its something which should be documented.
