### ISSUE TITLE
Duplicate KSCrash symbols when using Sentry and Bugsnag together

### ISSUE THREAD

**Issue by zakster12** [bugsnag/bugsnag-react-native#151]
I have duplicate KSCrash symbols which causes a crash because I need to use Sentry and BugSnag in the same project but they both internally use KSCrash. The image shows the errors:

`"react-native-sentry": "0.23.2",`
`"bugsnag-react-native" : "2.4.1"`

Unfortunately I couldn't find which version of KSCrash Sentry is using internally.

![ghj](https://user-images.githubusercontent.com/25477229/31166013-db48fcca-a8f5-11e7-82d6-606e2bf192b6.png)

**Comment by fractalwrench** [comment]
@zakster12 v2.4.2 has been released which should fix this issue - we've tested this on a fresh project and existing project with Sentry 0.26 as a dependency. Please get in touch if you run into anything else

**Comment by zakster12** [comment]
@fractalwrench Great! It's working perfectly! Thank you so much for the effort!!!
