### ISSUE TITLE
Unable to configure notifyReleaseStages

### ISSUE THREAD

**Issue by junshengpierre** [bugsnag/bugsnag-react-native#162]
### Expected behavior
Bugsnag notifies exceptions based on configuration provided with `configuration.notifyReleaseStages`. `configuration.notifyReleaseStages = ['beta']` notifies development exceptions only based on https://docs.bugsnag.com/platforms/react-native/configuration-options/#notifyreleasestages

### Observed behavior
It works as expected when bugsnag is initialised with no params - `new Client(configuration)`. Both 'beta' and 'production' errors are notified. However, neither 'beta' nor 'production' errors are notified when bugsnag is initialised with `configuration`. I've tried setting `configuration.notifyReleaseStages` to `['beta', 'production']`, `['production']`, `['beta']` in dev and release modes and couldn't get any to work. Anyone knows what I could have missed?

### Steps to reproduce
In index.ios.js/index.android.js:
```javascript
import { AppRegistry } from 'react-native'
import App from './App/Containers/App'
import { Client, Configuration } from 'bugsnag-react-native'

let configuration = new Configuration()
configuration.notifyReleaseStages = ['beta']

const bugsnag = new Client(configuration)

AppRegistry.registerComponent('App', () => App)
```
### Version
bugsnag: 2.3.2
react-native: 0.46.4
platforms: android, iOS

**Comment by kattrali** [comment]
Thanks for the report, @junshengpierre. Are you [setting the release stage](https://docs.bugsnag.com/platforms/react-native/configuration-options/#releasestage) to `beta` at some point during the configuration? `beta` isn't a value which is set automatically. If it is not set, the three values which are set automatically are:

* `development` (checking if debug mode is enabled)
* `testflight` (on iOS and not in debug mode and a receipt is present)
* `production` (if debug mode is disabled)

One example would be:

```js
configuration.releaseStage = __DEV__ ? 'development' : 'beta'
```

Though I'm not sure what criteria is needed to determine which stage of your app is running.

**Comment by junshengpierre** [comment]
Thank you for the clarification, @kattrali. I wasn't setting release stage to `beta`. Setting `configuration.notifyReleaseStages = ['development']` worked well.

**Comment by emilefleming** [comment]
@kattrali Thanks for listing the release stages, I also had this issue. How did you come to know what they were? In the docs ([linked here](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#notifyreleasestages)) I only see 'beta' and 'production' listed. Is there an additional set of docs you know of? I'm really worried if these aren't accurate.

**Comment by xander-jones** [comment]
Hey @emilefleming. The three release stages that we automatically set are `production`, `development`, and `testflight`:
https://github.com/bugsnag/bugsnag-react-native/blob/6a02e1e06d3bea20b0ee8a3dc4b2fe81f10898e9/cocoa/BugsnagReactNative.m#L418-L427

We've made some modifications to our documentation to clarify this.
