### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by njt1982** [bugsnag/bugsnag-react-native#163]
On https://docs.bugsnag.com/platforms/react-native/#automatically-captured-breadcrumbs it mentions screenshots are automatically captured, but I cannot see where they are in the UI.

Do I need to configure them somehow?

**Comment by kattrali** [comment]
Thanks for the question, @njt1982. Bugsnag captures the screenshot event occurring (the system event indicating that a screenshot was made by the user). For privacy reasons, we do not capture and upload the images from users' devices. Does that make sense?

* [More information on the screenshot notification](https://developer.apple.com/documentation/foundation/nsnotification.name/1622966-uiapplicationuserdidtakescreensh)

**Comment by njt1982** [comment]
Ahh I see. It logs the event of a screenshot happening. I thought it meant it took a screenshot when there was an error!
