### ISSUE TITLE
Sourcemaps work with bugsnag.notify but do not work in unhandled errors(fatal exceptions)

### ISSUE THREAD

**Issue by jayshah123** [bugsnag/bugsnag-react-native#164]
### Expected behavior
Source maps should work with unhandled errors/fatal exceptions, as it works absolutely fine with bugsnag.notify

### Observed behavior
I added a line in js code which executes onPress of a touchable
``` js
throw new Error('Accidental tap error!');
```

### Steps to reproduce
Above code is executed on a tap, and fatal exception happens and is reported in bugsnag dashboard.

### Version
RN 0.48.4, bugsnag-react-native: ^2.4.2

### Additional information
This is done in a release build on android.
My app version matches the one seen in error in dashboard, And I have uploaded corresponding sourcemaps with matching version and source url - index.android.bundle and *index.android.bundle.
Still, This is what raw stacktrace looks like in the dashboard
```
com.facebook.react.common.JavascriptException Accidental Card Tap!, stack:
cardTapped@1018:1813
cardTapped@1067:2248
touchableHandlePress@252:1880
_performSideEffectsForTransition@166:8508
_receiveSignal@166:7291
touchableHandleResponderRelease@166:4735
Gt@113:21819
invokeGuardedCallback@113:22144
invokeGuardedCallbackAndCatchFirstError@113:22266
C@113:1870
y@113:2072
nn@113:22871
rn@113:22978
P@113:3019
processEventQueue@113:23821
G@113:5536
handleTopLevel@113:27372
<unknown>@113:28874
qn@113:28099
z@113:6018
perform@114:3484
batchedUpdates@114:18574
Ce@113:10516
Q@113:6049
K@113:6111
_receiveRootNodeIDEvent@113:28845
receiveTouches@113:29225
value@18:3223
<unknown>@18:957
value@18:2652
value@18:929
 
    ExceptionsManagerModule.java:56 com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError
    ExceptionsManagerModule.java:40 com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException
    Method.java:-2 java.lang.reflect.Method.invoke
    JavaMethodWrapper.java:363 com.facebook.react.bridge.JavaMethodWrapper.invoke
    JavaModuleWrapper.java:162 com.facebook.react.bridge.JavaModuleWrapper.invoke
    NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:148 android.os.Looper.loop
    MessageQueueThreadImpl.java:194 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:818 java.lang.Thread.run
```

**Comment by jayshah123** [comment]
I wonder there is no file/URL in JS stackframe?

**Comment by jayshah123** [comment]
As a workaround, I have tried doing bugsnag.notify from a globalhandler of ErrorUtils in RN, https://github.com/facebook/react-native/issues/1194 but the downside is there are now two errors, and the one which will show sourcemap correctly (via notify) will not have Java StackTrace, and the original fatal exception will not have js sourcemaps applied.

**Comment by kattrali** [comment]
Thanks for the report, @jayshah123. To clarify, the app version used when uploading the source maps (via `--app-version` or similar) is the same as the app version which appears in the error report on the Bugsnag dashboard? I'd also recommend sending a request via support@bugsnag.com so we can take a look and see if anything has gone awry with project configuration or uploaded source maps.

**Comment by jayshah123** [comment]
yes, the uploaded sourcemap was done with --app-version same as the one in report, 
Also, I've sent a support request.

**Comment by kattrali** [comment]
Thanks! It looks like there aren't any source maps uploaded for the React Native project at all. What command do you use to upload source maps, and was there any warnings or other output from the command to diagnose why source maps might not have been saved?

**Comment by kattrali** [comment]
Thanks, that helped. Seems to be two accounts for the same company name.

**Comment by kattrali** [comment]
There are a few things that would help to triage.

1. How did you configure the library? Is your configuration the same as the integration guide? Hopefully I can reproduce your setup exactly.

2. Can you retry with v2.5.0? Depending on your configuration, its possible that there are two bugsnag clients configured, causing some issues.

**Comment by jayshah123** [comment]
1. the client is configured as a singleton bugsnag.js (inspired from examples) that looks like following 
```
/* global __DEV__ */
// bugsnag.js
//-------------------------------------------------------------------------------------------------
// Create a singleton instance of the bugsnag client so we don't have to duplicate our configuration
// anywhere.
//-------------------------------------------------------------------------------------------------
// https://docs.bugsnag.com/platforms/react-native/#basic-configuration
import { Client, Configuration } from 'bugsnag-react-native';

const apiKey = __DEV__ ? 'devApiKey' : 'prodApiKey';
const configuration = new Configuration(apiKey);
const client = new Client(configuration);

//-------------------------------------------------------------------------------------------------
export default client;
```

Android native configuration is exactly same as given in https://docs.bugsnag.com/platforms/react-native/#android-native-configuration.

2. I will try with 2.5.0 and let you know.

**Comment by wellyshen** [comment]
My case is `bugsnag.notify(new Error('Test Error'))` works but iOS error won't send any report.

Bugsnag: 2.5.0
RN: 0.49.3
Platform: iOS
xCode: 9
iOS version: 11

**Comment by kattrali** [comment]
@jayshah123 Did upgrading resolve your issue?

**Comment by kattrali** [comment]
@wellyshen can you open a separate issue, it sounds like a different issue.

**Comment by wellyshen** [comment]
@kattrali The iOS errors works again. I think my concerning is solved. Thanks.

**Comment by jayshah123** [comment]
Well, I have updated to use ^2.5.1, but now nothing seem to reported all, let me see what is going on.

**Comment by jayshah123** [comment]
Our app does ErrorUtils.setGlobalHandler for some utility stuff. Is that the reason why our app's fatal exceptions are not reported? 
I'm looking more into this..

**Comment by kattrali** [comment]
@jayshah123 Yes, setting the global error handler would prevent fatal exceptions from being reported unless a reference to the previous global error handler is kept. [Here is how bugsnag.js does it](https://github.com/bugsnag/bugsnag-react-native/blob/master/src/Bugsnag.js#L44).

**Comment by jayshah123** [comment]
Ok, I see everything works now, but my sourcemap is off by some lines(usually 1-5 lines), 
There is a single error currently present in my project rnapp-prod. Is there a way to debug/fix this?

**Comment by fabriziobertoglio1987** [comment]
I am experiencing this issue. I did follow the docs and configure the app version correctly

Source mapping failed:A source map could not be applied
A source map was found but could not be applied because it doesn't match the code. Ensure that the source map is correctly generated and matches the version of your code. (Note that events are not reprocessed after source maps are uploaded.)

**Comment by abigail-bugsnag** [comment]
@fabriziobertoglio1987  thanks for reaching out! 
It sounds like your uploaded source maps may have been generated from a different version of your application than the version they have been uploaded against. 
There are some frequently asked questions available here for React Native source map uploads: https://docs.bugsnag.com/api/rn-source-map-upload/#frequently-asked-questions.
If you are still having trouble with this then please write into support@bugsnag.com, providing the link to the error where you are seeing this.

**Comment by rafaelcorreiapoli** [comment]
Hi. Im facing the same issue:
```
A source map was found but could not be applied because it doesn't match the code. Ensure that the source map is correctly generated and matches the version of your code. (Note that events are not reprocessed after source maps are uploaded.)
```

Here is my script that generates and uploads the source maps:

```
PACKAGE_VERSION=$(node -p -e "require('./package.json').version")

echo "Bundling Android Debug"
curl "http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false" > android-debug.bundle
curl "http://localhost:8081/index.bundle.map?platform=ios&dev=true&minify=false" > android-debug.bundle.map
echo "Ok"

echo "Uploading Android source maps Debug"
curl https://upload.bugsnag.com/react-native-source-map \
   -F apiKey=$BUGSNAG_API_KEY \
   -F appVersion=$PACKAGE_VERSION \
   -F dev=true \
   -F platform=android \
   -F sourceMap=@android-debug.bundle.map \
   -F bundle=@android-debug.bundle \
   -F projectRoot=`pwd`
echo "Ok"
```

Here is my config:
```
import { Client, Configuration } from 'bugsnag-react-native'

const config = new Configuration('f87da94c0710e135e3c6ddd443d65039')
config.appVersion = require('../../../package.json').version
export const bugsnag = new Client(config)
```

**Comment by fabriziobertoglio1987** [comment]
@rafaelcorreiapoli I had the same issue. 
The bugsnag team closed my post and told me by email to just re-upload the sourcemaps.

I re-uploaded the sourcemaps 20 times and never got fixed.
The issue is on their server side.

15 days later my free trial expired
It would be too much work to generate the sourcemaps for every release

so I just keep it minified for now and I will search a better service in the future.
Bugsnag takes too much effort to configure

**Comment by mattdyoung** [comment]
@rafaelcorreiapoli @fabriziobertoglio1987 
The specific message:
_A source map was found but could not be applied because it doesn't match the code. Ensure that the source map is correctly generated and matches the version of your code. (Note that events are not reprocessed after source maps are uploaded.)_

is displayed if one or more frames in the reported stacktrace are a location that doesn't have a mapping defined in the source map you've uploaded.

This could be the case if the code running on the device doesn't match the code you've generated the source map from (for example if you've labelled an uploaded source map with the wrong app version or modified the code after generating prior to releasing your app).

Or it could be due to a bug in the software used to generate the source map (this was the case for a number of configurations in earlier versions of React Native).

Either way, this isn't due to a bug in bugsnag-react-native. It could be misconfiguration or an issue with how the source map is generated.

The best way to resolve these issues is to contact support@bugsnag.com with details of what you've tried and a link to the Bugsnag error on which you're seeing this message and we can work with you to identify the cause.

Thanks!
