### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by danbenn** [bugsnag/bugsnag-react-native#166]
### Expected behavior
I used **Cocoapods** to add React native to my existing iOS app. 

### Observed behavior
<img width="347" alt="screen shot 2017-10-13 at 11 48 07 am" src="https://user-images.githubusercontent.com/12377258/31555086-b8b6189a-b00d-11e7-931e-43b7622c74cc.png">

Xcode can't seem to link React library files with Bugsnag. 

Solutions on the Internet suggest unchecking "parallelize build" under the main project scheme, and adding React. I did these steps, but this still didn't fix it. Here's my scheme:

<img width="672" alt="screen shot 2017-10-13 at 12 01 15 pm" src="https://user-images.githubusercontent.com/12377258/31555241-45e14032-b00e-11e7-830f-171761a39864.png">

I've also tried changing the header imports manually, and that stops the errors one by one but it's not a sustainable solution.

E.g., '#import <React/RCTBridgeModule.h>' => '#import "RCTBridgeModule.h"

I also tried adding React to the header search paths, but that had no effect. Here are my settings under Project Settings => Build Settings => Header Search Paths:

<img width="523" alt="screen shot 2017-10-13 at 12 06 11 pm" src="https://user-images.githubusercontent.com/12377258/31555457-0e51dd10-b00f-11e7-8aee-f1cf42bb6000.png">

### Version
Bugsnag-react-native v. 2.5.0
react-native v. 0.48.3
XCode v. 9.0

### Additional information
In RN 0.40.0 the library files were reorganized into the React namespace: '#import <React/RCTBridgeModule.h>' => '#import "RCTBridgeModule.h"... yet somehow Xcode didn't catch on to this.

**Comment by kattrali** [comment]
Thanks for the report, @danbenn. I have a working example with cocoapods in https://github.com/bugsnag/bugsnag-react-native/pull/167, can you try running that branch project or comparing the configuration to see if there's something missing?

Is React Native also installed via CocoaPods?

**Comment by danbenn** [comment]
Awesome, thanks! I didn't realize I could install with Cocoapods as opposed to `react-native link`. 

Adding this line to my Podfile fixed it:

`pod 'BugsnagReactNative', path: './node_modules/bugsnag-react-native'`

**Comment by harrisrobin** [comment]
My issue had nothing to do with bugsnag but with the fact that i was using react-native 0.57.8  but forgot to update react to 16.6.3 which is absolutely necessary.
