### ISSUE TITLE
disabling auto breadcrumbs

### ISSUE THREAD

**Issue by JonasWho** [bugsnag/bugsnag-react-native#168]
In the javascript API, there is a possibility to disable autobreadcrumbs like this:
Bugsnag.disableAutoBreadcrumbs();

But in React Native docs, I can't find anything. And client.disableAutoBreadcrumbs() does not work.

Am I doing it wrong or is it not implemented for RN yet?

**Comment by kattrali** [comment]
Hi @JonasWho, there is currently no JS interface to disabling automatic breadcrumbs on react native, though this is something we should add. In the meantime, you can use the native interfaces for android and iOS. Is there somewhere in the docs which mention `disableAutoBreadcrumbs()`?
