### ISSUE TITLE
com.facebook.react.bridge.NoSuchKeyException · couldn't find key severityReason in dynamic object

### ISSUE THREAD

**Issue by tomauty** [bugsnag/bugsnag-react-native#178]
### Expected behavior
*This error doesn't occur*

### Observed behavior
*A spike in this error on production as of yesterday*

### Steps to reproduce
*Seems it happens when any error occurs*

### Version
*2.5.0*

### Additional information
We've seen a very large spike in this error in the last 24 hours. The full stack is below

```
com.facebook.react.bridge.NoSuchKeyException · couldn't find key severityReason in dynamic object
Raw
ReadableNativeMap.java:-2com.facebook.react.bridge.ReadableNativeMap.getString	
BugsnagReactNative.java:123com.bugsnag.BugsnagReactNative.notifyBlocking	
Method.java:-2java.lang.reflect.Method.invoke	
JavaMethodWrapper.java:363com.facebook.react.bridge.JavaMethodWrapper.invoke	
JavaModuleWrapper.java:162com.facebook.react.bridge.JavaModuleWrapper.invoke	
NativeRunnable.java:-2com.facebook.react.bridge.queue.NativeRunnable.run	
Handler.java:751android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
MessageQueueThreadHandler.java:31com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage	
Looper.java:154android.os.Looper.loop	
MessageQueueThreadImpl.java:194com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run	
Thread.java:762java.lang.Thread.run
```

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by tomauty** [comment]
I should mention we don't use the client's `notify` function manually anywhere in our codebase.

**Comment by fractalwrench** [comment]
Thanks for the report @tomauty - have you recently updated either the Bugsnag/React Native versions, or has this just happened spontaneously?

**Comment by tomauty** [comment]
Seems pretty spontaneous. We haven't made any updates since our previous version release, which was before this started happening:

<img width="414" alt="screen shot 2017-11-06 at 12 45 48 pm" src="https://user-images.githubusercontent.com/1112872/32455513-855fc644-c2f0-11e7-86fc-38574fff7085.png">

**Comment by mehdijjz** [comment]
I'm having the same issue, I freaked out when I looked at my app's Crashlytics statistic

**Comment by fractalwrench** [comment]
@mehdijjz are you using the same Bugsnag library version? Has this also just occurred spontaneously for you? Any additional information would be helpful for debugging this.

**Comment by mehdijjz** [comment]
@fractalwrench No my bugsnag version is `^2.3.2` and my RN version is `0.48.2`. this is the stack trace, I'm not sure if it's bugnsag's issue or not
[
<img width="543" alt="screen shot 2017-11-16 at 19 40 56" src="https://user-images.githubusercontent.com/16239413/32901890-3bc5526a-cb06-11e7-987e-37e95259c257.png">
](url)

**Comment by fractalwrench** [comment]
@mehdijjz have you noticed any similar spikes for Native iOS crashes? Would you be able to find the bugsnag-react-native version in your yarn.lock file?

**Comment by mehdijjz** [comment]
@fractalwrench Actually my bugsnag version was `2.3.2`, but it is possible that we've mistakenly code-pushed when it was `^2.3.2`. Maybe the reason is that the js version gets higher than the native version this way?

and by the way, I don't know if it's related or not but I can't tell whether it's `notify` or the `new Error` part which is making this error
<img width="557" alt="screen shot 2017-11-18 at 09 42 18" src="https://user-images.githubusercontent.com/16239413/32977561-ce75103e-cc44-11e7-887e-cd610e59ae60.png">

**Comment by fractalwrench** [comment]
This should be fixed in `2.7.1`.

@mehdijjz that issue doesn't look related - is that still a problem? I'll spin off a separate issue if so.

**Comment by mehdijjz** [comment]
@fractalwrench do we have to also update native code when updating ?

**Comment by fractalwrench** [comment]
@mehdijjz we'd definitely recommend using the same versions of the native code and JS code - it's possible that code push could have caused that. Our [changelog](https://github.com/bugsnag/bugsnag-react-native/blob/master/CHANGELOG.md) should document any upgrade steps, but feel free to get in touch if you run into anything.

**Comment by anuragdadheech** [comment]
Observing this on `2.8.0`

react: 16.0.0
react-native: 0.51.0

**Comment by tobob** [comment]
guys, make sure that bundle is up to date `react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` after you update packages via npm or yarn
