### ISSUE TITLE
can run in simulator but can't archive

### ISSUE THREAD

**Issue by iwater** [bugsnag/bugsnag-react-native#18]
xcode 8.0/8.1
mac os 10.12.1
react-native 0.36
bugsnag-react-native 1.0.4

when archive show error "'KSCrash/KSCrashReportFilter.h' file not found"

**Comment by kattrali** [comment]
Thank you for the report, @iwater. Are there any other messages displayed? Alternately, can you running `Product > Clean` from the Xcode menu and then retry? There might be a cache of old app artifacts.

**Comment by ahanriat** [comment]
I'm having the same issue. I've cleaned the project but, tried to reinstall my node_modules etc..
I've managed to install on real device (iPhone 6) and simulator without any issue.

Here is my error
`/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/BugsnagConfiguration.m:27:9: 'KSCrash/KSCrashReportWriter.h' file not found`

**Comment by kattrali** [comment]
Thanks for the confirmation, @ahanriat. Are you archiving via Xcode or perhaps a CLI tool? I am having some trouble reproducing this issue, though I’m sure we can figure it out. :)

**Comment by ahanriat** [comment]
I'm using Xcode to archive the App :)

**Comment by kattrali** [comment]
Can you try cleaning the build directory? (Cmd+Shift+Option+K in Xcode)

**Comment by ahanriat** [comment]
Unfortunately I still have the issue even after a deep clean of Xcode. As the problem only occurs when archiving, it should come from the architecture right ?

**Comment by kattrali** [comment]
Hmm. Possibly, but are you archiving for an architecture other than `$(ARCHS_STANDARD)` (armv7, arm64)?

**Comment by ahanriat** [comment]
Nope I'm not :/

**Comment by kiatweitan** [comment]
![screen shot 2016-11-02 at 11 58 24 am](https://cloud.githubusercontent.com/assets/7495667/19916290/b18f496c-a0f3-11e6-8501-d9ad80020c14.png)

Same issue here:
xcode 8.0
mac os 10.11.6
react-native 0.36
bugsnag-react-native 1.0.4

**Comment by kattrali** [comment]
It seems odd that I haven't been able to reproduce this in a fresh project, but maybe swapping the imports for local ones (e.g. `#import "KSCrashReportWriter.h"`) might work?

**Comment by nalinda** [comment]
Go to Link Binary with Libraries and try adding Bugsnag.framework.

**Comment by thomasdelobel** [comment]
We encounter the same issue (i.e. making the module work perfectly in Debug, Profile, Analyze, but impossible to Archive and so release our app). 

We spent hours trying to find out what could cause the issue, but without success. The only thing I'm sure is the Bugsnag.xcodeproj doesn't manage to link to KSCrash-iOS when it comes to libBugsnagLib creation during the archive process. I tried to solve this using different ways (compilation links, search paths, using frameworks instead of libs, ...), but nothing worked. And we are not enough expert in iOS development to really understand the deep functioning and specifics of Cocoa archiving.

We will release soon and have no time, so we move to the soon deprecated react-native-bugsnag until a fix is found for this issue.

Good luck guys !

react-native@0.34.1
react-native-bugsnag@1.0.1

Xcode Version 8.1 (8B62)
macOS 10.12.1 (16B2657)

Project Deployment Target : 8.0   ->  Bugsnag seems to be 10 (warnings)
Build files local to the project  ->  also tried with output files built in Xcode default folders

**Comment by kattrali** [comment]
Thanks for the write-up, @thomasdelobel.

> The only thing I'm sure is the Bugsnag.xcodeproj doesn't manage to link to KSCrash-iOS when it comes to libBugsnagLib creation during the archive process.

Well, it should be linking against libKSCrashLib, not KSCrash-iOS.framework. I'll double check that the conditions are correct.

> Project Deployment Target : 8.0 -> Bugsnag seems to be 10 (warnings)

This is notable. I'll patch this bit to see if its related.

**Comment by kattrali** [comment]
Updated the project settings in [v1.1.1](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v1.1.1). It could potentially fix what’s happening here? Its still hard to determine since the configuration builds for me consistently. Can you test this, @ahanriat?

**Comment by ahanriat** [comment]
@kattrali thanks I'll try it now

**Comment by ahanriat** [comment]
Unfortunately I'm still having the same issue, even after cleaning etc.. 😢

**Comment by kattrali** [comment]
Thanks @ahanriat, can you post the exact message from the build output, or make a gist of it?

**Comment by kfbow** [comment]
+1 Having the same issue after cleaning and adding Bugsnag.framework.

**Comment by kattrali** [comment]
Definitely don't add bugsnag.framework. That would actually cause this issue.

**Comment by kfbow** [comment]
Oh I tried it with just the cleaning first. Then tried the other recommendation. I'm going to try with v1.1.1 now.

**Comment by kfbow** [comment]
Thought I would post the message..

Message: 
```
node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/BugsnagSink.h:28:9: 'KSCrash/KSCrashReportFilter.h' file not found
````

**Comment by kattrali** [comment]
Ah, thanks @kfbow.

**Comment by kattrali** [comment]
Ok, I’ve tried this with a new project, added and documented on the [kattrali/sample-project-1.1.1](https://github.com/bugsnag/bugsnag-react-native/tree/kattrali/sample-project-1.1.1) branch, which includes instructions to reproduce. Can anyone try running the project and confirming that their list of linked libraries looks similar to the screenshot?

**Comment by kfbow** [comment]
@kattrali I tried on a new project and was able to successfully get the project to archive but the archive is placed under the "Other Items" section in the Organizer, this may be unrelated but this only happened after the `npm i bugsnag-react-native` then `react-native link`.

**Comment by asciiman** [comment]
I'm experiencing this issue as well.
RN 0.34.1

I installed 1.1.0 yesterday and got the error.  Upgraded today to 1.1.1 and same error.

The xcode hints give this clue as well:
```
/Users/xxx/Documents/Code/xxx/mobile-app/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/Bugsnag.m:32:9: In file included from /Users/xxx/Documents/Code/xxx/mobile-app/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/Bugsnag.m:32:
```

**Comment by kattrali** [comment]
Alright! Thank you, this definitely helps, @kfbow. 

@asciiman Is there another line after or before that file path to indicate an error message?

**Comment by asciiman** [comment]
`In file included from /Users/asciiman/Documents/Code/GoStudent/mobile-app/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/Bugsnag.m:32:
/Users/asciiman/Documents/Code/GoStudent/mobile-app/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/BugsnagSink.h:28:9: fatal error: 'KSCrash/KSCrashReportFilter.h' file not found
#import <KSCrash/KSCrashReportFilter.h>`

**Comment by asciiman** [comment]
@kattrali We can set up a zoom session and you can look around on my system if you'd like to.

**Comment by kattrali** [comment]
I’ve pushed [v1.1.2](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v1.1.2), which should address the missing headers as well as the generic archive problem. Would it be possible to retest, @asciiman @kfbow. If not, @asciiman can you send an email to support@bugsnag.com so we can set up a zoom session? We’ve got to be close to figuring this one out.

**Comment by asciiman** [comment]
It worked!!

**Comment by ahanriat** [comment]
🎉  Yeah it works ! Thanks @kattrali 👍

**Comment by iwater** [comment]
works now

**Comment by kattrali** [comment]
Awesome! Thanks everyone, all of the feedback helped. :)

**Comment by littlehome-eugene** [comment]
May I know what you changed for the header problem? I'm experiencing the same issue with different library and your work might help a great deal.

**Comment by yg-park** [comment]
@littlehome-eugene You can see changed code here. https://github.com/bugsnag/bugsnag-react-native/compare/v1.1.1...v1.1.2
