### ISSUE TITLE
method does not override or implement a method from a supertype   @Override

### ISSUE THREAD

**Issue by shyam528** [bugsnag/bugsnag-react-native#186]
Hi, I am using bugsnag-react-native version 2.2.3, I am getting below error while building in android
**"method does not override or implement a method from a supertype @Override"**
and in ios, it's working fine.
and when i comment **@Override** in node_modules/bugsnag-react-native/android/src/main/java/com/bugsnag/BugsnagReactNative.java file then it' successfully build.

I replaced this
**@Override
  public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
  }**
to

**//@Override
  public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
  }**

and it's working

when i use latest version so i am getting so many errors.
So please suggest

**Comment by fractalwrench** [comment]
Thanks for the report @shyam528 - this has been addressed in #136 and is fixed since `v2.3.0`.

**Comment by shyam528** [comment]
Thanks for the reply. Is there any other solution for this, instead of commenting, coz when we submit this app to the client, we cannot say to them for commenting in node module. 
When I am using upper version, I am getting few more errors.that'y dont want to update module.
Thanks

**Comment by fractalwrench** [comment]
@shyam528 which version are you seeing errors in? If that's preventing you from updating I can investigate the issue with more details.

Another alternative is using RN <0.46 or below, which still contains those overridden methods.

**Comment by shyam528** [comment]
@fractalwrench I am using 2.2.3 version

**Comment by fractalwrench** [comment]
@shyam528 are there any errors within the Bugsnag React Native library which are preventing you from upgrading?

**Comment by shyam528** [comment]
@fractalwrench No ,there is no any error while upgrading but my app doesn't build successfully when I use the updated version.

**Comment by fractalwrench** [comment]
@shyam528 if your app is failing to build because of the Bugsnag React Native library, then I'm happy to look into that given more details.

**Comment by shyam528** [comment]
@fractalwrench  sure, when i am using v: 2.2.3 it's working fine when I comment as told you previously, but I don't want to comment that and then I upgrade it to v-2.7.0 then I am getting following error.. please suggest and thanks a lot to reply too soon

 FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.android.support:support-annotations:27.0.0.
  Searched in the following locations:
      file:/Users/shyam/Library/Android/sdk/extras/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/Library/Android/sdk/extras/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      file:/Users/shyam/Library/Android/sdk/extras/google/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/Library/Android/sdk/extras/google/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      file:/Users/shyam/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      file:/Users/shyam/.m2/repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/.m2/repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      https://jcenter.bintray.com/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      https://jcenter.bintray.com/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      file:/Users/shyam/projects/PilotMobile-master/node_modules/react-native/android/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/projects/PilotMobile-master/node_modules/react-native/android/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
  Required by:
      project :app > project :bugsnag-react-native > com.bugsnag:bugsnag-android:4.1.3
> Could not find com.android.support:support-annotations:27.0.0.
  Searched in the following locations:
      file:/Users/shyam/Library/Android/sdk/extras/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/Library/Android/sdk/extras/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      file:/Users/shyam/Library/Android/sdk/extras/google/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/Library/Android/sdk/extras/google/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      file:/Users/shyam/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      file:/Users/shyam/.m2/repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/.m2/repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      https://jcenter.bintray.com/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      https://jcenter.bintray.com/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
      file:/Users/shyam/projects/PilotMobile-master/node_modules/react-native/android/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
      file:/Users/shyam/projects/PilotMobile-master/node_modules/react-native/android/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
  Required by:
      project :app > com.android.support:appcompat-v7:23.0.1 > com.android.support:support-v4:23.0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by fractalwrench** [comment]
@shyam528 the fix for this is in the changelog and detailed in #180 - you'll need to add `maven { url 'https://maven.google.com' }` to your build.gradle file.

**Comment by shyam528** [comment]
@fractalwrench  I have added it already :(

**Comment by shyam528** [comment]
my build.gradle file 
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

**Comment by shyam528** [comment]
@fractalwrench  and when I replace 
```
maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
```
to 
`maven { url 'https://maven.google.com' }`

getting following error

```
/Users/shyam/projects/PilotMobile-master/android/app/src/main/java/com/pilotmobile/MainApplication.java:5: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/Users/shyam/projects/PilotMobile-master/android/app/src/main/java/com/pilotmobile/MainApplication.java:9: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/Users/shyam/projects/PilotMobile-master/android/app/src/main/java/com/pilotmobile/MainApplication.java:17: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  symbol: class ReactApplication
/Users/shyam/projects/PilotMobile-master/android/app/src/main/java/com/pilotmobile/MainApplication.java:19: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/shyam/projects/PilotMobile-master/android/app/src/main/java/com/pilotmobile/MainApplication.java:37: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
         ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/shyam/projects/PilotMobile-master/android/app/src/main/java/com/pilotmobile/MainActivity.java:7: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
       ^
/Users/shyam/projects/PilotMobile-master/android/app/src/main/java/com/pilotmobile/MainApplication.java:19: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/shyam/projects/PilotMobile-master/android/app/src/main/java/com/pilotmobile/MainApplication.java:36: error: method does not override or implement a method from a supertype
  @Override
  ^
8 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see
``` the compiler error output for details.

**Comment by shyam528** [comment]
@fractalwrench  Thank you so much to be so helpful, It's working now, i have to keep both maven

```
maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
```

`maven { url 'https://maven.google.com' }`

Thanks alot :)
