### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by jslok** [bugsnag/bugsnag-react-native#188]
I have bugsnag working on android, but crash reports are not being sent from my iOS app. I followed the steps exactly as they are in the installation instructions and reinstalled/relinked several times with no luck. https://docs.bugsnag.com/platforms/react-native/#ios-native-configuration

Setting api key in either info.plist or in the configuration object does not work. Using bugsnag.notify() also did not send a report to my dashboard.

RN 0.49.5
Bugnsag-react-native 2.7.3

```
import { Client, Configuration } from 'bugsnag-react-native';
const configuration = new Configuration();
configuration.apiKey = "myapikey";
const bugsnag = new Client(configuration);
bugsnag.notify("Test error");
```

Any help would me much appreciated!

**Comment by kattrali** [comment]
Thanks for the report, @jslok. Can you try cloning the repository and using your API key in the [example app](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/plain)? If that works, then we can determine which part of the configuration is different between your app and the example. 

Are you running the application using Xcode or `react-native run-ios`? If using the former, there maybe some build warnings or debugging log messages printed which will help determine what the issue is.

**Comment by jslok** [comment]
@kattrali Thanks for the reply. I was able to get bugsnag to log reports, but only sometimes. bugsnag.notify("some error") does not work in any case. If I create an error such as console.log(someUndefinedVariable), then bugsnag will log errors to the dashboard when this line is placed in index.js, app.js, or my login screen (which is the first screen). After the login screen, no errors are logged to the dashboard. This is only an issue on ios. Bugsnag works as expected on android with my same app. Any ideas?

**Comment by kattrali** [comment]
Thanks for the update, @jslok. I wasn't sure based on your initial comment, but is bugsnag-react-native being initialized at the top of index.js (your entry point) or some other file?

**Comment by jslok** [comment]
@kattrali its initialized in index.js.

**Comment by kattrali** [comment]
Thanks. I'm having some trouble reproducing the issue, is there anything different between your app and the [example 0.51 app here](https://github.com/bugsnag/bugsnag-react-native/tree/kattrali/test-189/examples/example-0.51)? And what do you mean by screens? Using react-navigation or something else?

**Comment by tonygriv** [comment]
+1

I don't see any reports at all in my Bugsnag dashboard, but in XCode logs 

`INFO : BSG_KSCrash.m (348): -[BSG_KSCrash sendAllReportsWithCompletion:]: Sending 3 crash reports
2017-12-11 14:20:41.089304+0300 carrier_mobile_app[78720:6062722] Reports sent.`

**Comment by itinance** [comment]
For me, "notify"-calls are working as expected but real crashes aren't logged at all with bugsnag.

**Comment by fractalwrench** [comment]
Consolidating into #191
