### ISSUE TITLE
[v2.7.5] Not able to report fatal errors on development

### ISSUE THREAD

**Issue by chitrangsinghvi** [bugsnag/bugsnag-react-native#189]
### Steps to reproduce
configuration.notifyReleaseStages = ['beta', 'production', 'development'];
console.log(someUndefinedVariable) inside render function of App.js

### Expected behavior
Should report to bugsnag

### Observed behavior
No report to bugsnag

### Environment

- react-native version: 0.50.3
- bugsnag-react-native version: 2.7.5
- iOS/Android version(s): 11.1
- Simulator or physical device?: Both

**Comment by kattrali** [comment]
Thanks for the report, @chitrangsinghvi. Are you setting [`releaseStage`](https://docs.bugsnag.com/platforms/react-native/configuration-options/#releasestage) in addition to `notifyReleaseStages`?

**Comment by chitrangsinghvi** [comment]
currently no, i am only setting notifyReleaseStages

**Comment by kattrali** [comment]
Gotcha, thanks. I made an example app [here](https://github.com/bugsnag/bugsnag-react-native/tree/kattrali/test-189/examples/example-0.51) to reproduce, but it seems to be reporting as expected. Can you confirm that the setup is the same as your app, or try running it to see if you get a different result?

* [Changeset](https://github.com/bugsnag/bugsnag-react-native/commit/e805baaaf8f21535a1e7d810caad0434ae516ab4)
* [Example instructions](https://github.com/bugsnag/bugsnag-react-native/blob/kattrali/test-189/examples/example-0.51/readme.md)

As an aside, without setting `releaseStage`, using `"beta"` in `notifyReleaseStages` has no effect, as it is never used. The `notifyReleaseStages` list is compared to the `releaseStage` to determine whether Bugsnag should send reports and provide a simple way to disable error reports during development or testing.
* [How its used in JS](https://github.com/bugsnag/bugsnag-react-native/blob/master/src/Bugsnag.js#L238-L242)
* [How its used natively](https://github.com/bugsnag/bugsnag-react-native/blob/0d97716b538a7b2f62b819ec6b0ac665f10a6632/cocoa/vendor/bugsnag-cocoa/Source/BugsnagConfiguration.m#L71-L74)

**Comment by dwilt** [comment]
I'm currently running into this issue I believe. I can call `client.notify(new Error('test'))` and it reports to bugsnag successfully but if I throw a test error like `throw new Error('test')` somewhere in my code, it doesn't get reported (basically all unhandled exceptions are not reporting)

**Comment by fractalwrench** [comment]
Consolidating into #191
