### ISSUE TITLE
Need manual installation guide

### ISSUE THREAD

**Issue by devhyunjae** [bugsnag/bugsnag-react-native#19]
My Version
```
react native: 0.36
bugsnag: 1.0.4
```

In IOS,

```react-native link```

doesn't automatically map with the sdk.

So I had to manually do Linking with the library in the XCode.

You should probable update the installation guide manually for option

**Comment by kattrali** [comment]
Thank you for the report, @devhyunjae. This is likely related to whatever is happening in https://github.com/bugsnag/bugsnag-react-native/issues/14#issuecomment-256985894. I’ve updated the docs to add some iOS installation validation steps, which should be live shortly.
