### ISSUE TITLE
bugsnag notifications when offline

### ISSUE THREAD

**Issue by ferdicus** [bugsnag/bugsnag-react-native#190]
Sorry for not filling out the issue template, however this is a more general question.

What happens if bugsnag tries to send a notification when the device is offline?
Does it cache the notification and send it out on a later time when the device is online again, or does it simple swallow it?

**Comment by kattrali** [comment]
No problem, @ferdicus.

> What happens if bugsnag tries to send a notification when the device is offline?

When offline, unsent reports are cached on disk and then delivered once the network status changes (or the next time the app starts, if the app is killed before the reports are able to be delivered).
