### ISSUE TITLE
Installation via CocoaPods will add outdated dependency React 0.11.0

### ISSUE THREAD

**Issue by itinance** [bugsnag/bugsnag-react-native#193]
### Steps to reproduce

```
react-native init test
cd test
yarn add bugsnag-react-native
cd ios

```
create a Podfile with:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

end
```

```
$ pod install
Analyzing dependencies
Fetching podspec for `BugsnagReactNative` from `../node_modules/bugsnag-react-native`
Downloading dependencies
Installing BugsnagReactNative (2.7.5)
Installing React (0.11.0)
Generating Pods project
Integrating client project

[!] React has been deprecated
```

<img width="735" alt="screen shot 2018-01-01 at 20 15 48" src="https://user-images.githubusercontent.com/1758597/34470421-aaf35382-ef30-11e7-958f-54080381254d.png">

### Expected behavior

Correct installation with latest Version React 16.0.0 (or now installation since it was already integrated)

### Observed behavior

Installation of React 0.11.0

### Environment

- react-native version:0.51.0
- bugsnag-react-native version: 2.7.5
- react-native-code-push version (if any): none
- cocoapods version (if any): 1.3.0
- debug mode or production?: does not apply here

**Comment by tomer1490** [comment]
Try adding in your Podfile: `pod 'React', :path => '../node_modules/react-native'`. It should tell Cocoapods to use the version of react installed from package.json.

**Comment by kattrali** [comment]
@tomer1490 is correct. Since React is not published via CocoaPods, the React pod must be referenced locally in your Podfile. 

Example Podfile:

```ruby
# React Native requirements
pod 'yoga', path: './node_modules/react-native/ReactCommon/yoga'
pod 'DoubleConversion', :podspec => './node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'GLog', :podspec => './node_modules/react-native/third-party-podspecs/GLog.podspec'
pod 'React', path: './node_modules/react-native', subspecs: [
  'Core',
  'jschelpers',
  'cxxreact',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTWebSocket',
]

pod 'BugsnagReactNative', path: './node_modules/bugsnag-react-native'
```

* [Example app and configuration guide to using `bugsnag-react-native` and CocoaPods](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/ios-cocoapods-component)
* [React Native docs on integrating with CocoaPods](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html)

**Comment by tapz** [comment]
This does not work with React 0.53.0 (or 0.52.x).

```
error: bundling failed: ambiguous resolution: module `/Users/john/projects/myapp/myapp-mobile-app/src/App.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/john/projects/myapp/myapp-mobile-app/ios/Pods/React/package.json`
  * `/Users/john/projects/myapp/myapp-mobile-app/node_modules/react-native/package.json`
```

**Comment by haluong89** [comment]
Thanks @osdnk but it doesn't work for me:(

**Comment by StijnCoolen** [comment]
@kattrali why did you close? Adding bugsnag to react-native shouldn't be the same as adding react-native to an existing iOS project. I think this is still an issue.

**Comment by cristianoccazinsp** [comment]
Is it possible to avoid using pods directly? Having the same issue.

**Comment by Foskas** [comment]
Any solution ? Nothing works for this.

**Comment by mattdyoung** [comment]
@Foskas 
Are you saying that even when you reference React in your Podfile as described here:
https://github.com/bugsnag/bugsnag-react-native/issues/193#issuecomment-355166756

you're still getting React 0.11.0 installed?

Have you run `pod update`?
