### ISSUE TITLE
Crashes aren't detected on iOS in production mode

### ISSUE THREAD

**Issue by itinance** [bugsnag/bugsnag-react-native#194]
We've setup Bugsnag successfully as we can send notifications via "client.notify(new Error('test'))" to our bugsnag-Dashboard.

Nevertheless, hard crashes aren't monitored at all. Even not after waiting for some hours to appear.

```
#import <BugsnagReactNative/BugsnagReactNative.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  [BugsnagReactNative start];

```

**Comment by kattrali** [comment]
Thanks for the report, @itinance. Are the hard crashes being created manually and if so can you provide an example of how the crash is generated?

**Comment by itinance** [comment]
@kattrali thx for reaching back! We have some issues on our app especially for iOS where some crashes occur from time to time when running in release mode on real device.
They are hard to reproduce and first and foremost hard to catch. We hoped that they would get catched by Bugsnag as it has worked in another project very well some months ago. Unfortunately not this time.

**Comment by kattrali** [comment]
Gotcha, thanks @itinance. So some hard crashes are captured while others never appear?

**Comment by jcharbo** [comment]
I'm experiencing this as well.  A handful of crashes are coming through but the majority are not.  I don't see any particular pattern.  When calling bugsnag.notify from the ios simulator I get the following in xcode:
INFO : BSG_KSCrashReport.c (2157): void bsg_kscrashreport_writeStandardReport(BSG_KSCrash_Context *const, const char *const): Writing crash report to /Users/jeremey/Library/Developer/CoreSimulator/Devices/753F3144-F93C-4B3C-9C16-0FF1FD438D07/data/Containers/Data/Application/109C8832-D165-4992-AEF7-A20CECF5146C/Library/Caches/KSCrashReports/thejumpstaging/thejumpstaging-CrashReport-4C8EB9BD-C759-49AF-8E00-5C49C6946A7B.json
INFO : BSG_KSCrash.m (373): -[BSG_KSCrash sendAllReportsWithCompletion:]: Sending 1 crash reports

**Comment by fractalwrench** [comment]
Consolidating into #191
