### ISSUE TITLE
error: package com.bugsnag does not exist

### ISSUE THREAD

**Issue by nicklas669** [bugsnag/bugsnag-react-native#196]
Hi, having a problem after trying to add bugsnag to my project.

### Steps to reproduce
Followed the guide at [https://docs.bugsnag.com/platforms/react-native/](https://docs.bugsnag.com/platforms/react-native/) for installing for Android.
1. yarn add bugsnag-react-native --save
2. react-native link
3. Ensure that Google’s maven repository is specified in your android/build.gradle
4. Set your API key in your AndroidManifest.xml.
5. initialize Bugsnag in the onCreate function of MainApplication.java
6.  import and initialize Bugsnag within index.android.js
7. Try to run app on my phone using 'react-native run-android'

### Expected behavior
App should build and load on my phone

### Observed behavior

```
App build fails with the following message:
:app:compileDebugJavaWithJavac
 :app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
 D:\reduxlearning\android\app\src\main\java\com\reactnativereduxlearning\MainApplication.java:6: error: package com.bugsnag does not exist
import com.bugsnag.BugsnagReactNative;
                  ^
D:\reduxlearning\android\app\src\main\java\com\reactnativereduxlearning\MainApplication.java:30: error: cannot find symbol
           BugsnagReactNative.getPackage(),
           ^
   symbol: variable BugsnagReactNative
 D:\reduxlearning\android\app\src\main\java\com\reactnativereduxlearning\MainApplication.java:46: error: cannot find symbol
     BugsnagReactNative.start(this);
     ^
   symbol:   variable BugsnagReactNative
   location: class MainApplication
 3 errors
 :app:compileDebugJavaWithJavac FAILED
 
 FAILURE: Build failed with an exception.
```

Some code from my MainApplication.Java: 

Line 6:
` import com.bugsnag.BugsnagReactNative;`

More:
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          BugsnagReactNative.getPackage(),
          new RNFirebasePackage(),
          new VectorIconsPackage(),
          new RNFirebaseAnalyticsPackage()
      );
    }
```

### Environment
- react-native version: react-native-cli: 2.0.1, react-native: 0.48.4, "react-native": "0.48.4",
- bugsnag-react-native version: "bugsnag-react-native": "^2.7.5",
- simulator/emulator or physical device?: physical device
- debug mode or production?: debug

**Comment by kattrali** [comment]
Thanks for the report, @nicklas669. Is `bugsnag-react-native` listed in `android/settings.gradle` in your project? There should be entries similar to the following after running `react-native link`:

```groovy
include ':bugsnag-react-native'
project(':bugsnag-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/bugsnag-react-native/android')
```

Were there any warnings during the linking process?

**Comment by nicklas669** [comment]
Hey @kattrali. Thanks for helping out!

My android/settings.gradle has the following:

```
rootProject.name = 'ReactNativeReduxLearning'
include ':bugsnag-react-native'
project(':bugsnag-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/bugsnag-react-native/android')
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

include ':app'
```

This was the result of the linking process:

E:\ReactNativeReduxLearning>react-native link
```
Scanning 723 folders for symlinks in E:\ReactNativeReduxLearning\node_modules (18ms)
rnpm-install info Linking bugsnag-react-native android dependency
rnpm-install info Android module bugsnag-react-native has been successfully linked
rnpm-install info Linking bugsnag-react-native ios dependency
rnpm-install WARN ERRGROUP Group 'Frameworks' does not exist in your Xcode project. We have created it automatically for you.
rnpm-install info iOS module bugsnag-react-native has been successfully linked
rnpm-install info Android module react-native-firebase is already linked
rnpm-install info iOS module react-native-firebase is already linked
rnpm-install info Android module react-native-vector-icons is already linked
rnpm-install info iOS module react-native-vector-icons is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project
```
I have just gone through the exact same steps on another machine with the exact same results. Thanks in advance.

**Comment by josephmhanna120** [comment]
Same happened to me I think.
You need to add "compile project(':bugsnag-react-native')" to the app's build.gradle
Don't know why it didn't work with link, it hanged and i had to cancel it.

**Comment by nicklas669** [comment]
Thanks @josephmhanna120, adding "compile project(':bugsnag-react-native')" to the app's build.gradle fixed the problem!

**Comment by kattrali** [comment]
Thanks @josephmhanna120! Maybe this is the same issue as https://github.com/facebook/react-native/issues/14307 ?

**Comment by imtmh** [comment]
After adding the `"compile project(':bugsnag-react-native')"` , I got the following error. :(

`Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/tt080/codebase/TripFlip2/android/app/build.gradle' line: 156

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':bugsnag-react-native' could not be found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.838 secs
`
@josephmhanna120
