### ISSUE TITLE
See entire redux state on crash

### ISSUE THREAD

**Issue by Waltari10** [bugsnag/bugsnag-react-native#201]
When the app crashes with and unhandled exception, is it possible to see the entire redux state at the time from Bugsnag? I know you can add it when you are manually notifying bugsnag, but what about unhandled errors/crashes?

**Comment by CptFabulouso** [comment]
Iam interested in this too. Did you solve it? 
Looking into documentation, may it be possible to use [bugsnag.notify](https://docs.bugsnag.com/platforms/react-native/#sending-diagnostic-data)? Create some component connected to store, that would be rendered in root, something like this

Some Root Component
```
render(){
	return(
		<Provider store = {store}>
			<View>
				<NavigationRouter />
				<NotifyHelper />
			</View>
		</Provider>
	)
}
```

NotifyHelper Component
```
const NotifyHelper = (props) => {
	
	bugsnag.notify(error, function(report) {
	  report.metadata = {this.props.reduxState}
	});

	return null
}

const mapStateToProps = state => ({reduxState: state})

export default connect(mapStateToProps)(NotifyHelper)
```

So in theory in case of crash, bugsnag.notify will be called and add the state tree to metadata. Could this work? Iam not sure, it the bugsnag.notify can be called in render function and if yes, what it does to performance etc.

**Comment by Damnum** [comment]
I don't think that solution will work, because you have to give in `error` to attach the callback (in your example, `error` seems to be undefined). I'm also interested in this.

**Comment by rtman** [comment]
@kattrali can you comment on how this could work?

I would also like to report my redux state for crashes.

**Comment by VolkRiot** [comment]
Can't you just overwrite/extend the Bugsnag.notify() method and then import in your store and call store.getState(), then pass through the error and a stringified version of your store state to original Bugsnag.notify method.

**Comment by EyMaddis** [comment]
This can be achieved globally via the configuration object:

```js

import { Client, Configuration } from 'bugsnag-react-native'

const configuration = new Configuration()

configuration.registerBeforeSendCallback(report => {
  report.metadata = {
    ...(report.metaData || {}),
   reduxState: store.getState()
  }
  if (__DEV__) {
    console.warn('bugsnag report suppressed', report)
    return false
  }
})

const client = new Client(configuration)

```

**Comment by johnkiely1** [comment]
@Waltari10 @CptFabulouso 

Did the approach suggested by @EyMaddis work for you?
Closing this for now as there is a solution posted but happy to reopen as necessary.
