### ISSUE TITLE
Unrecognized selector sent to instance while invoking BugsnagReactNative

### ISSUE THREAD

**Issue by sospedra** [bugsnag/bugsnag-react-native#204]
I constantly have this kind of errors in production only:

`Unrecognized selector sent to instance XXX was thrown while invoking startWithOptions on target BugsnagReactNative`

I do not know how to reproduce it.
The severity is "error".
It's funny because is crashing the crashes detector 🤷‍♀️ 

### Steps to reproduce

1. Randomly on production builds

### Expected behavior

To not crash

### Environment

- react-native version: multiples form 0.40 to 0.50
- bugsnag-react-native version: 2.3.1
- react-native-code-push version (if any): 5.2.0-beta (previous to appcenter also)
- iOS/Android version(s): wide range
- debug mode or production?: production

### Additional information

<details>
  <summary>Stacktrace</summary>

```
RCTFatalException: Exception '-[__NSCFString updateAutomaticBreadcrumbDetectionSettings]: unrecognized selector sent to instance 0x100c9f3f0' was thrown while invoking startWithOptions on target BugsnagReactNative with params (
        {
        appVersion = "13.0.0";
        codeBundleId = "13.0.0";
        endpoint = "https://notify.bugsnag.com";
        notifyReleaseStages =         (
            production
        );
        releaseStage = production;
        version = "2.3.2";
    }
) Exception '-[__NSCFString updateAutomaticBreadcrumbDetectionSettings]: unre... 
    Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
    /usr/lib/libobjc.A.dylib _objc_exception_throw
    Frameworks/CoreFoundation.framework/CoreFoundation +[NSException raise:format:]
    /Users/carloscuesta/Developer/mobile-apps/node_modules/react-native/React/Base/RCTAssert.m:134:7 RCTFatal
    /Users/carloscuesta/Developer/mobile-apps/node_modules/react-native/React/CxxModule/RCTNativeModule.mm:108:5 invokeInner
    /Users/carloscuesta/Developer/mobile-apps/node_modules/react-native/React/CxxModule/RCTNativeModule.mm:68:5 operator()
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_queue_serial_drain$VARIANT$mp
    /usr/lib/system/libdispatch.dylib __dispatch_queue_invoke$VARIANT$mp
    /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain_deferred_wlh$VARIANT$mp
    /usr/lib/system/libdispatch.dylib __dispatch_workloop_worker_thread$VARIANT$mp
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
    /usr/lib/system/libsystem_pthread.dylib _start_wqthread
```
</details>

**Comment by fractalwrench** [comment]
Thanks for the detailed report @sospedra - is your `bugsnag-react-native` version locked to 2.3.1? We currently recommend [locking the library](https://docs.bugsnag.com/platforms/react-native/#installation-with-code-push) to the latest patch version, as otherwise this can lead to crashes due to the JavaScript layer not being in sync with the native layer.

**Comment by sospedra** [comment]
We're using 2.3.2
Locking 2.3.1 will fix this issue? 🤔

**Comment by sospedra** [comment]
?

**Comment by fractalwrench** [comment]
@sospedra locking the version to 2.3.1 (or whichever version you are currently using) should prevent the code from the JavaScript layer getting out of sync with code in the native layer, which can lead to these types of crashes. If you still continue to observe this issue, please let us know and we'll reopen + investigate.
