### ISSUE TITLE
Jest with bugsnag

### ISSUE THREAD

**Issue by Waltari10** [bugsnag/bugsnag-react-native#205]
When I try to run a simple snapshot test, I get this error:

> Test suite failed to run
>     Bugsnag: No native client found. Is BugsnagReactNative installed in your native code project?

My snapshot test it as follows:
```
import Avatar from '../elements/Avatar'
import React from 'react'
import renderer from 'react-test-renderer'

it('should render different Avatar sizes correctly', () => {
  const tree = renderer
  .create(<Avatar />)
  .toJSON()
  expect(tree).toMatchSnapshot()
})

```

What is causing this error? How can I fix it?

**Comment by kattrali** [comment]
Native modules aren't loaded during jest tests, since they are only testing the JavaScript layer. To work around this, you can [mock the native bugsnag module](https://github.com/bugsnag/bugsnag-react-native/blob/master/src/__tests__/Bugsnag.test.js#L14-L16).

**Comment by Waltari10** [comment]
I tried adding the lines
```
  jest.mock('react-native', () => ({
    NativeModules: { BugsnagReactNative: null }
  }), { virtual: true })
```

But this results in the error:     Bugsnag: No native client found. Is BugsnagReactNative installed in your native code project?

**Comment by taranda** [comment]
I am running into the same problem.  Is there any resolution on this?
