### ISSUE TITLE
Changing the versionCode?

### ISSUE THREAD

**Issue by larryranches** [bugsnag/bugsnag-react-native#213]
Is there any way to change the version code via react-native javascript side? 

If not, I think this would be a great feature request. A perfect use case is that when integrating with a CI system like circleci, travis, etc. we can set the versionCode via the CI build number. Looking at the docs this can be set on the low level xcode or android. Right now it automatically gets set to whatever the low level version code is. Would be great if the  versionCode could be set on the higher level javascript side and changed dynamically in a variable in a .env file via CI.

**Comment by kattrali** [comment]
Thanks for the report, @larryranches. Unfortunately the versionCode property cannot be set at runtime, as its "baked in" when the native components are compiled. Perhaps you could change it during the CI build phase by being clever with environment variables and sed? Something like:

```
sed -i '' "s/versionCode .*/versionCode $TRAVIS_BUILD_NUMBER/" android/app/build.gradle
```

I tried it out and it seemed to work.

**Comment by larryranches** [comment]
@kattrali Thank you for your reply! Is your above solution for xcode or android?
