### ISSUE TITLE
Android unnecessary specific react-native version dependency in build.gradle

### ISSUE THREAD

**Issue by orenklein** [bugsnag/bugsnag-react-native#219]
In the android build.gradle, react-native dependency is set to a specific version - 0.20.1 (As seen at https://github.com/bugsnag/bugsnag-react-native/blob/master/android/build.gradle#L17)

Even though it is not causing any issue compiling and running the application, it is causing unnecessary downloads of the react-native 0.20.1 and all its dependencies. 

I'd say that the best practice is to set it to `+` as following:
`compile 'com.facebook.react:react-native:+'`

Was there any specific reason for that change?

https://github.com/bugsnag/bugsnag-react-native/commit/8c73a005e3bbb9fbda60899c8a6318126069e026#diff-7ae5a9093507568eabbf35c3b0665732

**Comment by fractalwrench** [comment]
Thanks for the report @orenklein - I think changing it back would make sense here.

**Comment by fractalwrench** [comment]
Resolved in v2.9.2
