### ISSUE TITLE
The module `./NativeSerializer` could not be found

### ISSUE THREAD

**Issue by justinmakaila** [bugsnag/bugsnag-react-native#226]
### Description
Run the app

### Issue
"The module `./NativeSerializer` could not be found from `/path/to/project/node_modules/bugsnag-react-native/lib/Bugsnag.js` Indeed, none of these files exist: ..."

### Environment
React Native

Library versions:

```shell
npm ls react-native bugsnag-react-native react-native-code-push
project@1.3.0 /path/to/project
├── bugsnag-react-native@2.9.2
└── react-native@0.52.3
```

- cocoapods version (if any) (`pod -v`):
- iOS/Android version(s):
- simulator/emulator or physical device?: all
- debug mode or production?: debug for sure, can't even test production

- [x] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [x] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example Repo

- [ ] Create a minimal repository that can reproduce the issue after running
  `yarn install` and `react-native run-ios`/`react-native run-android`
- [ ] Link to it here:

### Example code snippet

```js
import { Client, Configuration } from 'bugsnag-react-native';

// (Insert code sample to reproduce the problem)
```

```

```

**Comment by drumnation** [comment]
I'm fighting through this one as well.  I got this after updating React-Native and the bugsnag npm.  I've tried disintegrating my pods and reinstalling, but no luck.

![image](https://user-images.githubusercontent.com/18486434/37489880-70b9dc2c-286f-11e8-86a6-c5eda7e95d16.png)

I checked the ./node_modules/bugsnag-react-native/lib folder with Bugsnag.js and if I'm reading it correct it points to ./NativeSerializer which I can't find in the lib folder. This is where my error says it's looking for that folder/index file.

**Comment by justinmakaila** [comment]
^^^^^ THAT 100%. There seems to be a reference to the file, but no actual file... it's as if TS is looking right over it before publish...

**Comment by drumnation** [comment]
It likely has something to do with the latest Bugsnatch update.

> * Refactor(typedMap): Extract and rename typedMap function into NativeSerializer module [#225](https://github.com/bugsnag/bugsnag-react-native/pull/225) [Ben Gourley](https://github.com/bengourley)

**Comment by justinmakaila** [comment]
@drumnation I'm not super familiar with typescript, otherwise i'd take a stab, but I'm seeing this in the `package.json` and it's probably related:
```
...
"prepublish": "mkdir -p lib && babel src/Bugsnag.js -s -o lib/Bugsnag.js",
...
```

@bengourley, any ideas?

**Comment by drumnation** [comment]
I'm currently seeing if I can make this work by rolling back to 2.9.1 for now assuming they'll patch this soon.

**Comment by justinmakaila** [comment]
@drumnation LMK, I tried that and was still having issues, figured it would be better to try to fix it rather than going back ANOTHER version ;)

**Comment by drumnation** [comment]
It looks like the folder is just not there.

On line 4 of Bugsnag.js

>import serializeForNativeLayer from './NativeSerializer'

But there is no ./NativeSerializer folder in /lib

If it is the case that the files are missing, then rolling back until they are added seems like the easiest thing to do.

Rolling back to 2.9.1 didn't work. Same error.  Trying 2.9.0 now to see what happens.

**Comment by CodyBrouwers** [comment]
Rolling back to 2.9.1 worked for me for the time being.

**Comment by drumnation** [comment]
That did it.  I can't remember if I remembered to disintegrate my pods after I went back to 2.9.1 and had the same error...

```
1. npm install --save bugsnag-react-native@2.9.0

2. cd ios && 
sudo gem install cocoapods-deintegrate && 
sudo gem install cocoapods-clean && 
pod deintegrate && 
pod clean && 
rm -f Podfile.lock && 
pod install && 
pod update
```
