### ISSUE TITLE
onUncaughtException

### ISSUE THREAD

**Issue by gaultierq** [bugsnag/bugsnag-react-native#229]
### Description
I would like to clear my app cache on uncaught exceptions. Is there a specific way to accomplish that or caveats to avoid ?

**Comment by fractalwrench** [comment]
@gaultierq you would want to set a global error handler which calls the previous handler, similar to what [we've done here](https://github.com/bugsnag/bugsnag-react-native/blob/master/src/Bugsnag.js#L43). Within your error handler, you could perform whatever logic you need such as clearing the app cache.

The key things to be wary of are that Bugsnag is initialised, and that the previousHandler is called after your custom logic is complete. It would also be worth being very careful about doing anything that could potentially cause a crash in your crash handler - for example ensuring that any errors triggered when deleting the app cache are handled.

**Comment by gaultierq** [comment]
clear. thanks
