### ISSUE TITLE
metadata not appearing in events

### ISSUE THREAD

**Issue by peacechen** [bugsnag/bugsnag-react-native#231]
### Description
Metadata attached to a report through `registerBeforeSendCallback` doesn't appear in event logs.

### Issue

The metadata doesn't appear in any of the event tabs (stacktrace, threads, breadcrumb, app, device, user).  There's an "add tab" tab which links to documentation.  That makes it seem like the metadata should appear as a new tab.  Am I looking in the right place?

I've also tried using `beforeSendCallbacks` to modify the metadata with no success either.

### Environment

Library versions:
```shell
bugsnag-react-native@2.9.3
react-native-code-push@5.3.2
react-native@0.53.3
```

- cocoapods version (if any) (`pod -v`):
- iOS/Android version(s): Android 6.0
- simulator/emulator or physical device?: Simulator
- debug mode or production?:  Production

- [x] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class? Yes

### Example code snippet

I can confirm that setting `codeBundleId` passes the value along to the app tab.

```js
import { Client, Configuration } from 'bugsnag-react-native';

let appVersion = 'testCodeBundleId';

const config = new Configuration();
config.codeBundleId = appVersion;
const bugsnag = new Client(config);
bugsnag.registerBeforeSendCallback((report, error) => {
	report.metadata = {
		...report.metadata,
		extra: {
			UUID: DeviceInfo.getUniqueID(),
			reactNativeVersion: require('react-native/package.json').version,
			appVersion
		}
	}
});
```

**Comment by peacechen** [comment]
Yesterday the custom metadata wasn't appearing, but today it is.  Did something change on the back end?

**Comment by Cawllec** [comment]
Hi @peacechen.  We've had a look into this and it appears that the issue was with the documentation.  While the docs say to call `registerBeforeSendCallback` on the `Client` object, it needed to be called on the `Configuration` object.

By any chance have you made this change anywhere?

**Comment by peacechen** [comment]
Yes I did change it after seeing another example.  Thanks for updating the documentation.

**Comment by Cawllec** [comment]
Thanks for the info, I'll take a look through and make sure it's correct
