### ISSUE TITLE
[Android]Cannot find com.bugsnag.android.Client

### ISSUE THREAD

**Issue by dhaibo** [bugsnag/bugsnag-react-native#235]
### Description
I tried running my app, sync and build it, but it failes on
/android/demo/CrashDemo/android/app/src/main/java/com/crashdemo/MainApplication.java:45: 
exception: Inaccessible Client BugsnagReactNative.start(this);
  Can not find com.bugsnag.android.Client

### Steps to reproduce
* Install bugsnag from npm
* react-native link
* specify api key in code as given in docs
* build via react-native run android

### Versions
* compileSdkVersion 27
* buildToolsVersion "27.0.3"
* "bugsnag-react-native": "^2.9.3"
* "react-native": "0.55.3"

Tks!

**Comment by fractalwrench** [comment]
Thanks for the report @dhaibo - have you specified the [Google Maven repository](https://docs.bugsnag.com/platforms/react-native/#basic-configuration) in your build.gradle file?

If that doesn't resolve the issue, it would be helpful to see the relevant parts of your build.gradle files, and to see whether anything differs from [our example project](https://github.com/bugsnag/bugsnag-react-native/blob/master/examples/plain/). Specifically we'd be interested in the contents of any `dependencies` and `repositories` closures.

**Comment by fractalwrench** [comment]
@dhaibo are you still affected by this issue?

**Comment by kattrali** [comment]
Closing as inactive, but feel free to reopen @dhaibo if the issue recurs.
