### ISSUE TITLE
Init bugsnag on native, but set configurations later on by javascript

### ISSUE THREAD

**Issue by SudoPlz** [bugsnag/bugsnag-react-native#236]
Hey there,

please correct me if I'm mistaken, but right now if we instantiate `BugsnagReactNative` on native (be it on iOS or Android), it creates it's own `BugsnagConfiguration` and it uses it from that point on.

The only way to set it's `BugsnagConfiguration` is to instantiate it in javascript with `new Client(bugsnagConfig)`

There's currently no way to instantiate Bugsnag on the native side (just to make sure we catch those nasty launch time exceptions before react-native initiates) AND if the app doesn't crash, configure bugsnag on javascript.

Would it be too much to ask from you to add that functionality?

Thank you

**Comment by kattrali** [comment]
Hi @SudoPlz!

> please correct me if I'm mistaken, but right now if we instantiate `BugsnagReactNative` on native (be it on iOS or Android), it creates it's own `BugsnagConfiguration` and it uses it from that point on.

Correct. Native configurations are created at that point and any subsequent crashes are delivered.

> The only way to set it's `BugsnagConfiguration` is to instantiate it in javascript with `new Client(bugsnagConfig)`
>
> There's currently no way to instantiate Bugsnag on the native side (just to make sure we catch those nasty launch time exceptions before react-native initiates) AND if the app doesn't crash, configure bugsnag on javascript.

When creating a new client at the JS layer, with `new Client(bugsnagConfig)`, `bugsnagConfig` is serialized and sent to the native layer to update the native options as well. For example, you can configure `releaseStage` or add a `codeBundleId` (for CodePush), and it will be set with any native or JS crashes.

For example, on iOS, `new Client()` calls `[BugsnagReactNative startWithOptions:]` with the serialized `Configuration` object, which is [used to update the native options](https://github.com/bugsnag/bugsnag-react-native/blob/master/cocoa/BugsnagReactNative.m#L211-L223). ([Here is the equivalent code on Android](https://github.com/bugsnag/bugsnag-react-native/blob/master/android/src/main/java/com/bugsnag/BugsnagReactNative.java#L206-L271))

Does that answer your questions?

**Comment by nabati** [comment]
> When creating a new client at the JS layer, with new Client(bugsnagConfig), bugsnagConfig is serialized and sent to the native layer to update the native options as well. For example, you can configure releaseStage or add a codeBundleId (for CodePush), and it will be set with any native or JS crashes.

This should be better documented, especially for a paid service. Both the Codepush example and the official bugsnag docs on this area are really lacking. It's not really helpful to show that you can statically set the codeBundleId since that is basically never what you want to do as the bundle id comes from the Codepush server.
