### ISSUE TITLE
Support for Error class in NativeSerializer (feature request)

### ISSUE THREAD

**Issue by daisy1754** [bugsnag/bugsnag-react-native#239]
### Description
Consider bugsnag code like below that tries to leverage metadata to track details of error.

```:JavaScript
const err = new Error('this is cause');
const params = { foo: 1 };
bugsnag.notify(new Error('This is an example'), (report) => {
  report.metadata.account = { cause: err, params };
});
```

It will create meatadata like:
```
{
  cause: {},
  params: { foo: 1 }
}
```

Note cause is logged as empty object.

**Describe the solution you'd like**
Implement handling for Error type within https://github.com/bugsnag/bugsnag-react-native/blob/master/src/NativeSerializer.js so it'll log relevant info (eg., error message)

**Comment by bengourley** [comment]
Hey @daisy1754, thanks for raising this. I've confirmed that this is an issue and have scheduled some time for us to work on adding support for `Error` objects in the native serializer.
