### ISSUE TITLE
Adding bugsnag to package.json causes yarn to exceed call stack

### ISSUE THREAD

**Issue by bjorncooley** [bugsnag/bugsnag-react-native#243]
Our steps to reproduce:
* Add `"bugsnag-react-native": "2.9.x"` to dependencies in package.json
* Run `yarn`
* Outputs: `[fix-libraries]: Error! RangeError: Maximum call stack size exceeded`

Full output:
```
tr_client ((HEAD detached at 634b461)) > yarn
yarn install v1.5.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > apollo-link-rest@0.2.4" has incorrect peer dependency "graphql@0.11.7 || ^0.12.3".
warning " > react-native@0.55.4" has incorrect peer dependency "react@16.3.1".
warning " > reactxp@1.2.0" has incorrect peer dependency "react@16.2.0".
warning " > reactxp@1.2.0" has incorrect peer dependency "react-dom@16.2.0".
warning " > reactxp@1.2.0" has incorrect peer dependency "react-native@^0.53.3".
warning " > reactxp@1.2.0" has unmet peer dependency "react-native-windows@^0.53.0".
warning " > react-addons-test-utils@15.6.2" has incorrect peer dependency "react-dom@^15.4.2".
[5/5] 📃  Building fresh packages...
success Saved lockfile.
$ ./scripts/postinstall.sh
yarn run v1.5.1
$ yarn run react-native-schemes-manager fix-libraries
$ /Users/bjorncooley/projects/taskrabbit/tr_client/node_modules/.bin/react-native-schemes-manager fix-libraries
 ✔ [fix-libraries]: Debug -> Local_Debug created in node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.xcodeproj
 ✔ [fix-libraries]: Debug -> Staging_Debug created in node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.xcodeproj
 ✔ [fix-libraries]: Debug -> Test_Debug created in node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.xcodeproj
 ✔ [fix-libraries]: Release -> Staging_Release created in node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.xcodeproj
 ✔ [fix-libraries]: Release -> Production_Release created in node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.xcodeproj
⃠ [fix-libraries]: Error! RangeError: Maximum call stack size exceeded
```

**Comment by fractalwrench** [comment]
Thanks for the report @bjorncooley - I tried running `yarn` on our `examples/plain` project, and wasn't able to reproduce the behaviour. Would you be able to share the specific dependency versions you're using within your `package.json`? Perhaps there's some incompatibility being triggered somewhere.

I also noticed there are a couple of [similar issues](https://github.com/blargity/react-native-schemes-manager/issues/32) distributed across various GitHub repos, which may be of interest.

**Comment by kattrali** [comment]
Thanks for the update, @bjorncooley. I have a couple of follow-ups.

1. This seems to have more to do with `react-native-schemes-manager` than `yarn`. What is the goal of adding new schemes to the library?
2. What is `-rn-link-preventer`?

**Comment by bjorncooley** [comment]
Hi @kattrali, answers to your questions:
1. Having multiple schemes allows us to build for different environments without manually changing settings before each build. React Native doesn't handle this very well out of the box. `react-native-schemes-manager` fixes this by adding build configurations for each scheme to dependency libraries. 
2. `-rn-link-preventer` is a script we use to run `yarn safelink` instead of `react-native link`

**Comment by bjorncooley** [comment]
Error went away after upgrading to cocoapods, closing
