### ISSUE TITLE
Allow Bugsnag's breadcrumb logger to be turned off (Android)

### ISSUE THREAD

**Issue by cpetzel** [bugsnag/bugsnag-react-native#245]
### Description
Superfluous logging output with breadcrumbs.

### Issue

The Bugsnag SDK outputs the breadcrumbs to Logcat before it saves the breadcrumb. This is flooding our console (and other log capturing SDK's ) with a ton of erroneous log statements. 

https://github.com/bugsnag/bugsnag-react-native/blob/master/android/src/main/java/com/bugsnag/BugsnagReactNative.java#L92

You should expose an API to disable this logger.

### Environment

Library versions: react native bugsnag v 2.9.3

**Comment by kattrali** [comment]
Thanks for the report, @cpetzel. At most that should be a debug log instead of info.

**Comment by cpetzel** [comment]
Thank you for the quick response  :)
