### ISSUE TITLE
Documentation fails to mention calling `pod install` after `react-native link`

### ISSUE THREAD

**Issue by michaeleisel** [bugsnag/bugsnag-react-native#247]
### Description
There are many people that have commented in #215 saying that they're unable to build the iOS app because a header can't be found. It appears that `react-native link` adds bugsnag to the Podfile but doesn't run `pod install`. It would make sense for the docs to tell people that they need to run `pod install` after `react-native link`. I would post this in that issue, #215, except that no one from bugsnag support seems to be commenting there anymore.

### Issue
Documentation fails to mention calling `pod install` after `react-native link`

### Environment
OS X

**Comment by kattrali** [comment]
Thanks for the report @michaeleisel. I've added a note to the documentation to specify that if you are using CocoaPods to configure your dependencies, then you should run `pod install` after `react-native link`. It should be live in a few minutes.
