### ISSUE TITLE
Bugsnag does not report errors that are not of type `Error`

### ISSUE THREAD

**Issue by cpetzel** [bugsnag/bugsnag-react-native#249]
### Description
Bugsnag's error handler does not report errors that are not of type `Error`. This is problematic for existing codebases that are throwing `String`s or `Object`s. 

### Issue
Codebase is throwing objects and strings that are not making it up to the bugsnag dashboard

https://github.com/bugsnag/bugsnag-react-native/blob/master/src/Bugsnag.js#L84
does the type check. 

Ideally, the SDK can handle any object type... 
Perhaps do something like this? 

```
 notify = async (error, beforeSendCallback, blocking, postSendCallback, _handledState) => {
    if(typeof error !== 'Error') error = new Error(error);
    /*if (!(error instanceof Error)) {
      console.warn('Bugsnag could not notify: error must be of type Error')
      if (postSendCallback) { postSendCallback(false) }
      return
    }*/
}
    if(typeof msg !== 'object') msg = new Error(msg);
    bugsnag && bugsnag.notify(msg);

```
### Environment

Library versions:

```shell
├─ bugsnag-react-native@2.9.4
├─ react-native-code-push@5.3.4
└─ react-native@0.55.4

```

- cocoapods version (if any) (`pod -v`):
- iOS/Android version(s):
- simulator/emulator or physical device?:
- debug mode or production?:

- [x] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [x] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example code snippet

```js
import { Client, Configuration } from 'bugsnag-react-native';

throw "String Error"
```

```

```
</details>

**Comment by fractalwrench** [comment]
Thanks for the report @cpetzel - I believe this ticket is similar to #131, so I'm closing it for now.
