### ISSUE TITLE
BugsnagReactNative.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by bpolonia** [bugsnag/bugsnag-react-native#250]
### Description
I followed native installation instructions for both iOS and Android. Works fine for iOS, but when building for Android via Android Studio I get the compile error below.

`.../BugsnagReactNative.java: uses unchecked or unsafe operations.`

Full error output is below, under _Error messages:_

### Environment

Library versions:

```shell
warning Resolution field "core-js@2.5.2" is incompatible with requested version "core-js@^1.0.0"
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ bugsnag-react-native@2.9.5
├─ react-native-code-push@5.3.2
└─ react-native@0.52.2
```

- Android version: 7.0 
- Physical device: Samsung Galaxy S7 Edge
- Debug mode
- `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of my `MainApplication` class

**Specifying Google’s maven repository in android/build.gradle as:**
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        maven { url "https://mobile-sdk.jumio.com" }
        mavenLocal()
        jcenter()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url "https://maven.google.com"
        }
    }
}

```

**Error messages:**
Error when building from Android Studio
```
/Users/.../.../node_modules/bugsnag-react-native/android/src/main/java/com/bugsnag/BugsnagReactNative.java:
uses unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.
```

**Comment by fractalwrench** [comment]
Thanks for the report @bpolonia - just to confirm, are these messages preventing you from building your project? Have you configured [lintOptions](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.LintOptions.html#com.android.build.gradle.internal.dsl.LintOptions:checkAllWarnings) to abort on warnings by any chance?

I can see that there are a few issues with the use of Java generics within the `BugsnagReactNative` file, which would cause these compiler warnings. I'll investigate further whether it makes to address or suppress these issues.

**Comment by fractalwrench** [comment]
@bpolonia sorry to hear that - I've not been able to reproduce any build errors in our [example project](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/plain), although I can see the previously mentioned compiler warnings when opening the file in an IDE.

Does your app/build.gradle differ from the example project at all, particularly anything surrounding lint/static analysis tools? Are you using the latest version of bugsnag-react-native? If you build from the command line, you should be able to pass `--stacktrace` as a flag - which may give us some more information to help us debug this.

**Comment by bpolonia** [comment]
@fractalwrench This is what our `app/build.gradle` looks like


```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:3.0.1"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked"
        }
    }
    repositories {
        maven { url "https://jitpack.io" }
        maven { url "https://mobile-sdk.jumio.com" }
        mavenLocal()
        jcenter()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com'
        }
    }
}

ext {
    supportLibVersion = "27.+"
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "27.0.2"
            }
        }
    }
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == "com.android.support"
                    && !details.requested.name.contains("multidex") ) {
                details.useVersion "27.0.2"
            }
        }
    }
}

apply from: "./versions.gradle"

```

I just added the lines with `-Xlint: unchecked` under `allprojects {...` to see what additional info we could get. I now get the following compiler errors/warnings from bugsnag:

```
<project-root>/android |  
../node_modules/bugsnag-react-native/android/src/main/java |  
../../../../../../../../node_modules/bugsnag-react-native/android/src/main/java/com/bugsnag/BugsnagReactNative.java |  
[unchecked] unchecked call to put(K,V) as a member of the raw type Map where K,V are type-variables: K extends Object declared in interface Map V extends Object declared in interface Map |  
[unchecked] unchecked call to put(K,V) as a member of the raw type Map where K,V are type-variables: K extends Object declared in interface Map V extends Object declared in interface Map |  
[unchecked] unchecked conversion required: Map found:    Map |  
[unchecked] unchecked call to put(K,V) as a member of the raw type Map where K,V are type-variables: K extends Object declared in interface Map V extends Object declared in interface Map |  
[unchecked] unchecked call to put(K,V) as a member of the raw type Map where K,V are type-variables: K extends Object declared in interface Map V extends Object declared in interface Map |  
[unchecked] unchecked cast required: Map found:    Object |
```

We build for Android from Android Studio intead of the command line. This is the output I could get. If there is any other output that would be useful that is accessible from building in Android Studio please let me know. I did a `grep` in the Logcat but didn't find anything with `bugsnag`.

**Comment by bpolonia** [comment]
@fractalwrench Any ideas about this?

**Comment by fractalwrench** [comment]
@bpolonia it sounds like there is a compiler flag within your project that is causing the build to error in this way, as I believe the default behaviour is for unchecked casts to warn. I was able to reproduce a build failure by adding the following flags to our example project:

```
options.compilerArgs << "-Xlint:all" << "-Werror"
```

We plan on addressing the underlying warnings, but in the meantime it may be worth reviewing what arguments are being passed to the compiler in your project. The output for `./gradlew build --info` should contain "error: warnings found and -Werror specified" if this is the case.
