### ISSUE TITLE
What are the options for setting and modifying metadata at any time?

### ISSUE THREAD

**Issue by rtman** [bugsnag/bugsnag-react-native#252]
Hey,

So I'd like to attach the contents of a shopping cart object to my bugsnag crash reports. This cart object is loaded from async storage into my redux state just after opening the app, and is later modified during use of the app. So I would like to add the cart to metadata after it is retrieved from storage, then everytime it is modified update the metadata.

Am I correct in assuming that the usage of the code below is only 1 time at the beginning of the app?

```
const config = new Configuration();
config.registerBeforeSendCallback((report, error) => {
  // add your custom metadata here
 report.metadata = {
    ...report.metadata, // merge existing metadata that could have been added by other callbacks
    extra: {"cart": this.state.cart}
  }
});
const bugsnag = new Client(config);
```
It seems that something like `bugsnag.setUser()` would be easier for something like this, but there aren't other options that are similar (that I know of)

What are my options here?

**Comment by fractalwrench** [comment]
@rtman those assumptions look correct. `config.registerBeforeSendCallback` should only need to be specified once during app initialisation, and will then be invoked for each error reported via Bugsnag. In your example, I believe it'd be possible to write your own code to update `this.state.cart` when necessary, and the attached metadata for each report should show the updated value.

There are some docs which go into more detail on how this works, [here](https://docs.bugsnag.com/platforms/react-native/customizing-error-reports/#adding-custom-diagnostics), and explain some callback options if you only want to modify one specific error report.

Hopefully that should resolve your issue - please let us know if that's not the case and I'll reopen this ticket.

**Comment by rtman** [comment]
@fractalwrench 

I read through that docs page already and came a way slightly confused.

The `registerBeforeSendCallback` is a function that runs before an error report is generated when a crash is detected right? So that means if `this.state.cart` is being modified it will have the current contents of that variable and not what was set at the beginning of the app when the code block (below) was set?

```
const config = new Configuration();
config.registerBeforeSendCallback((report, error) => {
  // add your custom metadata here
 report.metadata = {
    ...report.metadata, // merge existing metadata that could have been added by other callbacks
    extra: {"cart": this.state.cart}
  }
});
const bugsnag = new Client(config);
```

Another thing to keep in mind is that this.state.cart is a redux state variable, so it is not necessarily available on every screen in the app. Does this matter? I'm thinking of situations where a crash happens on a screen without access to this.state.cart, will this cause problems?

**Comment by snmaynard** [comment]
Yes the callback is run when an error is generated, so it will take the values at the time the function is run, rather than when it was set. If the redux state is not set on certain screens you can either not set the callback on those screens, or defensively program against it not being set in the callback as you see fit.

**Comment by rtman** [comment]
great thanks @snmaynard

**Comment by rtman** [comment]
I'm still having issues with this, can you guys help me with code examples?

Here is what I'm trying:

```
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux'
import { ActionCreators } from '../Actions'
import { Client, Configuration } from 'bugsnag-react-native';
 
const config = new Configuration();
config.registerBeforeSendCallback((report, error) => {
  // add your custom metadata here
  if(this.props && this.props.cart){
    report.metadata = {
      ...report.metadata, // merge existing metadata that could have been added by other callbacks
      extra: {"cart": this.props.cart}
    }    
  }
})
const bugsnag = new Client(config);

export class ShoppingCartScreen extends React.Component {
  constructor(props){
    super(props)
  }
  componentDidMount(){
     bugsnag.notify(new Error("Test Cart error"));
  }
  render(){
  ...
  }
}

//redux

function mapDispatchToProps(dispatch) {
  return bindActionCreators(ActionCreators, dispatch);
}

function mapStateToProps(state) {
  return {
    cart: state.cart,
    sectionedCart: state.sectionedCart
  };
}

export default connect(() => mapStateToProps, mapDispatchToProps)(ShoppingCartScreen);
```
If I have the if statement in the config callback, the test error works fine but there is no meta data. If I remove the if statement then I get `undefined is not an object (evaluating _this.props.cart)`. Am I initializing this at the wrong time? This screen definitely has access to the redux store and `this.props.cart`

**Comment by snmaynard** [comment]
What are you expecting `this` to be in the callback? If you are expecting it to be `this` outside of the callback I would recommend adding a `_this = this` or something to bind `_this` to that value.

**Comment by rtman** [comment]
@snmaynard 

> I would recommend adding a _this = this or something to bind _this to that value.

OK but can you provide a code example? I dont fully understand how this would work with the code above.

I just want bugsnag to have access to variables in my redux state. If there is a recommended way to do this please let me know. I am just beginning with bugsnag and after reading the docs I'm still confused as to how to achieve this.
