### ISSUE TITLE
Bugsnag not compatible with React Native 0.56 (Android)

### ISSUE THREAD

**Issue by taranda** [bugsnag/bugsnag-react-native#257]
### Description
Unable to run a new app on Android using React Native 0.56 and Bugsnag.

### Urgency

This issue is time sensitive because the [Google Play store will not accept new apps that do not support API 26 or higher starting on August 1, 2018](https://developer.android.com/distribute/best-practices/develop/target-sdk).  React Native 0.56 is required to support API 26.  

### Issue
After creating a new React Native app and following the Bugsnag [install instructions](https://docs.bugsnag.com/platforms/react-native/), the build fails when running `react-native run-android`.

The Android app fails to compile and therefore cannot be loaded onto a device.

### Environment

Library versions:

```shell
├─ bugsnag-react-native@2.10.0
└─ react-native@0.56.0
```

- Android version(s): not relevant.  Code never run on device
- simulator/emulator or physical device?: not relevant. Code never  ran on device.
- debug mode or production?: Debug

- [X] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example code snippet

```js
// App.js
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import { Client } from 'bugsnag-react-native';
const bugsnag = new Client();

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
```

### Error Messages

Error occurs when running `react-native run-android`:

```shell
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':bugsnag-react-native'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':bugsnag-react-native'. Minimum required is 25.0.0
```

This is error is likely because React Native updated their `targetSdkVersion` to 26 and their `buildToolsVersion` to 26.0.3.  These changes are needed to comply with the [Google's mandate](https://developer.android.com/distribute/best-practices/develop/target-sdk) that new apps must target API 26 by August 1st, 2018, or they will not be accepted by the Google Play Store.

If this issue is not fixed by then, new apps will not be able to use Bugsnag if they are to be published on Google Play.

**Comment by fractalwrench** [comment]
Thanks for the report - this is indeed addressed in #256. We'll aim to release this fix shortly.

**Comment by fractalwrench** [comment]
@taranda we're aiming to release this soon - this is currently blocked by an issue capturing unhandled JS errors in v0.56 which we're investigating internally.

**Comment by CarlosRamon** [comment]
It worked for me this way
in Android/build.gradle 
ext {
	    compileSdkVersion   = 27
	    targetSdkVersion    = 27
	    buildToolsVersion   = "27.0.3"
	    supportLibVersion   = "27.1.0"
	    googlePlayServicesVersion = "15.0.0" 
	}

react-native version 0.56,
"bugsnag-react-native": "^2.9.5",
