### ISSUE TITLE
Bugsnag not reporting on iOS/Android 

### ISSUE THREAD

**Issue by avinashwigroup** [bugsnag/bugsnag-react-native#261]
### Description
I am a regular bugsnag consumer and for every project that I create, I install bugsnag.  However, I noted that with this version [ "bugsnag-react-native": "^2.10.1" ] I do not receive the notifications anymore.  This happens for both iOS and Android.
   
### Issue
On iOS, when I run pod install after 'react-native link',  I am getting the below error: 

`error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
 `

### Environment

Library versions:

- cocoapods version (if any) (`pod -v`): 1.5.3
- iOS/Android version(s): BOTH
- simulator/emulator or physical device?: BOTH
- debug mode or production?: PRODUCTION

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
  YES
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class? 
   YES

### Example code snippet

```js
import { Client, Configuration } from 'bugsnag-react-native';
const bugsnag = new Client();
export default bugsnag
```

<details><summary>Error messages:</summary>

```
error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
```
</details>

**Comment by fractalwrench** [comment]
Thanks for the report @avinashwigroup - unfortunately I've not been able to reproduce this with a newly created example app which uses npm. [This issue](https://github.com/react-community/create-react-native-app/issues/193) suggests that this can be caused by a duplicate installation react-native within node_modules - does the issue occur after running `rm -rf node_modules && npm install`?

We'd also be interested to know whether this error only occurs after adding bugsnag. If you temporarily remove the integration, are you still able to reproduce the behaviour?

**Comment by avinashwigroup** [comment]
This is quite weird.  I deleted the node_modules folder, re-did npm install and it is working.

Can you please provide very clear explanation as to how we should set up Bugsnag for react-native ? I notice that unless I do the manual linking for Android, it will not report bugs as well as for iOS.  But the installation instruction on the dashboard doesn't specify this.

**Comment by fractalwrench** [comment]
@avinashwigroup good to hear that resolved things - I imagine there was a duplicate react-native dependency hanging around for some reason. 

Our [installation section](https://docs.bugsnag.com/platforms/react-native/#installation) of the docs are the authoritative source for setting up Bugsnag. The [basic configuration section](https://docs.bugsnag.com/platforms/react-native/#basic-configuration) also documents how to setup Bugsnag with your API key, and how to setup the native integration for Android + iOS, if you use native components.

Hopefully this resolves your issue - please let me know if not, and I'll be happy to reopen the ticket.

**Comment by fractalwrench** [comment]
@avinashwigroup native integration on iOS would involve setting the API key in your Info.plist:

```
<key>BugsnagAPIKey</key>
<string>YOUR-API-KEY-HERE</string>
```

and initialising Bugsnag in your AppDelegate:

```
#import <BugsnagReactNative/BugsnagReactNative.h>
- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
    [BugsnagReactNative start];
}
```

If you've followed the installation instructions using npm then I don't believe you would need to do anything further with the Podfile, for a typical project.

**Comment by avinashwigroup** [comment]
Maybe something went wrong on my side.  Nothing was written to the podfile.  I had to manually add it.

Thanks @fractalwrench
