### ISSUE TITLE
Client.notify requires an Error object, docs and setup do not reflect this

### ISSUE THREAD

**Issue by kennygoff** [bugsnag/bugsnag-react-native#27]
When setting up Bugsnag on a new project, I followed instructions to do a test error to make sure it's set up properly. However the project said to do `client.notify("Test Error")`, and that caused a warning and wouldn't post to Bugsnag. The `client.notify` function requires an `Error` object. My solution was to simply wrap the string in an Error with `client.notify(new Error("Test Error"))`. That worked fine.

This should probably be reflected in the projects page or docs, or `client.notify` function should accept a string as well and create a new Error object if the parameter is a string. I've attached the screenshot of what my Bugsnag project dashboard showed during setup.

Otherwise a flawless and simple setup process! 👍 

<img width="666" alt="screen shot 2016-11-17 at 12 15 27 pm" src="https://cloud.githubusercontent.com/assets/1051880/20399686/f75369f6-acbf-11e6-9d5f-0bf2af7a31b8.png">

**Comment by wordofchristian** [comment]
Thanks for this. We'll update those instructions right away.
