### ISSUE TITLE
iOS v2.10.0 causes periodic crashes upon resume

### ISSUE THREAD

**Issue by jamesreggio** [bugsnag/bugsnag-react-native#270]
**This bug has been fixed in v2.10.1, so all you need to do is upgrade.**

I'm filing this bug for SEO purposes. You've already fixed this bug, but it took me a while to figure out the source of our crashes (and that Bugsnag was at fault).

----

We've had a _lot_ of verbally-reported crashes-upon-resume due to synchronous networking code for session tracking that was introduced in Bugsnag Cocoa in the v2.10.1 build. The synchronous code leads to a Springboard Watchdog termination, which isn't actually tracked or reported by Bugsnag, so it was a tricky problem to track down.

So, if you're experiencing the following issue, you ought to upgrade.

### Issue

About 20% of the time, when resuming your iOS React Native app by either unlocking your phone or using the app switcher, the app's UI will hang for about 8 seconds and then terminate. These crashes are not reported in Bugsnag, nor in the App Store crash logs that appear in the _Organizer_ in Xcode.

### Additional Information

The only way you can see the actual crash data is to connect your phone over USB, open up the _Devices & Simulator_ window in Xcode, select your phone, click _View Device Logs_, and browse to a corresponding crash.

You'll need to download the dSYMs for your app version in the _Organizer_ first. After that, you can right-click and click _Re-Symbolicate Log_ on the suspected crash. If you're affected by this issue, you'll see something akin to the following:

```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x0000000189aa3260 semaphore_wait_trap + 8
1   libdispatch.dylib             	0x00000001899915e8 _os_semaphore_wait + 24
2   libdispatch.dylib             	0x0000000189990ca0 _dispatch_semaphore_wait_slow + 140
3   banter                        	0x0000000100195a2c -[BugsnagSessionTracker send] + 825900 (BugsnagSessionTracker.m:130)
4   banter                        	0x00000001001b2e0c -[BugsnagNotifier sessionTick:] + 945676 (BugsnagNotifier.m:413)
5   CoreFoundation                	0x000000018aa615ec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
6   CoreFoundation                	0x000000018aa60d00 _CFXRegistrationPost + 400
7   CoreFoundation                	0x000000018aa60a7c ___CFXNotificationPost_block_invoke + 60
8   CoreFoundation                	0x000000018aacf7a8 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1412
9   CoreFoundation                	0x000000018a9a494c _CFXNotificationPost + 376
10  Foundation                    	0x000000018b4b6920 -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
11  UIKit                         	0x0000000190e51f18 -[UIApplication _sendWillEnterForegroundCallbacks] + 232
12  UIKit                         	0x0000000190e8d8c8 -[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] + 1684
13  UIKit                         	0x0000000190e8cfc0 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 448
14  UIKit                         	0x0000000190e78570 __70-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 152
15  UIKit                         	0x0000000190e781ec -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 892
16  UIKit                         	0x00000001911b26e4 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 464
17  FrontBoardServices            	0x000000018c64222c __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.376 + 208
18  FrontBoardServices            	0x000000018c66f884 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
19  FrontBoardServices            	0x000000018c66f6f0 -[FBSSerialQueue _performNext] + 176
20  FrontBoardServices            	0x000000018c66faa0 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
21  CoreFoundation                	0x000000018aa75424 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
22  CoreFoundation                	0x000000018aa74d94 __CFRunLoopDoSources0 + 540
23  CoreFoundation                	0x000000018aa729a0 __CFRunLoopRun + 744
24  CoreFoundation                	0x000000018a9a2d94 CFRunLoopRunSpecific + 424
25  GraphicsServices              	0x000000018c40c074 GSEventRunModal + 100
26  UIKit                         	0x0000000190c5b130 UIApplicationMain + 208
27  banter                        	0x00000001000d0c58 main + 19544 (main.m:6)
28  libdyld.dylib                 	0x00000001899b159c start + 4
```

The pertinent details are as follows:

```
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
```

The `SPRINGBOARD` `0x8badf00d` termination (pronounced _ate-bad-food_) indicates that the app was terminated due to non-responsiveness. This is typically caused by expensive, synchronous operations occurring on the main thread.

And indeed, it is the main thread (Thread 0), that crashed. If you look at the logs, you'll see the following two frames near the top:

```
3   banter                        	0x0000000100195a2c -[BugsnagSessionTracker send] + 825900 (BugsnagSessionTracker.m:130)
4   banter                        	0x00000001001b2e0c -[BugsnagNotifier sessionTick:] + 945676 (BugsnagNotifier.m:413)
...
11  UIKit                         	0x0000000190e51f18 -[UIApplication _sendWillEnterForegroundCallbacks] + 232
```

Here, you can see that the `BugsnagSessionTracker` is initiating a network request on the main thread in response to the `appWillEnterForeground` notification.

----

It's quite frustrating that my error tracker has been introducing crashing errors into my app, and even more frustrating that it's due to a new feature (session tracking) that I'm not paying for, nor using, nor even aware of.

This is, in fact, the second time Bugsnag has introduced critical crashers into my product. (The last time it happened was when you introduced console breadcrumbs, which I had to fix in #183.) I guess I'm the foolish one here.

Given that you beat me to identifying and fixing the issue this time around, I _really_ wish y'all would figure out a means of notifying customers when you ship critical bugs like this. (And I don't think that it's hyperbolic to call a newly-introduced untraceable crasher a critical bug.)

**Comment by kattrali** [comment]
You're right, @jamesreggio. This is frustrating and its more than reasonable to be upset about a third party library introducing difficult-to-find bugs in your application, let alone an error reporting library. Thank you for the detail you've put into this report.

Internally, for each of these issues, we discuss what went wrong and what proactive steps to take to avoid having it ever happen again. For this issue in particular, we are building performance test suites for our mobile platforms (and iOS in particular) to make it a test failure to occupy the main thread for more than a moment. There are also manual test steps which are required for every release, and which now include testing under low- to no-network conditions.

I'm going to evaluate how we are notifying customers about when new versions are available, and in particular critical fixes. As this release was live for a while, it merited more than a patch release and we could provide additional notification.

As you noted, the issue at hand has been resolved, so I am going to close this issue. However if there is more details which would be useful to you or you have additional feedback/suggestions for how this process could be improved, feel free to reach out at support@bugsnag.com.

**Comment by jamesreggio** [comment]
Thank you for the thoughtful reply, @kattrali.

It's encouraging to know that you have a postmortem process, and that you're taking steps to avoid shipping bugs of the same class in the future.

It's the customer notification aspect that is of greatest concern for me. It'd probably be good for your various SDKs to include version tags in their network payloads so you can correlate version usage with a given Bugsnag project/account. From there, you could send emails or display a banner in the Bugsnag Dashboard if you've detected use of a critically flawed version of the SDK.

For a faster, JavaScript-specific remediation, you could use the `npm deprecate` command to push a warning to all of the customers locked to a critically broken version. Other packages tend to use this for major security bugs, but I think it's plenty appropriate for warning about a crasher in an error-reporting library. I would've immediately noticed and upgraded had I seen such a warning.

Regardless, I appreciate your transparency and hope you'll take some steps forward with customer notification.

**Comment by kattrali** [comment]
> For a faster, JavaScript-specific remediation, you could use the `npm deprecate` command to push a warning to all of the customers locked to a critically broken version. Other packages tend to use this for major security bugs, but I think it's plenty appropriate for warning about a crasher in an error-reporting library. I would've immediately noticed and upgraded had I seen such a warning.

Ah, that's a good idea and something we can immediately add to the release process. Its currently a mixed bag when it comes to package-level notification on the various platforms we support, but npm does a good job here.
