### ISSUE TITLE
Failed to execute aapt

### ISSUE THREAD

**Issue by antonsivogrivov** [bugsnag/bugsnag-react-native#275]
### Description
Try to execute ./gradlew assembleRelease with success

### Issue
Got an error while executing ./gradlew assembleRelease:

Task :app:uploadBugsnagReleaseMapping
Mapping file not found: null

.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/06f32b88be0c59d0bd89dc4506942ab3/res/values-v24/values-v24.xml:3:5-157: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/06f32b88be0c59d0bd89dc4506942ab3/res/values-v24/values-v24.xml:4:5-135: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/06f32b88be0c59d0bd89dc4506942ab3/res/values-v26/values-v26.xml:13:5-16:13: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

Execution failed for task ':bugsnag-react-native:verifyReleaseResources'.
com.android.ide.common.process.ProcessException: Failed to execute aapt

### Environment

Library versions:

```shell
├── bugsnag-react-native@2.10.3
├── react-native@0.57.0
└── react-native-code-push@5.3.4
```

- cocoapods version (if any) (`pod -v`): not used
- simulator/emulator or physical device?: physical
- debug mode or production?: production

- [x] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

</details>

**Comment by fractalwrench** [comment]
Thanks for the report @antonsivogrivov - does this behaviour occur in a project without bugsnag-react-native integrated, and have you recently updated React Native, or any other android build dependency? I don't believe the bugsnag-react-native library relies on AppCompat and it looks like the error is due to some missing resources within that library.

**Comment by antonsivogrivov** [comment]
It was occurred after updating react-native from 0.53 to 0.57 and in 0.57 Android SDK was changed to 27

**Comment by fractalwrench** [comment]
Does the error only occur when bugsnag-react-native is integrated in your project?

**Comment by antonsivogrivov** [comment]
No, when disable imports of bugsnag I have got similar errors but with another libs :(

**Comment by Blutude** [comment]
@antonsivogrivov did you fix this?
