### ISSUE TITLE
doc: source map upload example about react native project

### ISSUE THREAD

**Issue by iwater** [bugsnag/bugsnag-react-native#28]
in docs, there is a require param minifiedUrl, how to fill this on a react native project, "main.jsbundle" or ?
can you give some example about react native project?

**Comment by duncanhewett** [comment]
Hi @iwater - there are some specific docs for React Native source maps which should help - https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#uploading-source-maps

**Comment by keshavkaul** [comment]
@duncanhewett The docs aren't helpful. It's been over 10hrs of futile efforts to upload source maps. Having react-native support should ideally have this feature built in as most of the code being executed is in Javascript and not native. Please improve the docs and the library. Thanks!

**Comment by pkantsedalov** [comment]
@keshavkaul Hi. Can you tell me please how did you do that? Tried many times but my URLs don't match.
