### ISSUE TITLE
Cannot build Android after installing bugsnag - [cannot find symbol, report.getNotifier, Task :bugsnag-react-native:compileDebugJavaWithJavac FAILED]

### ISSUE THREAD

**Issue by mshibl** [bugsnag/bugsnag-react-native#280]
### Issue
After installing bugsnag, android builds no longer work.
![bugsnag](https://user-images.githubusercontent.com/11624249/46374178-efea8500-c644-11e8-9eae-d8ca9bd9b5f2.png)

### Environment

Library versions:

```shell
├─ bugsnag-react-native@2.11.0
└─ react-native@0.55.4
```

- cocoapods version (if any) (`pod -v`):
- iOS/Android version(s): 27
- simulator/emulator or physical device?: pixel emulator
- debug mode or production?: debug

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

<details><summary>Error messages:</summary>

```
> Task :bugsnag-react-native:compileDebugJavaWithJavac FAILED
.../node_modules/bugsnag-react-native/android/src/main/java/com/bugsnag/BugsnagReactNative.java:384: error: cannot find symbol
        report.getNotifier().setName(NOTIFIER_NAME);
              ^
  symbol:   method getNotifier()
  location: variable report of type Report

.../node_modules/bugsnag-react-native/android/src/main/java/com/bugsnag/BugsnagReactNative.java:385: error: cannot find symbol
        report.getNotifier().setURL(NOTIFIER_URL);
              ^
  symbol:   method getNotifier()
  location: variable report of type Report

.../node_modules/bugsnag-react-native/android/src/main/java/com/bugsnag/BugsnagReactNative.java:386: error: cannot find symbol
        report.getNotifier().setVersion(String.format("%s (Android %s)",
              ^
  symbol:   method getNotifier()
  location: variable report of type Report
3 errors

```
</details>

**Comment by danferd** [comment]
i'm having this issue too after updated to version 2.11.0 and i'm using react-native@0.57.1

**Comment by fractalwrench** [comment]
Thanks for the report @mshibl - we're looking into it as a priority. Do you still see this behaviour after performing a clean build i.e. deleting the `.gradle/` folder in your android directory, and deleting `node_modules` then running `npm install`? We've only been able to see this intermittently so far, and suspect that it's a dependency caching issue.

Would you also be able to attach the output of `./gradlew app:dependencies`, where `app` is the name of your module, and the areas of your package-lock.json which reference "bugsnag"? This will help us see whether the correct dependencies are being used.

**Comment by efiorello** [comment]
+1

**Comment by ahilles107** [comment]
Deleting `~/.gradle/caches` and `~/.gradle/daemon` didn't helped in my case ;/ Cache was cleared and new binaries were fetched but i still have this error.

**Comment by fractalwrench** [comment]
@ahilles107 Would you also be able to attach the output of ./gradlew app:dependencies, where app is the name of your module, and the areas of your package-lock.json which reference "bugsnag"? This will help us see whether the correct dependencies are being used.

**Comment by brunoczo** [comment]
+1

**Comment by claudiofp** [comment]
+1

**Comment by alessandrofc** [comment]
Deleting ~/.gradle/caches and ~/.gradle/daemon works for me.

**Comment by efiorello** [comment]
for me too
