### ISSUE TITLE
Support bugsnag-react

### ISSUE THREAD

**Issue by brunolemos** [bugsnag/bugsnag-react-native#286]
### Description
`bugsnag.use` is not a function on native

**Describe the solution you'd like**
Support ErrorBoundary on native well, the same way it's done on the web.

**Additional context**
Related: #244

**Comment by snmaynard** [comment]
This will require a fair bit of work to unify the react-native codebase with the bugsnag-js codebase, but is something we intend to do in the future. In the mean time you can always add your own custom error boundary. Thanks for the feedback!

**Comment by johnkiely1** [comment]
As of [v7.3](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.4) the Bugsnag react native library has now become part of the [bugsnag-js](https://github.com/bugsnag/bugsnag-js) repository. ErrorBoundary specific setup instructions can be found [here](https://docs.bugsnag.com/platforms/react-native/react-native/#capturing-react-render-errors). 

An upgrade guide can be found [here](https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/UPGRADING.md) with full documentation available [here](https://docs.bugsnag.com/platforms/react-native/react-native/).
