### ISSUE TITLE
BSG_KSCrashC.h' file not found

### ISSUE THREAD

**Issue by agrass** [bugsnag/bugsnag-react-native#292]
I'm trying to install in iOS manually, but I got this error BSG_KSCrashC.h' file not found. I follow this steps:

1. npm i --save bugsnag-react-native
2. Add the project in library
3. add libBugsnagReactNative.a in linked libraries
4. add pod Bugsnag 
5. pod install

Is there something that I'm missing?

**Comment by kattrali** [comment]
Thanks for the report, @agrass - I suspect that the library may be added incorrectly. 
Does it work without steps 4 & 5 (if you remove `pod 'BugsnagReactNative'`)? 
What is the exact error message?
What versions of react-native, bugsnag-react-native, and CocoaPods are you using?

**Comment by agrass** [comment]
Thanks for the response! yes, now is working. It was a little confusing to install it manually, the project is with another project inside and I was following some instructions of the native iOS without RN. Finally worked without steps 4 and 5 and I removing libBusgsnagStatic.a from the linked libraries.
