### ISSUE TITLE
Add scripts to upload dsym and sourcemaps

### ISSUE THREAD

**Issue by pvinis** [bugsnag/bugsnag-react-native#298]
### Description
Since these demo projects are to help with getting started, it would be nice to have a couple of scripts in each of them, that upload the dsym and the sourcemaps.

**Describe the solution you'd like**

a couple of scripts that we can use to get perfect crash reports with the demo apps

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by fractalwrench** [comment]
Thanks for the feedback @pvinis - this has been implemented in #306

**Comment by pvinis** [comment]
After trying it out, I found that the iOS native crash stacktrace is still hard to read.

Other than that, everything looks and works great!

**Comment by pvinis** [comment]
<img width="871" alt="screen shot 2019-01-22 at 08 49 55" src="https://user-images.githubusercontent.com/100233/51519968-b66f9c80-1e22-11e9-9cfb-13aa41fe26b6.png">
