### ISSUE TITLE
got error if attaching custom data in bugsnap.notity

### ISSUE THREAD

**Issue by iwater** [bugsnag/bugsnag-react-native#30]
![error](https://cloud.githubusercontent.com/assets/108937/20612679/6096169c-b2f7-11e6-90e5-22bb612db7b5.png)

got error if attaching custom data in bugsnap.notity

bugsnag: latest version
platform: ios simulator
react-native: 0.38.0

**Comment by kattrali** [comment]
Thanks for the report, @iwater. Custom data should be serializable to JSON (numbers, strings, arrays, etc). Can you share the custom data used, or at least the structural layout so I can reproduce the problem?

**Comment by duncanhewett** [comment]
@iwater I reproduced this by not setting a sub object to a pair:
```
client.notify(new Error('foo'), (report) => {
    report.metadata.test = "value";
});
```

Where as this works:

```
client.notify(new Error('foo'), (report) => {
    report.metadata.test = {"key": "value"};
});
```

**Comment by iwater** [comment]
Exception '-[NSTaggedPointerString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0xa000068637465665' was thrown while invoking notify on target BugsnagReactNative with params (
        {
        apiKey = 2f1180ca5280a4ed2e250db57******;
        errorClass = TypeError;
        errorMessage = "Network request failed";
        metadata =         {
            arguments =             {
                type = map;
                value =                 {
                    body =                     {
                        type = string;
                        value = "{\"source\":{\"headers\":{\"Authorization\":\"Basic bnVsbA==\"},\"url\":\"http://fackurl/products_04/\"},\"target\":\"products_04\",\"continuous\":true}";
                    };
                    headers =                     {
                        type = map;
                        value =                         {
                            Accept =                             {
                                type = string;
                                value = "application/json";
                            };
                            Authorization =                             {
                                type = string;
                                value = "Basic YWRtaW46cGFzc3dvcmQ=";
                            };
                            "Content-Type" =                             {
                                type = string;
                                value = "application/json";
                            };
                        };
                    };
                    method =                     {
                        type = string;
                        value = POST;
                    };
                    params =                     {
                        type = map;
                        value =                         {
                        };
                    };
                };
            };
            type =             {
                type = string;
                value = fetch;
            };
        };
        severity = warning;
        stacktrace = "onerror@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:3…m=ios&dev=true&minify=false:3813:6\ncallFunctionReturnFlushedQueue@[native code]";
        user =         {
        };
    }
)

RCTFatal + 104
-[RCTBatchedBridge callNativeModule:method:params:] + 1209
__33-[RCTBatchedBridge handleBuffer:]_block_invoke.481 + 1470
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_queue_serial_drain + 236
_dispatch_queue_invoke + 1073
_dispatch_queue_override_invoke + 683
_dispatch_root_queue_drain + 720
_dispatch_worker_thread3 + 123
_pthread_wqthread + 1299
start_wqthread + 13

above is my error shown, expect some information was modified, like apiKey, url etc.
