### ISSUE TITLE
Native Stacktrace looks bad

### ISSUE THREAD

**Issue by pvinis** [bugsnag/bugsnag-react-native#300]
### Description
When a native crash happens, the stacktrace is all in one long line, and not formatted correctly.
It's not very useful, as we need to do the extra step of parsing it before we can see where the problem was.

### Issue
Native stacktrace is not detected correctly?

### Environment

Library versions:
bugsnag-react-native: 2.12.6
react: 16.6.3
react-native: 0.57.8

```shell
 % yarn list react-native bugsnag-react-native react-native-code-push
yarn list v1.12.3
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ bugsnag-react-native@2.12.6
└─ react-native@0.57.8
✨  Done in 0.56s.
```

- cocoapods version (if any) (`pod -v`): no cocoapods
- iOS/Android version(s): iOS 12
- simulator/emulator or physical device?: both
- debug mode or production?: release/production

- [X] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example Repo

- [X] Create a minimal repository that can reproduce the issue after running
  `yarn install` and `react-native run-ios`/`react-native run-android`
- [X] Link to it here: https://github.com/pvinis/BugsnagBadStack

I have all the steps I took to make the repo, as well as steps to reproduce the problem.

Thank you.

**Comment by pvinis** [comment]
here are some screenshots too
nice js:
![crash-js](https://user-images.githubusercontent.com/100233/50340959-5208a700-051d-11e9-9205-34af41bdf4c1.png)
bad native:
![crash-native](https://user-images.githubusercontent.com/100233/50340966-56cd5b00-051d-11e9-8656-bb1d843585bd.png)

**Comment by pvinis** [comment]
# UPDATE: This should be fixed on this [PR](https://github.com/facebook/react-native/pull/23691) and it will land on RN 0.60.0

**Comment by snmaynard** [comment]
@pvinis thanks for your work on that!
