### ISSUE TITLE
Don't working with native errors

### ISSUE THREAD

**Issue by corujoraphael** [bugsnag/bugsnag-react-native#308]
I've set it up as explained in the documentation and errors in javascript as undefined are displayed on the dashboard. But errors of the native part like the one presented in the Play Console are not being captured.

> java.lang.RuntimeException:
>                        at android.app.ActivityThread.handleReceiver (ActivityThread.java:3334)
>   at android.app.ActivityThread.-wrap17 (Unknown Source)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1725)
>   at android.os.Handler.dispatchMessage (Handler.java:105)
>   at android.os.Looper.loop (Looper.java:164)
>   at android.app.ActivityThread.main (ActivityThread.java:6694)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:769)
> Caused by: java.lang.ClassNotFoundException: 
>   at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:93)
>   at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
>   at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
>   at android.app.ActivityThread.handleReceiver (ActivityThread.java:3329)

What could be happening?

**Comment by fractalwrench** [comment]
Thanks for getting in touch @corujoraphael - could you write in to [support@bugsnag.com](mailto:support@bugsnag.com) with further details, if you're still encountering an issue with your integration?
