### ISSUE TITLE
Receiver 'BugsnagConfiguration' for class message is a forward declaration

### ISSUE THREAD

**Issue by adamterlson** [bugsnag/bugsnag-react-native#309]
### Description
I am attempting to use the `startWithConfiguration` method to start bugsnag, but I get an error attempting to instantiate the BugsnagConfiguration class.

My library was linked according to the [manual linking instructions](https://docs.bugsnag.com/platforms/react-native/manual-linking-guide/).

### Issue
`Receiver 'BugsnagConfiguration' for class message is a forward declaration` build error is given on the BugsnagConfiguration constructor, and `Property 'releaseStage' cannot be found in forward class object 'BugsnagConfiguration'` is given when trying to set `releaseStage` (or any other property)

Using simply `[BugsnagReactNative start]` works fine—no build errors, and it successfully logs all crashes as expected.  I am simply unable to use the custom configuration method.

### Example code snippet

```objc
#import <BugsnagReactNative/BugsnagReactNative.h>
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    BugsnagConfiguration *config = [BugsnagConfiguration new];
    config.releaseStage = @"DEV";
    [BugsnagReactNative startWithConfiguration:config];
}
```

![image](https://user-images.githubusercontent.com/2498418/51840917-ac133e00-230d-11e9-827d-98285d23e620.png)

### Repro using the example

I was able to reproduce this problem simply using the [ios cocoapods example](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/ios-cocoapods-component) project and changing the `didFinishLaunchingWithOptions` implementation with the code sample given in [the enhanced native integration config example](https://docs.bugsnag.com/platforms/react-native/enhanced-native-integration/#further-configuration).

![image](https://user-images.githubusercontent.com/2498418/51846894-cf90b580-231a-11e9-8371-e17f723af885.png)

**Comment by fractalwrench** [comment]
Thanks for the report @adamterlson - we have updated [our docs](https://docs.bugsnag.com/platforms/react-native/enhanced-native-integration/#further-configuration) to reflect that an additional import is required, i.e. `#import "BugsnagConfiguration.h"`.

**Comment by adamterlson** [comment]
@fractalwrench Adding this import to the AppDelegate doesn't work.  Does this import need to be added elsewhere?  Is a newer version of the library required?

![image](https://user-images.githubusercontent.com/2498418/52473380-ed211300-2b95-11e9-918a-fe6ff3c8b6c3.png)

**Comment by fractalwrench** [comment]
@adamterlson in a manually linked app you'll also need to update the "Header Search Paths" field in XCode, so that the project know where to find the bugsnag headers. 

Adding the following should resolve your issue: `$(inherited) $(SRCROOT)/../node_modules/bugsnag-react-native/cocoa/** `

**Comment by adamterlson** [comment]
@fractalwrench For whatever reason, that doesn't seem to work for me.

![image](https://user-images.githubusercontent.com/2498418/52490475-1907bd00-2bc5-11e9-970c-1786efbb4782.png)

**Comment by fractalwrench** [comment]
@adamterlson it looks like `**` and `recursive` are specified - if you remove the `**` then I believe it should work. For reference the header search path in the project I'm using looks like this:

<img width="905" alt="screenshot 2019-02-08 at 16 42 40" src="https://user-images.githubusercontent.com/11800640/52492176-967cfe80-2bc0-11e9-8f4a-4c080edeffd3.png">

**Comment by ebaynaud** [comment]
@fractalwrench You should also add to [Android instructions](https://docs.bugsnag.com/platforms/react-native/react-native/enhanced-native-integration/#further-configuration) the import required in MainApplication.java to get it work:

`import com.bugsnag.android.Configuration;`

And fix your snippet to reflect that API KEY is required in Configuration constructor: 

`Configuration config = new Configuration("YOUR-API-KEY-HERE");`
