### ISSUE TITLE
Can reporting handled rejected promises be disabled?

### ISSUE THREAD

**Issue by dajaffe** [bugsnag/bugsnag-react-native#311]
### Description
I read through the documentation and couldn't find if this is possible. I have a use case of polling for messages to an OAuth2 backed server. There may be times the token is no longer valid (getting a 403) back, in which case my app refreshes the token. These tokens could expire within 30 minutes, and my app polls every 30ish. This results in daily quotas being eaten up by **handled** rejected promise HTTP 403's that I don't care about. Most of my rejected promises I tend to ignore, as they're related to failed logins / authorizations which I have fallback logic for.

**Describe the solution you'd like**
A configuration option telling Bugsnag to not report handled rejected promises.

**Describe alternatives you've considered**
Nothing really feasible aside from forking Axios to treat everything as a resolved promise, but return an error indicator in the resolved promise, to avoid rejecting promises altogether.

**Comment by kattrali** [comment]
Thanks for the report, @dajaffe. *Handled* rejected promises shouldn't be reported at all. Can you provide an code example for how these promises are caught but then still reported? There is a config option for [disabling *unhandled* rejected promises](https://docs.bugsnag.com/platforms/react-native/configuration-options/#handlepromiserejections), though it sounds like something different is happening here. You can also use [callbacks](https://docs.bugsnag.com/platforms/react-native/configuration-options/#beforesendcallbacks) to ignore particular errors you don't care about by returning `false` from the function.

**Comment by dajaffe** [comment]
That's odd.. I discarded my best example to see if they stopped counting against my quota so I don't have the full stack right now, but this is where's coming from:

```
Errornode_modules\axios\lib\core\createError.js:16
Network Error
```

Which comes from the Axios library here: https://github.com/axios/axios/blob/master/lib/core/createError.js

Which in my case (I remember part of the stack) comes from Axios' XHR's handleError: 
https://github.com/axios/axios/blob/503418718f669fcc674719fd862b355605d7b41f/lib/adapters/xhr.js

```
request.onerror = function handleError() {
      // Real errors are hidden from us by the browser
      // onerror should only fire if it's a network error
      reject(createError('Network Error', config, null, request));

      // Clean up request
      request = null;
    };
```

They new off an Error if a network issue occurs (no connectivity, non-200 responses, etc.), then pass it into the consumer's promise's rejection callback, which is what had been eating up my quota. I finally got the Bugsnag source code mapping to work, and the 'new Error' line in their core/createError is what's getting highlighted.

**Comment by kattrali** [comment]
No worries! Thanks for the update.
