### ISSUE TITLE
Clarification: While linking the react-native-bugsnag which xcodeproj need to link with libraries

### ISSUE THREAD

**Issue by nihp** [bugsnag/bugsnag-react-native#312]
I have a clarification about linking the react-native-bugsnag in xcodeproj and have the following questions about this

1. After installing the package, which xcodeproj need to link with the Link binary with Libraries.(i.e) i have Bugsnag.Xcodeproj and BugsnagReactNative.Xcodeproj. 

2. How can we test it working or not after the installation. Did I need to call bugsnag.notify() in all my screens. 

3. In which file we need to set the https://docs.bugsnag.com/platforms/react-native/configuration-options/

4. Which method is preferrable for showing full stacktraces(i.e) with bitcode or without bitcode

I am new to this

**Comment by kattrali** [comment]
> 1. After installing the package, which xcodeproj need to link with the Link binary with Libraries.(i.e) i have Bugsnag.Xcodeproj and BugsnagReactNative.Xcodeproj.

You'll need to link BugsnagReactNative.xcodeproj - there's instructions for manually configuring a project [here](https://docs.bugsnag.com/platforms/react-native/manual-linking-guide/#ios-configuration)

> 2\. How can we test it working or not after the installation. Did I need to call bugsnag.notify() in all my screens.

No need, you could do something like have a button call an undefined function and check whether it was reported to Bugsnag successfully.

> 3\. In which file we need to set the https://docs.bugsnag.com/platforms/react-native/configuration-options/

I'd recommend having a dedicated file for initializing and configuring Bugsnag if you need additional options, similar to [this project](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/plain) (see [`lib/bugsnag.js` here](https://github.com/bugsnag/bugsnag-react-native/blob/master/examples/plain/app/lib/bugsnag.js) then you can configure it all in one place and import it elsewhere if you need to use `bugsnag.notify()`.

> 4\. Which method is preferrable for showing full stacktraces(i.e) with bitcode or without bitcode

Both work, its purely dependent on the needs of your project (bitcode is recommended by Apple as the default setting, for example).

**Comment by nihp** [comment]
Thanks

**Comment by nihp** [comment]
@kattrali I have a clarification, Is this work in iOS ???

**Comment by kattrali** [comment]
Yes. Can you try running one of the [example projects](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/plain) to compare if it works for you? Maybe then it might be easy to figure out what's wrong in your current project's configuration.

**Comment by nihp** [comment]
I have run the example project. I can able to see the error logs in Bugsnag. But it not showing the error log file. (i.e) If I run into errors it not showing in which file I got error.

Also If I change the file name and created an error. It not showing the changed file name.

Kindly let me know ASAP

Refer the below

**TypeErrorhttp://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:88505
TypeError: undefined is not an object (evaluating 'this.props.navigation.navigate') This error is located at: in App (at renderApplication.js:34) in RCTView (at View.js:45) in View (at AppContainer.js:98) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:33)**
