### ISSUE TITLE
 no such file or directory: '/Users/XXXXXX/Library/Developer/Xcode/DerivedData/Application/Build/Products/Debug-iphonesimulator/libBugsnagReactNative.a'

### ISSUE THREAD

**Issue by nihp** [bugsnag/bugsnag-react-native#313]
I am trying to setup the RNBugsnag, but while compiling the app I am getting an error as  "**no such file or directory**: '/Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Application/Build/Products/Debug-iphonesimulator/libBugsnagReactNative.a'

How to resolve this error

**Comment by kattrali** [comment]
Thanks for the report, @nihp. I'd recommend cleaning your project in Xcode (Command + Shift + K) and retrying the build.

**Comment by nihp** [comment]
@kattrali It not worked for me

**Comment by kattrali** [comment]
Can you check your project and see whether you have both of these libraries linked like so and share a screenshot?
<img width="1440" alt="linked libraries screen" src="https://user-images.githubusercontent.com/333454/53405063-eb858680-39ae-11e9-982a-39858ba96f77.png">

**Comment by nihp** [comment]
Yes I have added that in Link Binaries to library
![screenshot 2019-02-26 at 3 45 55 pm](https://user-images.githubusercontent.com/36992338/53405362-b17fa900-39dd-11e9-83d4-cd0fe2a041bd.png)

**Comment by kattrali** [comment]
Is `libBugsnagReactNative.a` included multiple times? Or listed in `Copy Bundle Resources` (below `Link Libraries`)?

**Comment by nihp** [comment]
It not listed in  `Copy Bundle Resources` (below `Link Libraries`)

Included only once (Link Binary with Libraries) 

Shall I need to add here as well or not

![screenshot 2019-02-26 at 4 26 27 pm](https://user-images.githubusercontent.com/36992338/53407917-4cc74d00-39e3-11e9-9fc9-a01d83125c73.png)

**Comment by kattrali** [comment]
Nope! Just trying to rule out things that might be wrong. Did you follow the [guide](https://docs.bugsnag.com/platforms/react-native/)? Is it possible that you used `react-native link` but also changed linked libraries manually? I'd also try a full clean (Command + Option + Shift + K) in Xcode to be safe.

**Comment by nihp** [comment]
I have Done the following and tried to build the app

1. Installation [(here)](https://docs.bugsnag.com/platforms/react-native/#installation)
2. Basic Configuration in index.js [(here)](https://docs.bugsnag.com/platforms/react-native/#basic-configuration)
3. iOS configuration (Linking manually) [here](https://docs.bugsnag.com/platforms/react-native/manual-linking-guide/#ios-configuration)

Ten tried to build the app

**Comment by nihp** [comment]
I have removed  node_modules and cleanedand again re-installed the package and tried to build. But after this BugsnagReactNative.h file not found error is shown in my Xcode as well as I can't able to see the BugsnagReactNative.Xcodeproj under node_modules in my App folder

**Comment by nihp** [comment]
I can able to build. But now I am facing an error as

Bugsnag: No native client found error

![screenshot 2019-02-27 at 12 20 52 pm](https://user-images.githubusercontent.com/36992338/53471292-24def480-3a8a-11e9-909e-af7ba7c7b066.png)

**Comment by kattrali** [comment]
Well that's progress! Is `libBugsnagReactNative.a` still listed in your Xcode Linked Libraries? Are the headers shown like so: 

<img width="1203" alt="Header Search Paths" src="https://user-images.githubusercontent.com/333454/53480651-88a9f300-3a73-11e9-9242-5d9c5515f369.png">

**Comment by nihp** [comment]
I am getting Bugsnag.h file not found error

**Comment by kattrali** [comment]
What does the actual error message say?

**Comment by nihp** [comment]
Bugsnag.h' file not found


Libraries ==>BugsnagReactNative.Xcodeproj ==>BugsnagReactNative.m ==> 
 Refer the attched inage

Kindly post your answerASAP

![screenshot 2019-02-28 at 5 19 46 pm](https://user-images.githubusercontent.com/36992338/53564583-4a005f80-3b7d-11e9-906a-051a7ca2aaf7.png)

**Comment by snmaynard** [comment]
As this is a support request rather than a diagnosed issue with the library itself, please contact support@bugsnag.com with a link to this issue and they will be able to help you. Thanks!

**Comment by ITAndriyTsymbalyuk** [comment]
> I am trying to setup the RNBugsnag, but while compiling the app I am getting an error as "**no such file or directory**: '/Users/XXXXXXX/Library/Developer/Xcode/DerivedData/Application/Build/Products/Debug-iphonesimulator/libBugsnagReactNative.a'
> 
> How to resolve this error

change display name
