### ISSUE TITLE
Unable to identify in which file (filename) I got error 

### ISSUE THREAD

**Issue by nihp** [bugsnag/bugsnag-react-native#315]
I am using react-native-bugsnag to monitor error and crash in my app. While generating any error, It not showing in which file the error get occurred. 

If I make any changes in my app it always showing the same log and not showing the error file.

Error:

**ReferenceError: Can't find variable: TouchableOpacity This error is located at: in App (at renderApplication.js:34) in RCTView (at View.js:45) in View (at AppContainer.js:98) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:33)**

**Comment by snmaynard** [comment]
Please contact support@bugsnag.com to get support on this issue.
