### ISSUE TITLE
Clarification: Can I able to upload the dsym file automatically in bugsnag 

### ISSUE THREAD

**Issue by nihp** [bugsnag/bugsnag-react-native#316]
While I am referring this thread I have a clarifications

1. Shall I need to setUser to know about the user details. How it will notify errors for the multiple users. 
[config setUser:@"userId" withName:@"User Name" andEmail:@"user@email.com"];

2. Does we have option to upload the dsym file  automatically in the step (Showing full stacktraces with bitcode)
[https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#uploading-mapping-files-for-android]

**Comment by fractalwrench** [comment]
Please contact support@bugsnag.com to get support on this issue.
