### ISSUE TITLE
Bugsnag doesn't report on ios (android not tested)

### ISSUE THREAD

**Issue by artechventure** [bugsnag/bugsnag-react-native#319]
### Description
Bugsnag doesn't report on ios(with or without codepush). 

### Issue

Bugsnag doens't report on ios in both debug and production.
The log in XCode shows

Sent 1 sessions to Bugsnag
Reports sent (when I trigger bugsnag.notify)

But nothing appears in dashboard.

### Environment

Library versions:

bugsnag-react-native@2.15.0
react-native-code-push@5.5.0
react-native-firebase@5.0.0
(We use react-native 0.56.1, however npm ls react-native shows empty)

- cocoapods version (if any) (`pod -v`): 1.5.3
- iOS/Android version(s): ios 12.1.4
- simulator/emulator or physical device?: physical device
- debug mode or production?: production (release build in Xcode)

- [O] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### More Info
AppDelegate.m
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [BugsnagReactNative start];
  [FIROptions defaultOptions].deepLinkURLScheme = @"SOMESTRING";
  [FIRApp configure];
  
  NSLog(@"dynamicLink, %@", launchOptions);
  NSString *idfaString = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
  NSLog(@"idfaString, %@", idfaString);
  
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  
  [[NSNotificationCenter defaultCenter] addObserver:self  selector:@selector(orientationChanged:)    name:UIDeviceOrientationDidChangeNotification  object:nil];
  
  NSURL *jsCodeLocation;
  #ifdef DEBUG
      jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  #else
      jsCodeLocation = [CodePush bundleURL];
  #endif

  
  // Initialise RNCallKit
  RNCallKit *rncallkit = [[RNCallKit alloc] init];
  
  // Initialise React Bridge with RNCallKit
  RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation
                                            moduleProvider:^{ return @[rncallkit]; }
                                             launchOptions:launchOptions];
  
  // Initialise React Root View with React Bridge you've just created
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Wave"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:0.0f green:0.0f blue:0.0f alpha:0];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  [RNSplashScreen show];
  return YES;
}
`

Bugsnag.js
`import {Client, Configuration} from 'bugsnag-react-native';
const codeBundleId = BUNDLEID
const config = new Configuration(API_KEY);
config.codeBundleId = codeBundleId;

const bugsnag = new Client(config);

export default bugsnag;
`

and we import Bugsnag.js in index.js after importing AppRegistry.

**Comment by mattdyoung** [comment]
Now being progressed by Bugsnag Support on a support ticket so closing.

Suspect this was due to events being sampled due to exceeding quota rather than the library being misconfigured.
