### ISSUE TITLE
Android Assemble Release not working

### ISSUE THREAD

**Issue by Blutude** [bugsnag/bugsnag-react-native#321]
### Description

Trying to run command ./gradlew assembleRelease
### Issue

Here is part of my stacktrace:
`> Task :app:uploadBugsnagReleaseMapping 
Mapping file not found: null

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bugsnag-react-native:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /Users/ronyazrak/Documents/McGill/Winter18/Spap/code/PROJ_SPAP_FRONT/Spap/node_modules/bugsnag-react-native/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.`
### Environment

Library versions:

```shell
├── bugsnag-react-native@2.14.0 
└── react-native@0.58.6 
```

- cocoapods version (if any) (`pod -v`): no
- iOS/Android version(s):
- simulator/emulator or physical device?: physical
- debug mode or production?: production

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [x] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class? no

I was following the [guide](https://docs.bugsnag.com/build-integrations/gradle/) for the bugsnag android gradle plugin. I noticed that I might have not installed the plugin myself. The guide says the following:
"Add the following dependency to <project_dir>/build.gradle:

buildscript {
    dependencies {
        // ...
        classpath 'com.bugsnag:bugsnag-android-gradle-plugin:4.+'
    }
}"

Which is exactly what I did. Does that alone install the plugin? I also did the basic configuration part of the guide.

What about this 'com.bugsnag:bugsnag-android-gradle-plugin:4.+'? Am I suppose to replace the '+' by a specific version?

**Comment by younes200** [comment]
Hi,
I got similar issue  when enabling Proguard `def enableProguardInReleaseBuilds = true`but with different error output :

```
Attempting upload of mapping file to Bugsnag
Bugsnag upload failed with code 422: Received empty file
``` 
The `com.bugsnag:bugsnag-android-gradle-plugin:4.+` is correct, the '+' symbol to use the last minor release of the plugin. You also need to add the `apply plugin: 'com.bugsnag.android.gradle'` **in android/app/build.gradle**

**Comment by fractalwrench** [comment]
Thanks for the report @Blutude - it doesn't seem that the `Aapt2Exception` is related to bugsnag from the observed trace. If you're able to consistently reproduce this issue, a minimal example that triggers the behaviour would be great help in debugging the issue, otherwise for now I'm going to close this issue.

**Comment by ghsdh3409** [comment]
Setting compileSdkVersion to 28 solved it for me.

**Comment by zaytsevfuu** [comment]
This answer worked for me: https://github.com/luggit/react-native-config/issues/299#issuecomment-474893874
