### ISSUE TITLE
Disable console.warn on NativeSerializer.js

### ISSUE THREAD

**Issue by vafada** [bugsnag/bugsnag-react-native#323]
### Description

A lot of console.warn yellow warning message when the data pass to leaveBreadcrumbs contains functions.

**Describe the solution you'd like**

There must be a way to disable this line:

https://github.com/bugsnag/bugsnag-react-native/blob/67468086569e17d37e08ac7a719d46af3971c9a0/src/NativeSerializer.js#L36

**Describe alternatives you've considered**

In our code, we traverse the data and delete functions before passing it to leaveBreadcrumbs

**Additional context**
Add any other context about the feature request here.

**Comment by johnkiely1** [comment]
Hi @vafada ,

Could you describe a bit more about your use case here, what are you trying to achieve. Could you share an example of your code used to call leaveBreadcrumbs?

Thanks

**Comment by johnkiely1** [comment]
Hi @vafada
If this is still creating a problem for you, I recommend you upgrade as this issue will no longer occur in (v7.3.4) of the Bugsnag react native library. As of v7.3 the library itself has now become part of the [bugsnag-js](https://github.com/bugsnag/bugsnag-js) repository.
An upgrade guide can be found [here](https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/UPGRADING.md) with full documentation available [here](https://docs.bugsnag.com/platforms/react-native/react-native/).
