### ISSUE TITLE
Clarification: Did the Bitcode enabled step upload the dsym file automatically

### ISSUE THREAD

**Issue by nihp** [bugsnag/bugsnag-react-native#324]
I have a clarification about uploading the dsym file. 

1. Does the bitcode enabled method will upload the dsym file automatically.

2. If I upload a build in Testflight, then how it will reflect the crash and error report in bugsnag.(i.e) Shall I need to add the bugsnag.notify in all screen.

i.e) I have  setup all configuration and build the app and uploaded in testflight to verify. How can I know about the errors in bugsnag

**Comment by mattdyoung** [comment]
This is a support question rather than an issue with the library so responding on your existing support query.
