### ISSUE TITLE
Upgrade bugsnag-cocoa to 5.19.1

### ISSUE THREAD

**Issue by Jekiwijaya** [bugsnag/bugsnag-react-native#329]
### Description
Please upgrade bugsnag-cocoa to 5.19.1
https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v5.19.1

You could teach me how to build the cocoa in this repo, and I will make the pull request.

I need https://github.com/bugsnag/bugsnag-cocoa/pull/332 to be fix, thank you.

#320

**Comment by fractalwrench** [comment]
Thanks for getting in touch @Jekiwijaya - v2.16.0 now uses bugsnag-cocoa v5.19.1.
