### ISSUE TITLE
Please help , i m gotting thiis error while i m trying to use react native maps

### ISSUE THREAD

**Issue by Bassemdh** [bugsnag/bugsnag-react-native#333]
> Could not resolve com.android.support:support-core-utils:28.0.0.
  Required by:
      project :react-native-maps > com.facebook.react:react-native:0.59.4 > com.android.support:appcompat-v7:28.0.0
      project :react-native-maps > com.android.support:support-fragment:28.0.0
      project :react-native-maps > com.android.support:support-core-ui:28.0.0
   > Cannot find a version of 'com.android.support:support-core-utils' that satisfies the version constraints: 
        Dependency path 'covoiturageReactNative:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.4' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0'
        Dependency path 'covoiturageReactNative:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.4' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-utils:28.0.0'
        Dependency path 'covoiturageReactNative:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:16.0.1' --> 'com.google.android.gms:play-services-basement:16.0.1' --> 'com.android.support:support-v4:26.1.0' --> 'com.android.support:support-core-utils:26.1.0'
        Dependency path 'covoiturageReactNative:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.4' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:support-core-utils:28.0.0'
        Constraint path 'covoiturageReactNative:react-native-maps:unspecified' --> 'com.android.support:support-core-utils' strictly '26.1.0' because of the following reason: debugRuntimeClasspath uses version 26.1.0
        Constraint path 'covoiturageReactNative:react-native-maps:unspecified' --> 'com.android.support:support-core-utils' strictly '26.1.0' because of the following reason: debugRuntimeClasspath uses version 26.1.0
        Constraint path 'covoiturageReactNative:react-native-maps:unspecified' --> 'com.android.support:support-core-utils' strictly '26.1.0' because of the following reason: debugRuntimeClasspath uses version 26.1.0

**Comment by fractalwrench** [comment]
I'm closing this issue as it does not appear to be an issue with the bugsnag-react-native library - please write into support@bugsnag.com who will be able to help you with any integration issues.
