### ISSUE TITLE
Support React Native RAM Bundle

### ISSUE THREAD

**Issue by Jekiwijaya** [bugsnag/bugsnag-react-native#334]
### Description
React Native supports a binary bundle format to avoid having to load the whole js bundle in memory initially. Doc here: https://facebook.github.io/react-native/docs/performance#ram-bundles-inline-requires.

I tried upload my sourcemap in ram bundle format, but the error could not be mapped to the source map.

Is there any plans to support ram bundle? Sentry also tried to support ram bundle, https://github.com/getsentry/sentry-cli/issues/408

**Comment by fractalwrench** [comment]
We're working on adding support for RAM bundles, and have been communicating with FB to get some of the packages mentioned in the other thread open-sourced.

**Comment by Jekiwijaya** [comment]
Cannot wait @fractalwrench! Tell me if there's any I can help

**Comment by fractalwrench** [comment]
I'm happy to announce that we now support RAM bundles on React Native. You can find documentation here: https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#uploading-source-maps
