### ISSUE TITLE
Redefinition of module 'Bugsnag'

### ISSUE THREAD

**Issue by WASHSWATDAVID** [bugsnag/bugsnag-react-native#339]
I got the run-time error when I build react-native ios build without cocoapod.
Of course I've did `react-native link bugsnag-react-native` so Android version it's ok but iOS is not working with these messages. `Redefinition of module 'Bugsnag'`

I'm not sure what happened my project, is there any solution for me?

![Screen Shot 2019-04-23 at 12 46 12 AM](https://user-images.githubusercontent.com/39440825/56509401-d3228a00-6561-11e9-811b-ebb8e1df7979.png)

**Comment by snmaynard** [comment]
I recommend emailing support@bugsnag.com with this and we can help you there - GitHub issues are for issues with the library itself rather than support. Thanks!

**Comment by igorlamos** [comment]
I think @WASHSWATDAVID's problem is related to the latest release 2.17.0 of this library ... 

I ran into the same issue while updating from 2.16.0 > 2.17.0... Actually, I solved this easily by downgrading back to 2.16.0, which works fine.

**Comment by el-lsan** [comment]
facing the same issue after updating from `2.16.0` to `2.17.0`.

**Comment by mattdyoung** [comment]
You're right. We've now found that there was an issue with the 2.17.0 release of bugsnag-react-native where some build artefacts were included which resulted in duplicate header files, preventing compilation for iOS.

This has now been resolved in 2.17.1 so please try with the new version. Thanks!

**Comment by igorlamos** [comment]
> This has now been resolved in 2.17.1 so please try with the new version. Thanks!

iOS compilatiln now OK with the version 2.17.1. Thank you!
