### ISSUE TITLE
exceptions trigger crash in bugsnag

### ISSUE THREAD

**Issue by tijs** [bugsnag/bugsnag-react-native#34]
I'm running into an issue where a call to notify(), an exception, crashes my app. In the debugger it's shown as 'mapState is not a function' error.

![screen shot 2016-12-01 at 12 41 33](https://cloud.githubusercontent.com/assets/3108/20792722/a9144c6a-b7c3-11e6-95b2-73fd87654532.png)

```
ExceptionsManager.js:63 mapState is not a functionhandleException @  
ExceptionsManager.js:63handleError @ InitializeCore.js:108(anonymous function) @   Bugsnag.js:46reportFatalError @ error-guard.js:40guard @   MessageQueue.js:48callFunctionReturnFlushedQueue @ MessageQueue.js:107(anonymous   function) @ debuggerWorker.js:71  
ExceptionsManager.js:71 Unhandled JS Exception: mapState is not a   functionreactConsoleErrorHandler @ ExceptionsManager.js:71console.error @   YellowBox.js:61logIfNoNativeHook @ RCTLog.js:38__callFunction @   MessageQueue.js:236(anonymous function) @ MessageQueue.js:108guard @   MessageQueue.js:46callFunctionReturnFlushedQueue @ MessageQueue.js:107(anonymous   function) @ debuggerWorker.js:71  
```

**Comment by kattrali** [comment]
Thanks for the report, @tijs. This is pretty odd. It seems to coming from deep in [react-redux](https://github.com/reactjs/react-redux/blob/68a4f2b78671329e10bfca87f8f1c82cc8690459/src/components/connect.js#L114). Can you share more about your application, such as the React Native version, library version, and device/OS used?

**Comment by tijs** [comment]
Yeah it's indeed weird :)

This was on react-native 0.38 and 0.39, with the latest bugsnag release and on iOS simulator (iOS 10.1). It's not easily reproducible to be honest so this is as detailed as i can report it.

**Comment by kattrali** [comment]
Was it just something like `notify(new Error("…"))` or potentially something more?

**Comment by tijs** [comment]
almost.. i did use the metadata feature:

```
this.client.notify(error, function(report) {
  report.metadata = { ...user };
});
```

**Comment by kattrali** [comment]
The v1.1.4 release went out shortly after this, would you be able to retest this, @tijs? I haven’t been able to reproduce it, but maybe it was related to other issues which were fixed.

**Comment by tijs** [comment]
@kattrali will do! i have a release to finish up first but will have a look again next week.

**Comment by kattrali** [comment]
Closing this out, but feel free to reopen if this issue persists. Thanks again, @tijs.
