### ISSUE TITLE
Possibility to add filters in configuration

### ISSUE THREAD

**Issue by jrnk** [bugsnag/bugsnag-react-native#341]
### Description
We're missing the option to add filters like described here https://docs.bugsnag.com/platforms/javascript/configuration-options/#filters

**Describe the solution you'd like**
The ability to add them to the configuration, the same way like https://docs.bugsnag.com/platforms/javascript/configuration-options/#filters

**Comment by johnkiely1** [comment]
Hi @jrnk 
The React Native Bugsnag library has undergone a major refresh very recently. As of [v7.3.x](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.3), now available via [bugsnag-js](https://github.com/bugsnag/bugsnag-js), you can use `redactedKeys` to achieve a similar functionality as `filters`. More information on how to use `redactedKeys` can be found [here.](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#releasestage).  You can also find an upgrade guide [here](https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/UPGRADING.md) which may be useful.
