### ISSUE TITLE
bugsnag.setUser() number crashes

### ISSUE THREAD

**Issue by mifi** [bugsnag/bugsnag-react-native#343]
### Description
calling bugsnag.setUser() with an ID which is a number, causes an error.

### Issue
<img width="367" alt="Screenshot 2019-04-24 at 14 26 43" src="https://user-images.githubusercontent.com/402547/56659574-c7d47900-669d-11e9-89e0-ebf17bb049d4.png">

### Environment
iOS Simulator

### Example code snippet

bugsnag.setUser(3, 'Jessica Jones', 'jess@example.com');

I beleive it should handle numbers too for IDs, at least it should not crash. At the very least the documentation should say that a string is required or it will crash.

**Comment by bengourley** [comment]
Hi @mifi, thanks for the report. Ideally IDs should be strings, but as you say, the library shouldn't crash for you if you use a number. This has been fixed in #346 and will be reviewed/released soon.
