### ISSUE TITLE
Improve API Doc

### ISSUE THREAD

**Issue by mifi** [bugsnag/bugsnag-react-native#344]
### Description
I think it was hard to find the documentation for the API. In particular:
- When creating a Client object, I'm a bit confused, can I have multiple clients with different api keys in my project, since it's an instantiable class, if so how does this work? If not, bugsnag could be a singleton/global object, and it would be nice if there was a global way to import the current bugsnag instance. Like this `import { bugsnag } from 'bugsnag-react-native'`, as is common with other logging utilities. At the very least show an example of how to share the object between in the getting started doc.
Like this:
```js
// bugsnag.js
import { Client } from 'bugsnag-react-native';
export default new Client('APIKEY');
```

- Could not find the API signature of `bugsnag.notify()` and `bugsnag.setUser()` in the docs. They are among the most important functions so they should be easy to figure out at a quick glance. And when using a reporting/logging framework IMO it's important that the developer doesn't misunderstand the api causing a crash when calling it, because logging/reporting should be very unobtrusive. At the very least link to [TypeScript defs](https://github.com/bugsnag/bugsnag-react-native/blob/master/index.d.ts) from the documentation at the places where you mention Client or notify or setUser etc.

**Comment by StijnCoolen** [comment]
@mifi I agree, having an example that shows the use of a singleton would be great.

**Comment by abigail-bugsnag** [comment]
@mifi @StijnCoolen - Thank you for your comments. We are currently working on a project to refresh our React Native notifier. As part of this work, our documentation will receive significant updates. I have registered your comments with our product team so that they are considered during this work.

**Comment by Hamawis** [comment]
@phillipsam any update on it

**Comment by phillipsam** [comment]
Hi @Hamawis - the refresh of our React Native notifier is something that we are working on and hope to release in the coming months.
