### ISSUE TITLE
Configuration 'compile' is obsolete

### ISSUE THREAD

**Issue by tijs** [bugsnag/bugsnag-react-native#359]
### Description

When using bugsnag-react-native in an android project you will see the following warning when building the project:

```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

This can be resolved by changing the compile calls in build.gradle to implementation as described in the linked docs.

### Issue

A warning is shown in build logs.

### Environment

Library versions: 

```shell
├─ bugsnag-react-native@2.19.1
└─ react-native@0.58.6
```

**Comment by pqkluan** [comment]
Duplicate with PR #303

**Comment by tijs** [comment]
@pqkluan ah your right i missed that one. I'll close this then, thanks for the heads up!
