### ISSUE TITLE
Remove isError dependency

### ISSUE THREAD

**Issue by snmishra** [bugsnag/bugsnag-react-native#368]
### Description

Single function dependencies are annoying. isError is the only dependency for bugsnag-react-native

**Describe the solution you'd like**

The entirety of the dependency is this and hasn't changed in two years and it should be included in the package directly: 
```
function isError(value) {
  switch (Object.prototype.toString.call(value)) {
    case '[object Error]': return true;
    case '[object Exception]': return true;
    case '[object DOMException]': return true;
    default: return value instanceof Error;
  }
}
```

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by bengourley** [comment]
We're working towards using [`bugsnag-js` core](https://github.com/bugsnag/bugsnag-js/tree/next/packages/core) for the JS side of the React Native notifier which includes `iserror` as a dependency (amongst others), so I'm going to close this off.
