### ISSUE TITLE
Requiring unknown module "promise/setimmediate/rejection-tracking"

### ISSUE THREAD

**Issue by JonasWho** [bugsnag/bugsnag-react-native#37]
This error happens already when I call `client = new Client(BUGSNAG_API_KEY);` Not in __DEV__ mode though. I'm using v.1.3.1. 

It looks like the error happens in line 53 in lib/Bugsnag.js

<img width="471" alt="genymotion_-_google_galaxy_nexus_-_4_3_-_api_18_-_720x1280__720x1280__320dpi__-_192_168_56_101" src="https://cloud.githubusercontent.com/assets/925342/20877395/b9f6217c-bac8-11e6-890d-2bd732118a87.png">

**Comment by wordofchristian** [comment]
`promise` is a dependency of react-native and should have been installed when you initialized your application. Is `promise` present when you look in your node_modules folder? Is `node_modules/promise/setimmediate/rejection-tracking.js` present?

**Comment by JonasWho** [comment]
@wordofchristian no I dont have `promise` in my node_modules, it doesnt appear after `npm install`either? I'm confused cause I use Promises a lot in my code and I've never seen this error before I installed Bugsnag 1.1.3. It doesn't happen for me if I downgrade to older versions of bugsnag-react-native

**Comment by wordofchristian** [comment]
This is strange, perhaps bugsnag-react-native should list promise as a dependency directly. I'll open a PR for that. In the meantime you might try adding it to your app to see if that resolves the problem. 

What version of react-native do you have?

**Comment by JonasWho** [comment]
Ok, yeah I am really new to npm and this whole js-library world, so it might have been because I had an older npm version installed?? Now I updated everything, deleted my node_modules and ran `npm install` and now I do have ´promise´ lib. Sounds like it might be a good idea to have it as a dependency. react-native does have it as a dependcy I can see.
