### ISSUE TITLE
Inconsistent setUser argument order.

### ISSUE THREAD

**Issue by iggyfisk** [bugsnag/bugsnag-react-native#38]
We're using this library in our production app on both iOS and Android, and it works great. However, when we attach user info to our reports, the properties get scrambled between platforms. We set user info as:
`Bugsnag.setUser(profile.id, profile.name, '');`

When viewing our reports in the Bugsnag web interface, the user info is correct for iOS events. For Android, `profile.name` appears as "email", while "name" is empty. I believe this is because of the different order in this method declaration/call:

https://github.com/bugsnag/bugsnag-react-native/blob/master/android/src/main/java/com/bugsnag/BugsnagReactNative.java#L101
https://github.com/bugsnag/bugsnag-java/blob/f135429eec2ee3c90a9a32055cedacc2979558ec/src/main/java/com/bugsnag/Report.java#L230

**Comment by kattrali** [comment]
Thanks for the report and the direction, @iggyfisk. You're quite right!
