### ISSUE TITLE
Enable background OOM detection in react native

### ISSUE THREAD

**Issue by bengtan** [bugsnag/bugsnag-react-native#383]
Bugsnag for iOS has settings `reportOOMs` and `reportBackgroundOOMs` to configure OOM detection (https://docs.bugsnag.com/platforms/ios/configuration-options/#reportbackgroundooms). Are these settings available for react native as well? They don't appear in the react native docs (https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/).

Specifically, I'd like to enable `reportBackgroundOOMs` for react native.

(FYI, we're currently using react-native-bugsnag 2.21.1.)

**Comment by bengtan** [comment]
Never mind.

**Comment by stripathi669** [comment]
@bengtan Were you able to figure this out?

**Comment by mattdyoung** [comment]
Hi @stripathi669 

Background OOM detection is no longer available in bugsnag-cocoa. This property was removed in v5.22.9 as determining background OOMs was found to be unreliable and caused a number of false positives.

Foreground OOM detection is now enabled by default in bugsnag-cocoa and bugsnag-react-native, but you can alter this (and any other bugsnag-cocoa configuration options), by using the enhanced native integration for bugsnag-react-native as shown here:
https://docs.bugsnag.com/platforms/react-native/react-native/enhanced-native-integration/#ios-native-installation

**Comment by stripathi669** [comment]
@mattdyoung Thank you for that information!
