### ISSUE TITLE
Build failed with the /node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/KSCrash/Source/KSCrash/Recording/Tools/NSDictionary+BSG_Merge.m

### ISSUE THREAD

**Issue by nihp** [bugsnag/bugsnag-react-native#387]
I am getting this error while compiling the app.{ **/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Source/KSCrash/Source/KSCrash/Recording/Tools/NSDictionary+BSG_Merge.m**}

But it worked as expected previously. Suddenly I got an error with this package. Can anyone suggest how to solve this error while building the app?

**Comment by kattrali** [comment]
Thanks for the report @nihp - can you remove the `ios/build` directory in your project and retry? It sounds like a clean build will fix the issue.

**Comment by nihp** [comment]
@kattrali My clarification is I have ios/Build folder(**B**uild not **b**uild). It has many folders. Do the **B**uild and **b**uild files have derived datas?

**Comment by nihp** [comment]
I have fixed the above error by cleaning the build folder and also removed the derived data.

I have a clarification here. I have ios**/B**uild folder not ios**/b**uild. The both build has the same files or not.

**Comment by kattrali** [comment]
Thanks, glad it worked. 👍
