### ISSUE TITLE
ios warning: UI API called on a background thread

### ISSUE THREAD

**Issue by idanhaviv** [bugsnag/bugsnag-react-native#396]
### Description
running on iPhone X ios 12.2 in debug from Xcode logs a Main Thread Checker warning in Xcode logs

### Environment

Library versions:

```shell
bugsnag-react-native@2.22.6
react-native@0.60.4
```

- cocoapods version 1.6.1
- iOS version: 12.2 
- physical device
- debug mode

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class? - no

**Comment by kattrali** [comment]
Thanks for the report, @idanhaviv. What was in the log message? As far as I can tell, bugsnag-react-native does not call UI methods.

**Comment by idanhaviv** [comment]
hey @kattrali, this is a screenshot of Xcode log ![Untitled](https://user-images.githubusercontent.com/8762573/64097914-1d1c4780-cd6e-11e9-9abf-f8787b8eec1f.png)

**Comment by kattrali** [comment]
Ah, I see. This seems to be a side effect of expecting initialization to take place on the main thread. The library should handle and warn you in this case, but to work around it, can you configure `[BugsnagReactNative start]` in your app delegate?

**Comment by chipqcl** [comment]
> can you configure `[BugsnagReactNative start]` in your app delegate?

Can you give specific instructions for this?

**Comment by idanhaviv** [comment]
@kattrali 
i did but still get the warning message

**Comment by abigail-bugsnag** [comment]
> > can you configure `[BugsnagReactNative start]` in your app delegate?
> 
> Can you give specific instructions for this?

@chipqcl @idanhaviv There are instructions available in our documentation here: https://docs.bugsnag.com/platforms/react-native/react-native/enhanced-native-integration/#ios-native-installation. Let us know if you have further questions.

**Comment by idanhaviv** [comment]
adding the api key in info.plist in addition to [BugsnagReactNative start] solved it.
@abigail-bugsnag maybe it's worth adding it to the react-native setup docs

**Comment by chipqcl** [comment]
> There are instructions available in our documentation here

Thanks, that worked.

**Comment by mattdyoung** [comment]
Fixed in [v2.23.2](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.2), so the workaround of calling `[BugsnagReactNative start]` should no longer be necessary, unless you require the enhanced native integration for another reason.
