### ISSUE TITLE
CodePush sourceMap is not mapped

### ISSUE THREAD

**Issue by jpacyfik** [bugsnag/bugsnag-react-native#404]
Hello,

I'm using both Bugsnag and CodePush. 
Today I've released new codepush update, ofc following your docs.

I've uploaded ios/android bundles and everything seems to be OK. Of course, they are visible in settings panel with proper bundle ids.

I've forced our users to update the app and I removed all events/issues from my bugsnag to be 100% sure that all events will be from new release.

However, bugsnag is not able to match stacktrace of new bugs with correct source/bundle. 

<img width="1522" alt="Screenshot 2019-09-11 at 15 57 46" src="https://user-images.githubusercontent.com/20946910/64704115-08e2f380-d4ae-11e9-8113-ab3753bc05ac.png">
<img width="732" alt="Screenshot 2019-09-11 at 15 57 34" src="https://user-images.githubusercontent.com/20946910/64704116-08e2f380-d4ae-11e9-97b3-b8ae088ebb58.png">

**Comment by mattdyoung** [comment]
Hi @jpacyfik 

I can't see anything obviously wrong that would cause this from your description and screenshots.

Can you contact support@bugsnag.com with a link to that error in your dashboard so I can try and identify the cause.

Thanks!
