### ISSUE TITLE
Error Android build React Native 0.60.+

### ISSUE THREAD

**Issue by mezalejandro** [bugsnag/bugsnag-react-native#406]
When I run react-native run-android or ./gradlew assembleRelease I have the following error:
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve androidx.annotation:annotation:{strictly 1.0.0}.
Could not resolve androidx.annotation:annotation:1.0.0.
     Required by:
         project :app > com.facebook.android:facebook-core:5.5.1
         project :app > androidx.cursoradapter:cursoradapter:1.0.0
         project :app > androidx.drawerlayout:drawerlayout:1.0.0
         project :app > androidx.legacy:legacy-support-core-utils:1.0.0
         project :app > androidx.cardview:cardview:1.0.0
         project :app > androidx.browser:browser:1.0.0
         project :app > androidx.viewpager:viewpager:1.0.0
         project :app > androidx.loader:loader:1.0.0
         project :app > androidx.customview:customview:1.0.0
         project :app > androidx.interpolator:interpolator:1.0.0
         project :app > androidx.documentfile:documentfile:1.0.0
         project :app > androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
         project :app > androidx.print:print:1.0.0
         project :app > androidx.media:media:1.0.0
         project :app > androidx.legacy:legacy-support-core-ui:1.0.0
         project :app > androidx.coordinatorlayout:coordinatorlayout:1.0.0
         project :app > androidx.slidingpanelayout:slidingpanelayout:1.0.0
         project :app > androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
         project :app > androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
         project :app > androidx.arch.core:core-runtime:2.0.0

**Comment by mattdyoung** [comment]
Hi @mezalejandro 

I saw you also wrote in to support@bugsnag.com with the same issue so we've been responding to you there.

We can't currently see why it's not finding that dependency but this definitely looks like a gradle configuration issue rather than any bug with the library. The dependency it's looking for does exist in Google's maven repository:
https://mvnrepository.com/artifact/androidx.annotation/annotation/1.0.0
