### ISSUE TITLE
Does this module capture crashes?

### ISSUE THREAD

**Issue by yabinliu** [bugsnag/bugsnag-react-native#41]

**Comment by tijs** [comment]
i did wonder the same. in [the blog post introducing this new module](https://blog.bugsnag.com/bugsnag-react-native/) it mentions crash reporting but i cannot find anything about crash reporting features in the docs..

**Comment by kattrali** [comment]
@yabinliu Yes. The native components of the library depends on/vendor the crash handling logic from [bugsnag-android](github.com/bugsnag/bugsnag-android) and [bugsnag-cocoa](github.com/bugsnag/bugsnag-cocoa). Crashes are reported automatically and include the stacktraces and other runtime information.

@tijs There’s a [brief snippet](https://docs.bugsnag.com/platforms/react-native/#reporting-unhandled-errors) in the docs to indicate unhandled errors are reported automatically, but I’ll update it to make it clearer that this includes crashes.

**Comment by tijs** [comment]
@kattrali great, some extra explanation will go a long way probably :)
