### ISSUE TITLE
Runtime Error: No native client found. Is Bugsnag React Native installed in your native code project?

### ISSUE THREAD

**Issue by Rutvik17** [bugsnag/bugsnag-react-native#413]
### Description
I am integrating bugsnag into my React Native Project following the official docs on bugsnag website. After completing all the steps successfully the app builds successfully on both android and ios but it fails on runtime with an error below.

### Issue
React Native Runtime Error: No native client found. Is Bugsnag React Native installed in your native code project? 

```js
Bugsnag: No native client found. Is BugsnagReactNative installed in your native code project?
Client

<unknown>
    global.js:4:27
loadModuleImplementation
    require.js:331:6
<unknown>
    index.android.js:9
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code
```

### Environment
React-Native MacOS

Library versions:
```js
"react": "16.8.3",
"react-native": "0.59.10",
"bugsnag-react-native": "^2.23.2",
```

I have updated my AndroidManifest.xml, MainApplication.java, Info.plist, build.gradle to include the api-key and bugsnag-react-native was successful too.

### AndroidManifest.xml
```xml
 <meta-data android:name="com.bugsnag.android.API_KEY"
               android:value="API KEY"/>
```

### MainApplication.java
```java
@Override
 public void onCreate() {
    super.onCreate();
    BugsnagReactNative.start(this);
    SoLoader.init(this, /* native exopackage */ false);
  }
```
### info.plist
```plist
<key>BugsnagAPIKey</key>
<string>API KEY</string>
```

**Comment by mattdyoung** [comment]
Hi @Rutvik17 

Are you seeing this on iOS or Android or both?

Did you run:
`react-native link bugsnag-react-native`

**Comment by Rutvik17** [comment]
Yes this is happening on both iOS and Android. 
I did run 
``js
react-native link bugsnag-react-native
``
It said the link was successful.

**Comment by mattdyoung** [comment]
Solved via a related support request.

For some reason the `react-native link bugsnag-react-native` step wasn't working on this project although it worked fine on a cleanly created project on RN 0.59.10.

After linking the binaries manually in XCode for the iOS project and adding the appropriate imports and `BugsnagReactNative.getPackage()` to `getPackages()` in MainApplication.java on the Android project (as `react-native link` should have done), the issue was resolved.
