### ISSUE TITLE
bugsnag doesn't report newly created errors

### ISSUE THREAD

**Issue by idanhaviv** [bugsnag/bugsnag-react-native#414]
### Description
trying to log handled exceptions with bugsnag.notify()

### Issue
calling bugsnag.notify(new Error("test")) doesn't appear on dashboard
calling bugsnag.notifity(error) when error is a caught error from fetch api appears on dashboard

### Environment

Library versions:
"react": "16.8.6",
"react-native": "0.60.4",
"bugsnag-react-native": "^2.22.6",
- cocoapods version 1.8.3
- iOS 12.2
- simulator
- debug

- [x] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?

**Comment by abigail-bugsnag** [comment]
Hi @idanhaviv - Your call to `bugsnag.notify(new Error("test"))` should work. We have just tested this out on the latest library.

Can you try taking our [example app here](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/plain) and changing `app/index.js` to:
```
function triggerHandledException() {
  bugsnag.notify(new Error("message"));
  //bogusHandledFunction(); // eslint-disable-line no-undef
}
```
Clicking to trigger a handled exception works on this example. Can you see something you are doing differently?

**Comment by idanhaviv** [comment]
sorry, can't seem to reproduce. now everything seems to be working fine
thanks!
