### ISSUE TITLE
Ensure you have started Bugsnag with startWithApiKey: before calling any other Bugsnag functions

### ISSUE THREAD

**Issue by Sbphillips19** [bugsnag/bugsnag-react-native#415]
### Description
Launching my app in release mode recently started getting this issue on my conversion from RN .59 to .60.5

### Issue

> 2019-10-10 16:03:51.911483-0500 SkiBuds[25156:339253] Ensure you have started Bugsnag with startWithApiKey: before calling any other Bugsnag functions.
> 2019-10-10 16:03:51.912051-0500 SkiBuds[25156:339253] Ensure you have started Bugsnag with startWithApiKey: before calling any other Bugsnag functions.

### Environment

Library versions:

```
SkiBuds@0.0.1 /Users/stephenphillips/Desktop/SB/SkiBuds
├── bugsnag-react-native@2.23.1
└── react-native@0.60.5
```

- cocoapods version (if any) (`pod -v`): 1.7.5
- iOS/Android version(s): iOS 13.1
- simulator/emulator or physical device?: Simulator
- debug mode or production?: Release mode

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?

Not sure where I would include that?  I don't see anything in the setup instructions

### Example code snippet

index.js

`import {bugsnag} from './app/configs/bugsnag';`

Bugsnag.js

```
import { Client } from 'bugsnag-react-native';
import Config from 'react-native-config'

export const bugsnag = new Client(Config.BUGSNAG_KEY);
```

Bugsnag Error Class
```

import { bugsnag } from './bugsnag'

export default function (err) {
  console.log("BUGSNAG ERR", err);
  if (err) {
    if (!err.stack) {
      err = new Error(err)
    }
    bugsnag.notify.apply(bugsnag, [err])
  }
}
```

**Comment by abigail-bugsnag** [comment]
Hi @Sbphillips19 the `[BugsnagReactNative start]` option is configured in the [Enhanced Native Integration](https://docs.bugsnag.com/platforms/react-native/react-native/enhanced-native-integration/) guide. The [iOS native installation](https://docs.bugsnag.com/platforms/react-native/react-native/enhanced-native-integration/#ios-native-installation) on that page describes the steps you will need.
Have you followed the enhanced native integration steps?

**Comment by Sbphillips19** [comment]
Closing issue since I didn't know about this advanced integration.  Thank you!
