### ISSUE TITLE
Question regarding upgrading version

### ISSUE THREAD

**Issue by yaronlevi** [bugsnag/bugsnag-react-native#418]
We now @ version 2.22.6 and want to upgrade to 2.23.2
Is it enough to update the package.json file and run npm install or do we need some other changes in the native side?

I am asking that because I saw in the changelog some changes regarding the code native sdk being used.

**Comment by tomlongridge** [comment]
@yaronlevi - updating the NPM dependency as you describe should be sufficient. Please let us know if you have any issues.

We aim to keep the React Native notifier up-to-date with the latest releases on the iOS and Android native notifiers, so this happens regularly.
