### ISSUE TITLE
Android Runtime Error: No native client found 

### ISSUE THREAD

**Issue by kevinnguy** [bugsnag/bugsnag-react-native#42]
Same issue as https://github.com/bugsnag/bugsnag-react-native/issues/14 but on Android. I'm able to run my app on iOS but not for Android.

I'm on 
```
"bugsnag-react-native": "^1.1.4", 
"react-native": "0.39.0"
```

**Comment by the-simian** [comment]
Hey, have you added bugsnad to your `MainApplication.java`
I got that error before I had added the libraries:

```java

   import com.bugsnag.BugsnagReactNative;

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          //... other packages here.
          BugsnagReactNative.getPackage(),

      );
    }
  };
```

the fact you call `getPackage()` is unusual, most don't work or look like that.

**Comment by kevinnguy** [comment]
Ahh that fixed it @the-simian. My project is using `react-native-navigation` so `react-native link` may have not worked properly. Thanks for pointing it out!

**Comment by PaijoRX** [comment]
Hey, I got same issue.

![screenshot_1530760718](https://user-images.githubusercontent.com/5009491/42300936-f3f16d38-803c-11e8-9727-3868076109c8.png)


I'm using:

```
"bugsnag-react-native": "^2.10.0",
"react-native": "^0.48.4",

```

I already configured (link)

*settings.gradle*
```
include ':bugsnag-react-native'
project(':bugsnag-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/bugsnag-react-native/android')
```

*app/build.gradle*
```
compile project(':bugsnag-react-native')
```

*MainApplication.java -> getPackages*
```
...
new MainReactPackage(),
BugsnagReactNative.getPackage(),
...
```

*MainApplication.java -> onCreate*
```
super.onCreate();
BugsnagReactNative.start(this);
...
```

I have no idea how to fix the issue. I already followed the basic configuration step.

**Comment by kinza88** [comment]
@PaijoRX 
Hey! Did you find any solution?

**Comment by beausmith** [comment]
@kinza88  @PaijoRX - I had the same issue and this is the solution that worked for me: https://github.com/bugsnag/bugsnag-react-native/issues/269

Probably a bit late for: @kevinnguy

**Comment by maulikdhameliya** [comment]
Hi, I am using react-native-navigation and somehow react-native link didn't add the package in MainApplication.java file.

   import com.bugsnag.BugsnagReactNative;

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          //... other packages here.
          BugsnagReactNative.getPackage(),

      );
    }
  };

**Comment by xintong621** [comment]
> Hi, I am using react-native-navigation and somehow react-native link didn't add the package in MainApplication.java file.
> 
> added and worked!
> 
> ```
> import com.bugsnag.BugsnagReactNative;
> 
>     @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>           //... other packages here.
>           BugsnagReactNative.getPackage(),
> 
>       );
>     }
>   };
> ```

Hi I think in your case you could try the manual link: https://docs.bugsnag.com/platforms/react-native/manual-linking-guide/

**Comment by TylerPin** [comment]
`apply plugin: "com.android.application"
apply plugin: 'com.bugsnag.android.gradle'`

for me i need to add the apply plugin line at the top of app/build.gradle file
