### ISSUE TITLE
IOS release version crash

### ISSUE THREAD

**Issue by ahmedjamshedlead** [bugsnag/bugsnag-react-native#421]
### Description
Crash on Launch IOS release on some devices

### Issue
reason: 'Exception 'threading violation: expected the main thread' was thrown while invoking startWithOptions on target BugsnagReactNative with params (
        {
        apiKey = 8153...
        }

### Environment

Library versions:
   "bugsnag-react-native": "2.21.0",

```shell

```

- cocoapods version (if any) (`pod -v`): 1.5.3
- iOS/Android version(s): Ios
- simulator/emulator or physical device?: physical
- debug mode or production?: production

- [x] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [x] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### CodeSnippet

const config = new Configuration('My_key')
config.codeBundleId = '3.2.01'
export const bugsnag = new Client(config)

**Comment by mattdyoung** [comment]
I believe this fix which has already been released should resolve the issue:
https://github.com/bugsnag/bugsnag-cocoa/pull/409

Can you confirm whether this is reproducible in the latest version before we investigate further?
[v2.23.2](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.2)

**Comment by ahmedjamshedlead** [comment]
@mattdyoung I had to start it on the native side but I am not getting any event as I called the start with new configuration on js side too with same api key but codebundleid Is extra there and now I am using the latest release.

**Comment by mattdyoung** [comment]
Hi @ahmedjamshedlead 

Can you share all the code you're using to initialize Bugsnag in JS and native code so we can see what might be wrong? It may be better to email to support@bugsnag.com if you'd prefer not to share the code here.

**Comment by mattdyoung** [comment]
@ahmedjamshedlead 
Closing this as we haven't had a response (unless you've contacted support and we didn't realise it was you!).

Please contact Bugsnag support if you're still having issues.
