### ISSUE TITLE
registerBeforeSendCallback doesn't respect an AsyncFunction object

### ISSUE THREAD

**Issue by kennym** [bugsnag/bugsnag-react-native#422]
### Description

```
      BugsnagConfiguration.registerBeforeSendCallback(async(report, error) => {
         return false
      }
```

This will run, and return false, but not cause the send to be prevented.

### Environment

- cocoapods version (if any) (`pod -v`): 1.7.5
- iOS/Android version(s): 13
- simulator/emulator or physical device?: simulator
- debug mode or production?: debug

- [X] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?

**Comment by mattdyoung** [comment]
Hi @kennym 

Calling registerBeforeSendCallback with an async function is not currently supported. It should work if you remove `async`.

We are currently working on a significant rework of our React Native error reporting library though which will then re-use our Universal JS bugsnag-js library for the Javascript layer. As the Universal JS error reporting library does support async beforeSend functions, this will then allow it on React Native as well.

So this should be possible after the next major release.
