### ISSUE TITLE
Unable to strip library 'libbugsnag-ndk.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.

### ISSUE THREAD

**Issue by sebqq** [bugsnag/bugsnag-react-native#425]
Hello I'm having problem with release build on Android. It keeps yelling following warning:

```
> Task :app:transformNativeLibsWithStripDebugSymbolForRelease
Unable to strip library '/Users/trebunak/Dev/ecc/ecc-camping-fuehrer-ng/android/app/build/intermediates/transforms/mergeJniLibs/release/
0/lib/armeabi/libbugsnag-ndk.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.
Unable to strip library '/Users/trebunak/Dev/ecc/ecc-camping-fuehrer-ng/android/app/build/intermediates/transforms/mergeJniLibs/release/
0/lib/armeabi/libbugsnag-plugin-android-anr.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.
```

I was wondering if it could be cause by proguard feature, which I have enabled in my android config. Is anybody experiencing something similar? 

Thank you so much!

**Comment by mattdyoung** [comment]
Hi @sebinq 

This warning is related to the removal of support for armeabi in recent versions of NDK.

You can safely ignore the warning, but we'll look into whether we can prevent this while still supporting older versions of NDK and armeabi for customers that use these.

Thanks!

**Comment by antoinerousseau** [comment]
Hi, any update on this?

**Comment by xander-jones** [comment]
Hey @antoinerousseau, the update for this has been made and released in v5.0.0 of our bugsnag-android notifier: https://github.com/bugsnag/bugsnag-android/pull/825

The Android underlying notifier has not yet been updated in our RN notifier though. It's coming!

**Comment by icemancast** [comment]
Has it been released yet?

**Comment by johnkiely1** [comment]
Hi @icemancast 

The RN notifier has not yet been released, we are still working on it. It has been held up somewhat due to delays in the iOS notifier which it also relies on. The iOS notifier update, which is expected imminently, is the last piece of the puzzle stopping the RN notifier being updated. We don't have definite dates for it yet but it will be soon.

**Comment by cristianoccazinsp** [comment]
I have started to get this warning recently after upgrading the NDK version so other libraries do not complain. Now this one is getting the warnings. Looking forward to the update.

**Comment by johnkiely1** [comment]
The new version of the React Native Bugsnag Library has now been released. The React Native library has moved and is now included in [bugsnag-js](https://github.com/bugsnag/bugsnag-js). Versions v7.3 and later make use of the v5 version of bugsnag-android which will include the changes made to address this issue.  [v7.3.3](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.3) is currently the latest available.
