### ISSUE TITLE
Unable to find 'React/RCTBridgeModule.h' file not found in Bugsnag

### ISSUE THREAD

**Issue by nihp** [bugsnag/bugsnag-react-native#426]
I am getting this error after upgrading the react-native version to latest

`/Applications/Helloworld/ios/Pods/Headers/Public/BugsnagReactNative/BugsnagReactNative.h:3:9: 'React/RCTBridgeModule.h' file not found`

**Comment by mattdyoung** [comment]
Hi @nihp 

Which version of react-native were you upgrading from and to?

Have you run `pod install`?
https://docs.bugsnag.com/platforms/react-native/react-native/#react-native-0-60

**Comment by nihp** [comment]
Upgrading from 0.58.6 to 0.61.5


Yes, I have run pod install

**Comment by mattdyoung** [comment]
I haven't been able to find any issue with using the latest bugsnag-react-native v2.32.2 with React Native 0.61.5.

Running the following steps to initialize a new React Native project and integrate Bugsnag works successfully and doesn't exhibit the error you describe:
```
$ react-native init example --version react-native@0.61.5
$ cd example
$ npm install bugsnag-react-native --save
$ cd ios/ && pod install
$ cd ..
```
Add the following lines to `index.js`:
```
import { Client } from 'bugsnag-react-native';
const bugsnag = new Client('YOUR-API-KEY-HERE');
```
```
$ npx react-native run-ios
```

I suspect the error is caused by a more generic issue with the upgrade procedure from 0.58.6 to 0.61.5 and may have nothing to do with Bugsnag. Can you share the steps you used to upgrade so I can try starting from an older version and try to reproduce what you're seeing?

**Comment by nihp** [comment]
I did not create new project, I tried with my existing old project

```
1. rm -rf node_modules (here I removed rnpm and chnaged the script as per react-upgrader in package.json file
2. npm install
3. run pod install(installed pods)
4. react-native run-ios (shows error need to unlink packages)
5. unlink all packages (now my pod file is empty)
6. Again i run pod install
7. It removed React, ImagePicker packages
8. Now the product ==>Edit scheme for react is missing (There is no list of third party packages in Manage schemes)
9. Then I remove Pods and Podfile.lock (now the podfile not have any packages in its target)
10. I did clean which you mentioned above
11. Again pod install
12. It only added the Frameworks which I added above for Crashlytics and Fabric
13.Then I have reverted the Pod file and run pod install. Again it added all packages and still the issue is there.
```
Can you tell how the podfile will show the packages inside target after an upgrade and how it will add in Product --> Edit scheme

**Comment by nihp** [comment]
I am getting like this after removing podfile.lock and run pod install

```
Detected React Native module pods for BVLinearGradient, RNFS, RNGestureHandler, RNImageCropPicker, RNImageRotate, react-native-cookies, react-native-image-picker, react-native-orientation, react-native-webview, and rn-fetch-blob
Analyzing dependencies
[!] No podspec found for `BugsnagReactNative` in `../node_modules/bugsnag-react-native`

[!] use_native_modules! skipped the react-native dependency 'react-native-cookie'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
```

**Comment by nihp** [comment]
@mattdyoung Did you have any update. I am trying to upgrade from 0.58.6 to 0.60 still getting same issue

**Comment by nihp** [comment]
@mattdyoung I created and checked with the another example project. These are my observations with my upgraded and example project

Before the upgrade the Header Seach path is like '(SRCTRoot/../..anypackages) same will be there after upgrade or not?

Because I have generated a new example project to check this. But I can see the difference in the Header search paths "${PODS_ROOT}/Headers/Public/BugsnagReactNative".

Also, I am facing RCTBridgeDelegate.h file and other files with extensions are not found while compiling my upgraded project.

But the example project is working fine. Can anyone suggest how can I isolate and build my existing upgraded app without a runtime error?

Note: Example app has third party packages in podfile but the existing project removed all third party packages while running react-native unlink command.

**Comment by mattdyoung** [comment]
@nihp 
I've been trying to reproduce the issue by creating an example project on 0.58.6 and upgrading to 0.60.0. I'm hitting a few issues with the `react-native upgrade` tool which I'm working through but haven't yet been able to reproduce the issue you reported.

0.60.0 and later versions of React Native use Cocoapods and autolinking so as you've found, you'll need to unlink Bugsnag: `react-native unlink bugsnag-react-native`

I assume you're opening the `xcworkspace` when building in XCode, not the `xcodeproj`?

Are you able to share your `Podfile` in case anything there is key to reproducing the issue?

**Comment by nihp** [comment]
Can you confirm how your header search path is like before and after upgrading.

**My Podfile Before upgrading**

```
# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'Fabric'
pod 'Crashlytics'

target 'App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for App

  target 'App-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
    #pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'
    #pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'RNImageRotate', :path => '../node_modules/react-native-image-rotate'

    pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

    pod 'RNFS', :path => '../node_modules/react-native-fs'

    pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

  end
```

**My Podfile after upgraing**

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'Fabric'
pod 'Crashlytics'

target 'App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   #use_frameworks!

  # Pods for App

  target 'App-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'Apptests' do
    inherit! :search_paths
    # Pods for testing
    use_native_modules!
  end

end
```

**Comment by nihp** [comment]
What are the steps needs to added in AppDelegate.m and runscripts

**Comment by mattdyoung** [comment]
Hi @nihp 

Regarding header search paths these are the same for me on 0.58.6 and after upgrading to 0.60.0:
```
HEADER_SEARCH_PATHS = (
        "$(inherited)",
        "$(SRCROOT)/../node_modules/bugsnag-react-native/cocoa/**",
);
```

I think the issue relates to the updates the React Native upgrader has made to your `Podfile` (and possibly other aspects of your project).

React Native 0.58.6 didn't have Cocoapods enabled by default (this was introduced in 0.60.0), whereas you were already using Cocoapods and it looks like the upgrade hasn't done the right thing.

I tried creating a plain example project on 0.58.6 and upgrading to 0.60.0 which resulted in the following `Podfile`:
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'example' do
  # Pods for RnDiffApp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'example-tvOS' do
  # Pods for example-tvOS

  target 'example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

So the issue looks to be caused by your `Podfile` not including the React Native dependencies.

This issue isn't caused by Bugsnag so there's nothing we could "fix" in bugsnag-react-native to resolve this.

I'd advise using the React Native upgrade helper to assist with determining what changes should have been made:
https://react-native-community.github.io/upgrade-helper/

Can you direct any further general questions on usage of bugsnag-react-native to support@bugsnag.com as the github issues are intended for reports of suspected bugs in the SDK.
