### ISSUE TITLE
Error on types definitions

### ISSUE THREAD

**Issue by neiker** [bugsnag/bugsnag-react-native#428]
On `index.d.ts`, `BeforeSend` is defined as `(report: Report) => boolean | void;` but in fact it receives 2 arguments.
Correct signature: 
`(report: Report, error: Error) => boolean | undefined;`

**Comment by mattdyoung** [comment]
@neiker 

Thanks for raising this, we'll look at fixing it in a future release.

**Comment by mattdyoung** [comment]
Fixed in [v2.23.6](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.6)
