### ISSUE TITLE
All headerfiles of React has been moved React/*** in 0.40

### ISSUE THREAD

**Issue by ptomasroos** [bugsnag/bugsnag-react-native#43]
This needs to be upgraded in order to let users continue to use the plugin when the release is out at 1 of January according to release schedule.

A release candidate is already available.

**Comment by kattrali** [comment]
Thanks for the heads up, @ptomasroos.

**Comment by henrikra** [comment]
Here is PR for that https://github.com/bugsnag/bugsnag-react-native/pull/60

**Comment by kattrali** [comment]
Fixed via #60. Thanks @henrikra!
