### ISSUE TITLE
Sourcemap uploaded but cant manage to make it for production and development

### ISSUE THREAD

**Issue by Zilleabbas10** [bugsnag/bugsnag-react-native#435]
I have intiliaze bugsnag in index.js with following configurations:

```
import { Client, Configuration } from 'bugsnag-react-native'

const configuration = new Configuration();

// change notifyReleaseStages to production for live build.
configuration.releaseStage = 'production';
configuration.notifyReleaseStages= ['production'];
configuration.apiKey =apiKey;

let bugsnag;
bugsnag = new Client(configuration);
```

after this i created android-debug.bundle and android-debug.bundle.map with following commands:

>  react-native bundle \
>     --platform android \
>     --dev false \
>     --entry-file index.js \
>     --bundle-output android-release.bundle \
>     --sourcemap-output android-release.bundle.map

when source map is created i uploaded it to bugsnag with following command

> curl --http1.1 https://upload.bugsnag.com/react-native-source-map \
>    -F apiKey=YOUR_API_KEY_HERE \
>    -F appVersion=1.2.3 \
>    -F dev=false \
>    -F platform=android \
>    -F sourceMap=@android-release.bundle.map \
>    -F bundle=@android-release.bundle \
>    -F projectRoot=`pwd`

the source map is uploaded fine on bugsnag as you can see in the screenshot

![image](https://user-images.githubusercontent.com/26869707/71503545-6f422500-2897-11ea-9383-413551e54c96.png)

Here is the issue, I dont know if i am missing any configuration or something but don't know how to make it available for production for testing so it come here

![image](https://user-images.githubusercontent.com/26869707/71503599-b0d2d000-2897-11ea-901a-52b4aded0b91.png)

please help, thanks in advance

**Comment by mattdyoung** [comment]
Hi @Zilleabbas10 

I can't see anything obviously wrong with what you've tried but the most common reasons for source maps not being applied are described here:
https://docs.bugsnag.com/api/rn-source-map-upload/#frequently-asked-questions

If this still isn't working for you can you contact support@bugsnag.com with a link to an error in your Bugsnag dashboard where you think the source map should have been applied and we can confirm what's not configured correctly.

Thanks!
