### ISSUE TITLE
RN 0.60 does not build for iOS giving error unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag') using cocoapods 

### ISSUE THREAD

**Issue by Rutvik17** [bugsnag/bugsnag-react-native#439]
### Description

RN 0.60 does not build for iOS giving error unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag') using cocoapods 
### Issue

I updated my project from 0.59.10 to 0.60.6 and now i can not build my project. I installed bugsnag using pods install for ios but it throws error on build.
`unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag')`
### Environment
Library versions:

```shell
react-native: 0.60.6
bugsnag-react-native: ^2.23.2
```

- cocoapods version (if any) (`pod -v`): 1.8.4
- iOS/Android version(s): iOS 
- simulator/emulator or physical device?: both
- debug mode or production?: debug

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

**Comment by tomlongridge** [comment]
@Rutvik17 - please try with the latest version of bugsnag-react-native (2.23.5) which fixes #433 - it sounds very similar to the error you are seeing.

**Comment by Rutvik17** [comment]
> @Rutvik17 - please try with the latest version of bugsnag-react-native (2.23.5) which fixes #433 - it sounds very similar to the error you are seeing.

The latest version has this issue. version 2.23.2 does not have this issue. I am at version 2.23.2  and it solved my problem.

**Comment by mattdyoung** [comment]
Hi @Rutvik17 

Can we just clarify whether you re-tried this with [v2.23.5](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.5) which was released yesterday?

**Comment by Rutvik17** [comment]
> Hi @Rutvik17
> 
> Can we just clarify whether you re-tried this with [v2.23.5](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.5) which was released yesterday?

No i haven't retried with that but it works with my current version so i will keep it there for now.

**Comment by mattdyoung** [comment]
Believed fixed by https://github.com/bugsnag/bugsnag-react-native/issues/433 in [v2.23.5](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.5)
