### ISSUE TITLE
props not registered with breadcrumbs

### ISSUE THREAD

**Issue by Bickson** [bugsnag/bugsnag-react-native#44]
Cant seem to get component props to register with breadcrumbs.

```
componentWillReceiveProps (newProps) {
    this.props.bugsnagClient.leaveBreadcrumb('New Props to MyComponent', {
      type: 'process',
      props: newProps.data,
      component: '<MyComponent/>'
    })
  }
```

```
componentWillMount () {
    this.props.bugsnagClient.leaveBreadcrumb('Load MyComponent', {
      type: 'navigation',
      props: this.props.data,
      component: '<MyComponent />'
    })
  }
```
Anyone else experience this issue ?

**Comment by kattrali** [comment]
Thanks for the report, @Bickson. What is the error message encountered, and can you provide a general idea of what the `newProps` structure would be?

**Comment by the-simian** [comment]
@Bickson is this a repeat of this issue : https://github.com/bugsnag/bugsnag-react-native/issues/36 ?

I suspected the implemented fix might not be handling nested objects.

**Comment by kattrali** [comment]
@the-simian That was my suspicion as well, though I didn’t want to assume.

**Comment by Bickson** [comment]
I don't remember getting a warning, but i will try again and report back shortly.
Thank you!

**Comment by kattrali** [comment]
Feel free to reopen if the issue recurs. Thanks again!
