### ISSUE TITLE
 App crashes on 4.4

### ISSUE THREAD

**Issue by mhusnain030** [bugsnag/bugsnag-react-native#444]
### Description
App crashes on android 4.4

### Issue
App is crashing with bugsnap.

### Environment
Android version 4.4
bugsnag version 2.23.5

### Reference Issue
App crashes on android 4.4.2 #199

**Comment by phillipsam** [comment]
Hi @mhusnain030 - thanks for the report. As asked on the previous ticket #199, can you please share the dependencies you're using in your build.gradle file and package.json, along with your buildToolsVersion, compileSdkVersion, minSdkVersion, and targetSdkVersion?

**Comment by mattdyoung** [comment]
Closing as we haven't had a response but if you're still seeing the issue please provide the details so we can try to reproduce.
