### ISSUE TITLE
`Client.notify()` docs seem inaccurate.

### ISSUE THREAD

**Issue by jarod-legault** [bugsnag/bugsnag-react-native#447]
### Description
I am trying to create a Bugsnag report in a React Native project with extra data (metadata).

### Issue
I followed [the Bugsnag docs](https://docs.bugsnag.com/platforms/javascript/reporting-handled-errors/#customizing-diagnostic-data) and tried both methods under "Customizing Diagnostic Data": 

```js
// Sending a metaData property in opts
bugsnagClient.notify(new Error('Something broke!'), {
  metaData: {
    'special info': {
      request_id: 12345,
      message_id: 854
    }
  }
})
```

```js
// Adding metaData via report methods
bugsnagClient.notify(new Error('Something broke!'), {
  beforeSend: (report) => {
    report.updateMetaData('special info', {
      request_id: 12345,
      message_id: 854
    })
  }
})
```

and I was getting this error:

```
TypeError n is not a function. (In 'n(f)', 'n' is an instance of Object) 
    node_modules/bugsnag-react-native/lib/Bugsnag.js:107:19 
    node_modules/regenerator-runtime/runtime.js:62:44 tryCatch
    node_modules/regenerator-runtime/runtime.js:296:30 
    node_modules/regenerator-runtime/runtime.js:62:44 tryCatch
    node_modules/regenerator-runtime/runtime.js:152:28 invoke
    node_modules/regenerator-runtime/runtime.js:195:17 
    node_modules/promise/setimmediate/core.js:45:7 tryCallTwo
    node_modules/promise/setimmediate/core.js:200:23 doResolve
    node_modules/promise/setimmediate/core.js:66:12 Promise
    node_modules/regenerator-runtime/runtime.js:194:27 callInvokeWithMethodAndArg
    node_modules/regenerator-runtime/runtime.js:217:12 _invoke
    node_modules/regenerator-runtime/runtime.js:241:13 async
    node_modules/bugsnag-react-native/lib/Bugsnag.js:86:177 notify
    ...
```

When I check the `index.d.ts` file in the Bugsnag directory, I see that the second parameter in the `notify` method is `beforeSendCallback` (not `opts` as the docs say). I also see that there is no `report.updateMetaData` method, but there is a `report.addMetadata` method. Based on what I found in `index.d.ts`, I was able to get my code working this way:

```js
bugsnagClient.notify( new Error( errorTitle ), report => {
   report.addMetadata( "error info", "errorData", errorData );
} );
```

Are the docs inaccurate? Or am I not understanding how to use the `notify` method properly?

### Environment

Library versions:

```shell
├── bugsnag-react-native@2.23.6 
├── UNMET PEER DEPENDENCY react-native@0.59.10 
└── react-native-code-push@5.5.3 
```

- cocoapods version (if any) (`pod -v`): N/A
- iOS/Android version(s): Android 8.1.0
- simulator/emulator or physical device?: physical device
- debug mode or production?: production

### Example code snippet

```js
bugsnagClient.notify( new Error( errorTitle ), {
      metaData: {
        "error info": {
          error:      error,
          errorTitle: errorTitle,
          errorData:  errorData
        }
      }
    } );
```

<details><summary>Error messages:</summary>

```
TypeError n is not a function. (In 'n(f)', 'n' is an instance of Object) 
    node_modules/bugsnag-react-native/lib/Bugsnag.js:107:19 
    node_modules/regenerator-runtime/runtime.js:62:44 tryCatch
    node_modules/regenerator-runtime/runtime.js:296:30 
    node_modules/regenerator-runtime/runtime.js:62:44 tryCatch
    node_modules/regenerator-runtime/runtime.js:152:28 invoke
    node_modules/regenerator-runtime/runtime.js:195:17 
    node_modules/promise/setimmediate/core.js:45:7 tryCallTwo
    node_modules/promise/setimmediate/core.js:200:23 doResolve
    node_modules/promise/setimmediate/core.js:66:12 Promise
    node_modules/regenerator-runtime/runtime.js:194:27 callInvokeWithMethodAndArg
    node_modules/regenerator-runtime/runtime.js:217:12 _invoke
    node_modules/regenerator-runtime/runtime.js:241:13 async
    node_modules/bugsnag-react-native/lib/Bugsnag.js:86:177 notify
```
</details>

**Comment by jcurlier** [comment]
+1

**Comment by phillipsam** [comment]
Hi @jarod-legault , @jcurlier 

We have separate documentation for React Native and Javascript. The link to the documentation and examples above are from our Javascript docs.

Information for adding diagnostic data in React Native is available here:
https://docs.bugsnag.com/platforms/react-native/react-native/#sending-diagnostic-data

The example looks like this:
```
bugsnag.notify(error, function(report) {
  report.metadata = { "account": {
    "company": "Acme Co",
    "id": 123
    }
  }
});
```

Additional information on customising error reports for React Native is available here:
https://docs.bugsnag.com/platforms/react-native/react-native/customizing-error-reports/#adding-custom-diagnostics

With this as an example:
```
bugsnag.notify(error, (report) => {
  report.metadata.account = {"name": "Acme Co."};
});
```

**Comment by jarod-legault** [comment]
> Hi @jarod-legault , @jcurlier
> 
> We have separate documentation for React Native and Javascript. The link to the documentation and examples above are from our Javascript docs.
> 
> Information for adding diagnostic data in React Native is available here:
> https://docs.bugsnag.com/platforms/react-native/react-native/#sending-diagnostic-data
> 
> The example looks like this:
> 
> ```
> bugsnag.notify(error, function(report) {
>   report.metadata = { "account": {
>     "company": "Acme Co",
>     "id": 123
>     }
>   }
> });
> ```
> 
> Additional information on customising error reports for React Native is available here:
> https://docs.bugsnag.com/platforms/react-native/react-native/customizing-error-reports/#adding-custom-diagnostics
> 
> With this as an example:
> 
> ```
> bugsnag.notify(error, (report) => {
>   report.metadata.account = {"name": "Acme Co."};
> });
> ```

Wow, I can't believe I missed that. Thanks so much, @phillipsam!
