### ISSUE TITLE
Support cocoapod import

### ISSUE THREAD

**Issue by ptomasroos** [bugsnag/bugsnag-react-native#45]
Many RN projects are handling their dependencies through Podfile in order to skip a lot of the manual integrations steps.

This is almost enabled by every IOS RN library out there.

Would be great to be able to add one to bugsnag-react-native as well.

Had something like this in mind. Haven't got it up and running yet thought as I'm not too knowledgeable what should be imported in kscrash either?

Another alternative is to make the library use cocoapods as well instead of vendoring. But that requires all RN projects to use cocoapods which might not be wishful.

```
require "json"
package = JSON.parse(File.read('package.json'))

Pod::Spec.new do |s|
  s.name          = package['name']
  s.version       = package['version']
  s.summary       = package['description']
  s.author        = "Bugsnag"
  s.license       = package['license']
  s.requires_arc  = true
  s.homepage      = "https://github.com/bugsnag/bugsnag-react-native"
  s.source        = { :git => 'https://github.com/bugsnag/bugsnag-react-native.git' }
  s.platform      = :ios, '6.0'
  s.libraries     = 'z'
  s.source_files  =
    "cocoa/vendor/kscrash/Source/KSCrash/**/*.{h,m}",
    "cocoa/vendor/bugsnag-cocoa/Source/*.{h,m}",
    "cocoa/*.{h,m}"

end
```

**Comment by kattrali** [comment]
Thanks for the report, @ptomasroos. Currently, the installation process doesn’t require any manual steps in Xcode or vendoring. The required files are bundled into the project (including the bugsnag-cocoa library and the required subspec of KSCrash). So installation like so should provide everything you need to get started:

1. `npm install bugsnag-react-native --save`
2. `react-native link`

Initially we handled iOS installation through either CocoaPods or vendoring, but unfortunately this led to more confusion rather than less since most users approaching React Native are not as familiar with CocoaPods and the iOS ecosystem. Though with that said, I may take another look at this process at another time if the current process proves prohibitive. There is already pods for bugsnag-cocoa and KSCrash, so it would be a matter of:

* Packaging source files `BugsnagReactNative.{h,m}`
* Adding a resource for `Bugsnag.js`
* Linking against the React Native headers

**Comment by ptomasroos** [comment]
Take our app for instance
85% av all rn are being imported through podfiles rather than manual linking.

Looking at some facts

```
package name:                           downloads last month on npm
react-native-code-push                  30,514 
react-native-device-info                30,378
react-native-fbsdk                      16,616
react-native-fcm                        9,013
react-native-google-analytics-bridge    6,108
react-native-image-picker               23,933
react-native-linear-gradient            25,536



bugsnag-react-native                    2,585
```

Plus we're a paying customer of yours. I think it would be fair to provide a podspec. I dont say we need to go all the way to declare your dependencies through podfiles but at least make sure we who want to use podfiles to manage your builds do it by having a podspec?

**Comment by kattrali** [comment]
> 85% av all rn are being imported through podfiles rather than manual linking.

Interesting. I think we are having a bit of confusion over what "manual linking" means. I was referring to requiring any action in Xcode after installation. Did you mean something else?

**Comment by ptomasroos** [comment]
Is there a big problem just having a podspec? It would allow people to choose. 

Well rnpm adds manual rows to the project file in terms of header search path, special linking.

When you have multiple targets this gets to be a manual process to add this in build spyware but when using pods all of this stuff is already handled. Again a much superior technology.

**Comment by kattrali** [comment]
> Is there a big problem just having a podspec? It would allow people to choose.

Well, it is always an issue of better understanding the problem, and ensuring we can support people effectively when they have questions. There is a large amount of experience diversity when it comes to React Native projects in particular, where we have people coming from iOS, Android, or client-side JavaScript backgrounds, and an approach to handling that is to ensure there is a “golden path” when it comes to using the library. Thus far, the most reliable approach has been to minimize Xcode usage and the number of commands run. That is why I am hesitant to add (and officially support) CocoaPods installation separately, as it as a dimension to the process, documentation, and types of ways integration can go wrong.

> When you have multiple targets this gets to be a manual process to add this in build spyware but when using pods all of this stuff is already handled.

That makes sense. Thus far, `react-native link` has not proven particularly robust when handling multiple targets. I’ve made a draft of what a podspec would need to contain to include the dependencies, though it would need further testing. Perhaps you could give it a try: https://github.com/bugsnag/bugsnag-react-native/commit/a097d836c7df0117c525126712bf2032b7f5bf27 ?

**Comment by ptomasroos** [comment]
Thanks @kattrali Will test it today!

**Comment by skv-headless** [comment]
@kattrali just tested https://github.com/bugsnag/bugsnag-react-native/commit/a097d836c7df0117c525126712bf2032b7f5bf27. Working fine. Thanks.

**Comment by kattrali** [comment]
Awesome, thanks @skv-headless.

**Comment by ptomasroos** [comment]
Thanks for the work to get podspec working @kattrali !
