### ISSUE TITLE
New version utilising new JS and Android versions?

### ISSUE THREAD

**Issue by henrymoulton** [bugsnag/bugsnag-react-native#457]
Is this library going to make use of the new JS and Android libraries?

https://updates.bugsnag.com/major-versions-of-android-and-universal-javascript-notifiers-148041

**Comment by xander-jones** [comment]
It is indeed. Additionally, we've got a cocoa update to come too! This was a huge driver for the rewrite of the libraries, so that we can bring them all together and make them work in the same way.

**Comment by henrymoulton** [comment]
Thanks @xander-jones , any estimate for when these updates might land in NPM?

**Comment by mattdyoung** [comment]
@henrymoulton 
We don't have a firm ETA but this is actively being worked on and we hope to make this available in the next few weeks.
