### ISSUE TITLE
the uploaded source map not getting applied

### ISSUE THREAD

**Issue by praveenp-od** [bugsnag/bugsnag-react-native#458]
Hi Team,

I have verified the issue mentioned here https://docs.bugsnag.com/api/rn-source-map-upload/#why-isn-39-t-the-uploaded-source-map-getting-applied-to-my-error

But still i'm facing the Same issue.

**Comment by mattdyoung** [comment]
Hi @praveenp-od 

Can you write in to support@bugsnag.com with a link to an example of an error in your Bugsnag dashboard where the source map hasn't applied and we can advise on the specifics of what isn't configured correctly.

Thanks!
