### ISSUE TITLE
bugsnag-react-native does not support bugsnag-cocoa 6.0

### ISSUE THREAD

**Issue by bolsinga** [bugsnag/bugsnag-react-native#465]
### Description
As you know, bugsnag-cocoa has updated to v6.0. bugsnag-react-native still uses v5.23.9

**Describe the solution you'd like**
A bugsnag-react-native release that supports bugsnag-cocoa v6.0

**Describe alternatives you've considered**
n/a

**Additional context**
We want to be able to leverage all the work in bugsnag-cocoa v6.0 very soon.

**Comment by phillipsam** [comment]
Hi @bolsinga thanks for reaching out! 

We are indeed looking to update our `bugsnag-react-native` notifier to use `bugsnag-cocoa` v6. We don't have a firm ETA for release, but it is likely to be of the order of a few weeks.

**Comment by bolsinga** [comment]
Thanks @phillipsam Is there a in progress branch integrating v6 that I may use to fix our use of the breaking changes in v6?

**Comment by phillipsam** [comment]
Hi @bolsinga unfortunately there is not a branch for this yet. We are planning to include the refresh of the RN notifier in bugsnag-js, so we would recommend holding off any implementation on this until this is released.

**Comment by phillipsam** [comment]
Hi @bolsinga - we have now released a new version of the bugsnag-js notifier which contains our brand new notifier for React Native. We recommend using the latest version: [v7.3.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.1).

**Comment by bolsinga** [comment]
When will the bugsnag-cocoa changes be in bugsnag-react-native? Is bugsnag-js a replacement for bugsnag-react-native? Thanks

**Comment by phillipsam** [comment]
We have unified the bugsnag-react-native and bugsnag-js codebases, resulting in a new major version of bugsnag-js (v7.3.0) that supports React Native as well as browser JS and Node. This major version has also pulled in the latest major versions of bugsnag-android and bugsnag-cocoa.
