### ISSUE TITLE
Cycle in dependencies between targets 'BugsnagReactNative' and 'FBSDKCoreKit';

### ISSUE THREAD

**Issue by CoSNaYe** [bugsnag/bugsnag-react-native#470]
### Description
While running `react-native run-ios`, it pops the error:
```
error: Cycle in dependencies between targets 'BugsnagReactNative' and 'FBSDKCoreKit'; building could produce unreliable results
```

And this error even stops Xcode from building. 
![image](https://user-images.githubusercontent.com/11452327/87882068-27037380-ca30-11ea-8b3b-a7ec0d355217.png)

### Environment

Library versions:
```
├─ bugsnag-react-native@2.23.10
└─ react-native@0.62.2
```

- cocoapods version (if any) (`pod --version`): 1.9.3
- iOS/Android version(s): iOS 11.0, Xcode: 11.5
- simulator/emulator or physical device?: simulator
- debug mode or production?: debug mode

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?

```
The integration guide seems doesn't mention `[BugsnagReactNative start]` ?
```

- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

**Comment by mattdyoung** [comment]
Hi @CoSNaYe 

I'm not able to reproduce this. I've tried a clean React Native 0.62.2 project and installed `bugsnag-react-native` and `react-native-fbsdk`:
```
$ npx react-native init MyProject --version 0.62.2
$ cd MyProject
$ npm install bugsnag-react-native --save
$ npm install react-native-fbsdk --save
$ cd ios/ & pod install
```

And followed the integration instructions and run up the app without issue:
https://docs.bugsnag.com/platforms/react-native/react-native/
https://docs.bugsnag.com/platforms/react-native/react-native/enhanced-native-integration
```
$ npx react-native run-ios
```

Does the issue persist if you perform a clean build?

Are you able to share a reproduction example project?

**Comment by phillipsam** [comment]
Hi @CoSNaYe - closing this for now as we have not heard back. Feel free to comment below or reach out to support@bugsnag.com and we can reopen this issue.
