### ISSUE TITLE
Files that shouldn't be in your npm package

### ISSUE THREAD

**Issue by halaei** [bugsnag/bugsnag-react-native#472]
### Description
After installing bugsnag-react-native, there are some files in node_modules/bugsnag-react-native that really shouldn't be there.

### Issue
Example of files and directories that should be removed:
```
android/.idea
android/local.properties (contains your local paths like ndk.dir=/Users/jamielynch/Library/Android/sdk/ndk-bundle)
```

### Environment

Library versions:

```shell
├─ bugsnag-react-native@2.23.10
└─ react-native@0.63.2
```

- cocoapods version (if any) (`pod --version`):
- iOS/Android version(s):
- simulator/emulator or physical device?:
- debug mode or production?:

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example Repo

- [ ] Create a minimal repository that can reproduce the issue after running
  `yarn install` and `react-native run-ios`/`react-native run-android`
- [ ] Link to it here:

### Example code snippet

```js
import { Client, Configuration } from 'bugsnag-react-native';

// (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by xander-jones** [comment]
Hi @halaei, we've just released an update to the React Native notifier which cleans up this issue. It now lives in the [`bugsnag-js`](https://github.com/bugsnag/bugsnag-js) monorepo, so the first new version of the React Native notifier is [v7.3.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.0). Please note that this is a pretty major upgrade for this notifier, so you'll want to check out the [UPGRADING.md](https://github.com/bugsnag/bugsnag-js/blob/v7.3.0/packages/react-native/UPGRADING.md) file, as well as the [docs](https://docs.bugsnag.com/platforms/react-native/react-native/). Closing the issue out as it's been resolved, but please let us know if you have any other comments!
