### ISSUE TITLE
Errors reported/displayed differently when sent from iOS and Android

### ISSUE THREAD

**Issue by Looveh** [bugsnag/bugsnag-react-native#48]
Sending the same error on iOS and Android respectively produces two separate errors in the interface, but grouped per platform.

Report object sent with error seems to be the same on both platforms though.

Top one is iOS and bottom Android, the error message doesn't seem to be included in the header on Android.

![image](https://cloud.githubusercontent.com/assets/1567752/21358911/9f1a5864-c6da-11e6-8c8d-82a872e388a9.png)

**Comment by kattrali** [comment]
Thanks for the report, @Looveh. I think this is an issue we’ll need to look into on the server side.

**Comment by Looveh** [comment]
@kattrali All right, should this issue be moved to another project or will you handle it internally? :)

**Comment by duncanhewett** [comment]
@Looveh Please could you contact support@bugsnag.com with a link to the errors in your screenshot on your dashboard so we can take a look (and mention this issue as well). Thanks!

**Comment by kattrali** [comment]
Closing this for the product support thread. :)
