### ISSUE TITLE
Bugsnag Android Dependency Update

### ISSUE THREAD

**Issue by rkavalap** [bugsnag/bugsnag-react-native#480]
### Description
React native bugsnag plugin which depends on the bugsnag android dependency is still under version 4.x
Latest bugsnag android version is v5.x 
https://github.com/bugsnag/bugsnag-react-native/blob/2f0ccd93a8249a3be163380b657801b2c6575327/android/build.gradle#L39

While this is a breaking change. Do we have a timeline when this can be expected with a version bump and docs updated ?

**Comment by steve-nester-uk** [comment]
@rkavalap per the [deprecation-notice](https://github.com/bugsnag/bugsnag-react-native#deprecation-notice), this client library has been moved into https://github.com/bugsnag/bugsnag-js.  The latest [docs](https://docs.bugsnag.com/platforms/react-native/react-native/) do now reflect this change.
