### ISSUE TITLE
Ability to set `errorClass` in new version?

### ISSUE THREAD

**Issue by cristianoccazinsp** [bugsnag/bugsnag-react-native#482]
We previously used custom error classes (with both `errorClass` and `groupingHash` on the notify/error callbacks) to nicely organize/label a few logs.  Now all errors seem to be labelled as "Error" and we are unable to customize its class.

Couldn't find anywhere in the documentation how to migrate this "breaking change".

Any help would be appreciated.

**Comment by cristianoccazinsp** [comment]
Figured it out afterwards...  For anyone wondering the same:

```
if(event.errors && event.errors.length){event.errors[0].errorClass = "Your Custom Class";}
```

**Comment by xander-jones** [comment]
Hey @cristianoccazinsp, thanks for letting us know you've found a solution for this. For future travellers too, the documentation on this can be found here: https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#errors
