### ISSUE TITLE
Usage with mocha

### ISSUE THREAD

**Issue by henrikra** [bugsnag/bugsnag-react-native#49]
This library works great when compiling and running it on device. Problems come when running test with mocha with components that are using this library.

The problem is that this library does not have dist version of it which would be in ES5. All code is in ES6 now and babel to my knowledge ignores node_modules by default. So that is my I am getting "Unexpected token import" from 2nd line of bugsnag-react-native library.

My question is that
1. isn't it normal that all npm packages have es5 (dist) version in the package so we shouldn't babelify node_modules. 
2. is my mocha configured wrong? 
3. is it normal that react native libraries are all written in es6? Notice that this problem is only when testing.

The way I have solved this for now is that I moved bugsnag library to my `src` folder and I require it there so then it will be compiled with babel.

Tell me if you need more information :)

Here is also my mocha.opts:
```
--compilers js:babel-core/register
--require react-native-mock/mock
--require babel-polyfill
--require test/setup.js
--reporter spec
--recursive
```

**Comment by kattrali** [comment]
Thanks for the report, @henrikra. Can you share your `.babelrc`? Maybe there is a configuration option which would help here.

**Comment by henrikra** [comment]
My `.babelrc` has basic conf: `{"presets": ["react-native"]}`
Another way we solved this was by ignoring `bugsnag-react-native` import when testing. Adding custom module loader to `setup.js`:
```javascript
require('react-native-mock/mock');
const m = require('module');

global.__DEV__ = true;
const originalLoader = m._load;

m._load = function hookedLoader(request, parent, isMain) {
  if (request === 'bugsnag-react-native') {
    return {};
  }
  return originalLoader(request, parent, isMain);
};
```

This will return empty object when `bugsnag-react-native` is being imported otherwise is loads modules as normal :)

**Comment by NicolasBonduel** [comment]
Hello guys, I'm having the same issue with Jest. I have the same .babelrc file as @henrikra 
We manually mocked bugsnag so we don't get the issue anymore:

`
let bugsnag = {
  leaveBreadcrumb: (message, metadata) => {
    console.log({message, ...metadata});
  }
};

if (envData.environment === ! 'DEV') {
  const bugSnagReact = require("bugsnag-react-native");
  const configuration = new bugSnagReact.Configuration("[...]");
  configuration.releaseStage = envData.environment;
  bugsnag = new bugSnagReact.Client(configuration);
}
`

@wordofchristian had the same issue here: #10

**Comment by john-farmer-candor** [comment]
I also ran into this problem with CircleCI. It's expecting es5 source and gets an error on the es6 import statement in node_modules/bugsnag-react-native/index.js.

I'll try working around it by testing for the circleci environment variables and not importing bugsnag for now.

**Comment by llaine** [comment]
Experiencing the same issue
