### ISSUE TITLE
How to unset user?

### ISSUE THREAD

**Issue by Andreyco** [bugsnag/bugsnag-react-native#50]
Setting user is easy...

I am experiencing issues with unsetting user (e.g when user logs out).
`setUser(null, null, null)` does not  work - further reports are completely without user (not event "dummy" one)

`setUser(undefined, undefined, undefined)` produces fatal error.
![screen](https://cloud.githubusercontent.com/assets/829963/21410843/16638620-c7e4-11e6-9d98-486aa34f5b40.png)

Having something like `unsetUser` would me great!

**Comment by kattrali** [comment]
Ah, thanks for the report, @Andreyco. This is actually an easy fix - just need to add a hook to the `clearUser` method in bugsnag-android, and the cocoa equivalent.

**Comment by Andreyco** [comment]
Thank you!
