### ISSUE TITLE
Improve source map docs

### ISSUE THREAD

**Issue by Andreyco** [bugsnag/bugsnag-react-native#57]
Trying to setup Bugsnag to show full stack traces, but I am stuck on source maps.
Docs are brief, not clear at all, eventually I need to know some magic behind your services to get things working.  

I have no problem to build a bundle with source map, but I fail on other side. Despite having source maps uploaded to your servers, I cannot see anything but bundled file.

Is there anything I could provide you in order to help

**Comment by Andreyco** [comment]
#35 is pretty much related. URL parsing is probably not working correctly on Android.

My findings are that bundle names are following:
- iOS: main.jsbundle
- Android: index.android.js

**Comment by bullmo** [comment]
@Andreyco The uploaded source maps get applied to an error report if the minifiedUrl in the upload matches the file/url in the stacktrace and the appVersion matches the app version or versionCode.

The [FAQ](https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#frequently-asked-questions) in the docs gives help on how to identify some common issues with applying source maps.

Please can you contact support@bugsnag.com with a link to an error that isn't showing the stacktrace correctly (and reference this issue) so we can investigate why it isn't working for you.

**Comment by bullmo** [comment]
I'm closing this in preference for assisting via support. We can update the docs if the findings are useful for others.

**Comment by keshavkaul** [comment]
@bullmo The docs aren't helpful. It's been over 10hrs of futile efforts to upload source maps. Having react-native support should ideally have this feature built in as most of the code being executed is in Javascript and not native. Please improve the docs and the library. Thanks!

**Comment by Twinski** [comment]
I agree with @keshavkaul. I'm struggling as well with setting up sourcemaps properly. Does it need the dSYM uploaded to Bugsnag or not? Or do we only need the sourcemap there? Nevertheless, I tried both and it's not working for development-mode. 

My setup:
React native app running on iOS.

Any help is appreciated! :)

**Comment by john1jan** [comment]
I am also facing the same issue. I use this command to upload source map 

`bugsnag-sourcemaps upload \
    --api-key MY_API_KEY \
    --app-version 3.1 \
    --minified-file index.android.bundle \
    --source-map index.android.sourcemap.js \
    --minified-url index.android.bundle \
    --upload-sources`

Even I can see my source map uploaded in Bugsnag

<img width="922" alt="screen shot 2018-02-14 at 8 15 49 pm" src="https://user-images.githubusercontent.com/4264813/36210237-eb703690-11c3-11e8-9728-a21697bca331.png">

But my error is still minified, check out the event details below

<img width="785" alt="screen shot 2018-02-14 at 8 16 59 pm" src="https://user-images.githubusercontent.com/4264813/36210352-3fce776a-11c4-11e8-90e9-4683ac72ba17.png">
![screen shot 2018-02-14 at 8 17 14 pm](https://user-images.githubusercontent.com/4264813/36210360-41503718-11c4-11e8-80f8-93c8cab9d8e1.png)

I have even checked all these things
* App version is matching with uploaded version
* Event is sent after uploaded source map
* --minified-file is matching the uploaded source map file name

Any help would be appreciated. Or I have to switch to some other error reporting tool.

**Comment by avinashwigroup** [comment]
Do we have an update on this?

**Comment by fractalwrench** [comment]
@avinashwigroup if you're encountering source map issues we'd recommend contacting support@bugsnag.com - if you think you've encountered a bug, then feel free to open a new GitHub issue and I'll take a look.

**Comment by mphasak** [comment]
Please do consider updating the docs with modern / clear info...  we've spent a lot of time ourselves on this, will be contacting support but it'd be nice if the docs were accurate.  Also the bugsnag-sourcemaps cli tool fails without giving any info as to why it failed 😕

**Comment by fabriziobertoglio1987** [comment]
yes, indeed I am experiencing the same issue and not capable of configuring source maps. I also can see my sourcemaps uploaded with the same version of package.json but the errors are minified

**Comment by abigail-bugsnag** [comment]
Hi @fabriziobertoglio1987 - thanks for reaching out!

It is worth noting that we released a separate API for use with React Native source maps which we'd recommend using, full instructions here:
https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#uploading-source-maps

It is important to use the [React Native source map upload API](https://docs.bugsnag.com/api/rn-source-map-upload/) and not the [Javascript source map upload API](https://docs.bugsnag.com/api/js-source-map-upload/)

Using the React Native source map upload API it will just match based on Android/iOS and release/debug variants so if you upload the correct source map variant with a matching `appVersion` / `appVersionCode`(Android) / `appBundleVersion`(iOS) / `codeBundleID` it should be applied to any new errors. Matching on `codeBundleID` takes precedence over application version.

If the version or `codeBundleID` does not match what is being reported in your error, then it will not be applied. You can check what is being uploaded in 'Settings > uploaded source maps' and your version and `codeBundleID` information should be visible on the 'APP' tab of your error.

If this information is all things that you are already doing, then please write into support@bugsnag.com and we will take a look at your account :)
