### ISSUE TITLE
Boolean values don't get logged in breadcrumbs [iOS]

### ISSUE THREAD

**Issue by cooperka** [bugsnag/bugsnag-react-native#59]
Even after the fixes in https://github.com/bugsnag/bugsnag-react-native/pull/56 (rebased on `v1.2.2`), boolean breadcrumb values show up as **blank** on crash reports for iOS. However, they work fine on Android.

Screenshot showing missing breadcrumb value:

![screenshot of missing breadcrumb](https://cloud.githubusercontent.com/assets/2047062/21775472/33ce982e-d664-11e6-93fa-025a9829512d.png)

A bit of logging in `BugsnagReactNative.m` reveals that `BSGConvertTypedNSDictionary` properly recognizes boolean values, transforming them using `@([RCTConvert BOOL:value])` and saving `converted[key]` as either `1` or `0`. Assuming this is expected behavior, the issue must happen after this point, though I haven't been able to figure out exactly where.

Any advice?

**Comment by kattrali** [comment]
Hmm, this seems to be an odd case. A `BOOL` converted to an object should be an `__NSCFBoolean`, which is a type of `NSNumber`, though it serializes to JSON as `true` or `false`. 

For example, given an Objective-C file:

```objc
#import <Cocoa/Cocoa.h>

int main(int argc, char * argv[]) {
    @autoreleasepool {
        NSData *data = [NSJSONSerialization dataWithJSONObject:@{@"bool": @(YES)} options:0 error:nil];
        NSString *json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
        NSLog(@"Value: '%@'", json);
    }
}
```

Compile with:

```
clang -objc -framework Cocoa main.m -o json-bool
```

The resulting output is:

```
./json-bool
2017-01-16 19:46:55.156 jsoning[1324:647305] Value: '{"bool":true}'
```

Maybe this is something to do with the implementation of `+[RCTConvert BOOL:]`. Taking a look into it.

**Comment by kattrali** [comment]
This is now fixed and does not require a library change 🎉
