### ISSUE TITLE
React-native link does not work with v2.0.0

### ISSUE THREAD

**Issue by iuraya** [bugsnag/bugsnag-react-native#62]
Doing the install process with version 2.0.0 the link with the libBugsnagReactNative.a stops working. With v1.2.2 works perfectly

**Comment by kattrali** [comment]
Thanks for the report, @iuraya. v2.0.0 has a peer dependency on React Native 0.40 and above. Can you provide the React Native version to ensure the project is compatible? Otherwise there should be a warning indicating that the peer dependency is unmet when the bugsnag package is installed.

**Comment by iuraya** [comment]
My react native version is 0.33.0

**Comment by kattrali** [comment]
Thanks! Downgrading to 1.2.3 should fix your issue.
