### ISSUE TITLE
not receive notifications on development

### ISSUE THREAD

**Issue by hecontreraso** [bugsnag/bugsnag-react-native#65]
How can I set up bugsnag to stop sending me emails and reporting errors when developing my app? I can't find anything in the docs. Any help will be greatly appreciated (:

**Comment by wordofchristian** [comment]
[Here](https://docs.bugsnag.com/platforms/react-native/configuration-options/#notifyreleasestages) is the setting for that.

```javascript
import { Client, Configuration } from "bugsnag-react-native";

const configuration = new Configuration("YOUR-API-KEY");
configuration.notifyReleaseStages = ['beta', 'production'];
const client = new Client(configuration);
```
