### ISSUE TITLE
Example for logging from native side

### ISSUE THREAD

**Issue by ptomasroos** [bugsnag/bugsnag-react-native#68]
Hey!

I have use-case where I would like to notify from a native side as well in both Android + IOS
Would be great to get a example in the docs how to do this, should one walk through the JS interface using the ReadableMap / JavaOnlyMap or is there an easier way to accomplish this.

**Comment by wordofchristian** [comment]
For clarification, are you wanting to send two events for the same unhanded exception? Or is is that you want to be able to manually notify bugsnag from the JS side and the native side during different scenarios?

**Comment by ptomasroos** [comment]
No rather. I have I case I can only detect in my native modules which will never be reachable from js. 

And it would be very valuable if I could error this from native code. 

Tomas

**Comment by ptomasroos** [comment]
Last statement is correct.

**Comment by wordofchristian** [comment]
The react native notifier uses the [iOS](https://docs.bugsnag.com/platforms/ios-objc/) and [Android](https://docs.bugsnag.com/platforms/android/sdk/) notifiers to do the actual reporting. You should be able to import and use them directly in native code to [report custom or handled exceptions](https://docs.bugsnag.com/platforms/ios-objc/#reporting-handled-exceptions)

You should not need to initialize them. By that I mean don't call `[Bugsnag startBugsnagWithApiKey:@"your-api-key-goes-here"];` in iOS or `Bugsnag.init(this);` in Android. The react native notifier will handle the initialization and configuration of the underlying platform notifier.

**Comment by souhe** [comment]
Hi, @wordofchristian. I want to call `Bugsnag.notify` inside my Android native code. I'm not sure what I'm doing wrong but I'm getting `You must call Bugsnag.init before other Bugsnag methods`.

Are you sure it is not necessary to call `Bugsnag.init`?

**Comment by kattrali** [comment]
I updated the React Native guide to include links to the native interface documentation for reporting handled exceptions, identifying users, and logging breadcrumbs. It should be deployed shortly.
