### ISSUE TITLE
React Native peer dependency for 0.41.x

### ISSUE THREAD

**Issue by mpatric** [bugsnag/bugsnag-react-native#70]
When trying to use this with react native 0.41.2, there's a npm peer dependency warning:

`bugsnag-react-native@2.0.2 requires a peer of react-native@^0.40 but none was installed`

This is because the dependency in bugsnag-react-native is declared as: `"react-native": "^0.40"`

That means as per semver rules (caret allows changes that do not modify the left-most **non-zero** digit), any react native version other than 0.40.x is not supported.

**Comment by yaronlevi** [comment]
+1

**Comment by mahm** [comment]
+1

**Comment by Simbamoureux** [comment]
+1
