### ISSUE TITLE
Meta-data in breadcrumbs throwing error

### ISSUE THREAD

**Issue by toddmetheny** [bugsnag/bugsnag-react-native#72]
breadcrumbs work fine if I only pass a type but throw an error when I attempt to pass additional data:

```
client.leaveBreadcrumb(msg, {
      type: 'navigation',
      component: 'Something',
      props: props,
      previousScene: 'Previous',
    });

```

Any thoughts on why this would be happening?

**Comment by kattrali** [comment]
Thanks for the report, @toddmetheny. Can you provide the error message received, and potentially what is in the `props` argument? It could be that props is not serializable.

**Comment by toddmetheny** [comment]
Hi @kattrali -- I'm passing everything in `this.props` (regardless of where I am) including navigator. The docs made it seem like you could pass whatever was in props.
 
This is the error: 

> Cannot read property 'requestSchedulingNavigation' of undefined
reactConsoleError @ index.ios.bundle:23991
console.error @ index.ios.bundle:60406
logIfNoNativeHook @ index.ios.bundle:24659
__callFunction @ index.ios.bundle:7397
(anonymous) @ index.ios.bundle:7301
guard @ index.ios.bundle:7249
callFunctionReturnFlushedQueue @ index.ios.bundle:7300
onmessage @ debuggerWorker.js:39

**Comment by kattrali** [comment]
We updated the docs to be clearer about only putting primitives in breadcrumb metadata.
