### ISSUE TITLE
Error when using Bugsnag for both react native and native ios

### ISSUE THREAD

**Issue by yaronlevi** [bugsnag/bugsnag-react-native#76]
I successfully configured Bugsnag for my react native project and everything is fine dandy. Errors from the javascript side of things are caught and placed in Bugsnag service.
Now I also want to configure Bugsnag inside the Xcode project to catch errors from the native domain.  

So I followed the guide, installed the Bugsnag pod, and called Bugsnag.startBugsnag() in appDelegate (which is written in Swift).

But when I run the app on the device, in runtime, I got an error which says something along the lines of **"found lib... in both places... which one to use?"**.

For some reason, I can't make it so that this error message will appear again, but instead, now it just says "something went wrong when installing the app on device". But this happens for the same reason.

What do I need to do to successfully run Bugsnag in the same react native project on both the javascript side and native side?

**Comment by wordofchristian** [comment]
Hello @yaronlevi, the bugsnag-react-native library already includes the bugsnag cocoa library as a dependency. You should not be using cocoapods to add it separately for react native projects. If you follow the [react native setup instructions](https://docs.bugsnag.com/platforms/react-native/#native-component-installation) and configure the library from javascript, it will automatically  catch exceptions from both javascript and swift environments.

**Comment by yaronlevi** [comment]
I tried this, but errors from native code would not seem to be channeled to Bugsnag. For example, I tried this lines in my AppDelegate.swift, in the end of didFinishLaunchingWithOptions:
```
let arr = [2];
let n = arr[3];
return true
```

And the error would not apperar in my Bugsnag console

**Comment by kattrali** [comment]
@yaronlevi Once the react native bugsnag library is installed, you can continue to use `Bugsnag.start()` in your AppDelegate by importing `"Bugsnag.h"` in your bridging header. There is also a podspec you can add to your Podfile using something like:

```
pod 'Bugsnag', :path => '../node_modules/bugsnag-react-native'
```

**Comment by yaronlevi** [comment]
The only xcode project I have in my workspace is BugsnagReactNative.xcodeproj,
so I tried to import #import <BugsnagReactNative/BugsnagReactNative.h> but it won't let me use BugsnagReactNative.start()

**Comment by kattrali** [comment]
> The only xcode project I have in my workspace is BugsnagReactNative.xcodeproj,
so I tried to import #import <BugsnagReactNative/BugsnagReactNative.h> but it won't let me use BugsnagReactNative.start()

If you expand the `BugsnagReactNative` project in the Project pane of the sidebar, you’ll see that it contains a Libraries folder. Within libraries are its two dependencies, `bugsnag-cocoa` and `KSCrash`. These files reside in the `bugsnag-react-native` directory in `vendor/cocoa`. Its how it handles native exceptions under the hood. Instead of importing BugsnagReactNative.h, use Bugsnag.h, which is in the base library, and `Bugsnag.start()`.

**Comment by yaronlevi** [comment]
Ok, I am trying:
#import <BugsnagReactNative/Bugsnag.h>
#import <BugsnagReactNative/Bugsnag/Bugsnag.h>
#import <BugsnagReactNative/Libraries/Bugsnag/Bugsnag.h>

but for all of them I get file not found

**Comment by kattrali** [comment]
Where did `#import <BugsnagReactNative/Bugsnag.h>` come from? Try:

```objc
#import "Bugsnag.h"
```

**Comment by yaronlevi** [comment]
They all sit inside myapp-Briding-Header.h . (attached an image)

![Uploading Screen Shot 2017-03-07 at 2.00.50.png…]()

**Comment by yaronlevi** [comment]
and also this is the project structure:
<img width="245" alt="screen shot 2017-03-07 at 2 03 33" src="https://cloud.githubusercontent.com/assets/5398977/23635780/5ee22484-02da-11e7-9269-51cc0d172b34.png">

**Comment by kattrali** [comment]
Alright. Let's take a step back to figure out what's going on here. If I understand correctly, you have:

* successfully configured bugsnag-react-native using `npm`
* are seeing JavaScript errors reported
* are *not* seeing some native errors are not being reported

Is that much correct?

**Comment by yaronlevi** [comment]
correct.
I have bugsnag-react-native 2.0.2 installed.
Bugs from the js land are reported ok.

**Comment by kattrali** [comment]
Did you see a crash, but no report was generated on your project dashboard on bugsnag.com?

**Comment by yaronlevi** [comment]
yes....I tried putting:

let arr = [2];
let n = arr[3];
 
inside appDelegate's didFinishLaunchingWithOptions.
no error was reported.

**Comment by kattrali** [comment]
Got it. I've tested that importing `"Bugsnag.h"` is working as expected from Objective-C, but there seems to be an issue with the umbrella header/module map when importing it from a bridging header for Swift. Investigating.

**Comment by yaronlevi** [comment]
OK (and yes, I have changed my default react native project structure, so that instead of the regular generated AppDelegate.h and AppDelegate.m (which I've commented their entire content) I now have a AppDelegate.swift

(As you can see in the pictures I've uploaded)

**Comment by kattrali** [comment]
What does the error message say when using `#import "Bugsnag.h"`? I initially got a message indicating that the umbrella header could not be found, but after cleaning the project a few times, it works as expected and reported errors successfully after initializing with `Bugsnag.start()`. Note that native crashes are not reported when a debugger is attached.

### Test project

#### package.json

```json
{
  "name": "MyProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "bugsnag-react-native": "^2.1.0",
    "react": "15.4.2",
    "react-native": "0.42.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

#### MyProject-Bridging-Header.h

```objc
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "Bugsnag.h"
```

#### AppDelegate.swift

Uncomment the call to `crashApp` to cause a crash, re-comment to stop crashing on launch and send reports.

```swift
import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    Bugsnag.start(withApiKey: "YOUR-API-KEY-HERE")
    
    let jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index.ios", fallbackResource: nil)
    let rootView = RCTRootView(bundleURL: jsCodeLocation, moduleName: "FancyPants", initialProperties: nil, launchOptions: launchOptions)
    rootView?.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1)

    window = UIWindow(frame: UIScreen.main.bounds)
    let rootViewController = UIViewController()
    rootViewController.view = rootView
    window?.rootViewController = rootViewController
    window?.makeKeyAndVisible()

    // crashApp()

    return true
  }

  func crashApp() {
    let items = [2]
    let item = items[34]
    print("\(item) will never be printed")
  }
}
```

**Comment by yaronlevi** [comment]
Ok, will check this and report you in couple of hours.

**Comment by yaronlevi** [comment]
Ok I tried clean and build several times but I still get the same result 
<img width="315" alt="screen shot 2017-03-07 at 15 43 35" src="https://cloud.githubusercontent.com/assets/5398977/23658893/e207ae5c-034c-11e7-9697-093c8b58f645.png">

**Comment by kattrali** [comment]
What does the error message say when using `#import "Bugsnag.h"`?

**Comment by yaronlevi** [comment]
<img width="149" alt="screen shot 2017-03-08 at 0 12 33" src="https://cloud.githubusercontent.com/assets/5398977/23680458/f4700f02-0393-11e7-957d-5cc70c031a7a.png">

**Comment by kattrali** [comment]
I pushed a sample project to the [swift-sample-project](https://github.com/bugsnag/bugsnag-react-native/tree/swift-project-sample) branch of the repository. Can you try checking it out and seeing if it runs for you? If so, maybe we can determine what setting is different from your project and causing the build error.

**Comment by yaronlevi** [comment]
Great.. I am checking

**Comment by yaronlevi** [comment]
WOHA!
Managed to make it work.
I deleted main.m and appdelegate.{h,m} (not just commenting their content, although I think it didn't had any effect )

and did:
react-native unlink bugsnag-react-native
react-native link bugsnag-react-native

Thank you for your help! much appriciated!

**Comment by kattrali** [comment]
Awesome!! 🎉

**Comment by yaronlevi** [comment]
Sorry for opening the issue again. When I call:

`Bugsnag.notifyError(NSError(domain:"com.example", code:408, userInfo:nil))`

The error is being sent correctly to Bugsnag and I can see it in the dashboard. But when doing:
```
let arr = [2];
let n = arr[3];

```
I see not error being reported. I've tried it multiple times. (and also in the SturdyPants sample project). 
Any clue to why this is happening?

**Comment by kattrali** [comment]
Sure, if you look in the console, the error is being captured, but if you crash the app in the first moments it's open, there's not enough time to send the error report, as that happens in the background.

**Comment by yaronlevi** [comment]
Actually it happens after the app is loaded, when I click a button:
<img width="1027" alt="screen shot 2017-03-08 at 19 03 22" src="https://cloud.githubusercontent.com/assets/5398977/23714506/1daa3caa-0432-11e7-85c3-99820bed3432.png">

**Comment by yaronlevi** [comment]
I can see in the xcode console the error:
`fatal error: Index out of range`

But after that nothing about crash reported or KCrash

**Comment by yaronlevi** [comment]
Ok, everything is cool. The error is reported. But only after I restart the app.

**Comment by kattrali** [comment]
Ah cool, makes sense. iOS is in an unstable state after an unhandled exception happens, so exceptions are only written to disk and sent on the next launch.

**Comment by pvinis** [comment]
when you get the report, have you managed to get them symbolicated too? because i cant.
