### ISSUE TITLE
npm isn't aware of newer releases

### ISSUE THREAD

**Issue by superquest** [bugsnag/bugsnag-react-native#79]
> $ yarn add react-native-bugsnag@1.2.4 
> 
> error Couldn't find any versions for "react-native-bugsnag" that matches "1.2.4". Possible versions: "0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 1.0.0, 1.0.1, 1.0.2"

[NPM says a new version hasn't been published for 2 months](https://www.npmjs.com/package/react-native-bugsnag):
![image](https://cloud.githubusercontent.com/assets/4335621/23820506/6743294a-05df-11e7-989c-c351f6be06de.png)

But there have clearly been releases since then on GitHub: https://github.com/bugsnag/bugsnag-react-native/releases.

I think you need to run `npm publish` ...

**Comment by duncanhewett** [comment]
@superquest You want [`bugsnag-react-native`](https://www.npmjs.com/package/bugsnag-react-native) instead of `react-native-bugsnag`.
