### ISSUE TITLE
Error trying to install for iOS: Bugnsnag/Bugsnag.h not found

### ISSUE THREAD

**Issue by dwilt** [bugsnag/bugsnag-react-native#8]
Following your steps [here](https://docs.bugsnag.com/platforms/react-native/#installation), I was able to easily get Android up and running. I can see the bugs coming into my Bugsnag snag project dashboard (which is a Javascript type project by the way). 

However, when I try to build in iOS after following the specific iOS instructions [here](https://docs.bugsnag.com/platforms/ios/#installation) (using the CocoaPods route), I get the following error in Xcode: `Bugnsnag/Bugsnag.h not found`

![image](https://cloud.githubusercontent.com/assets/1065539/19294047/3c16c802-8fde-11e6-8989-2af246f5e3ca.png)
 
The documentation here on what to install/configure is pretty confusing by the way.

**Comment by kattrali** [comment]
Hi @dwilt, thank you for the report. It looks like BugsnagReactNative is not linked with the Bugsnag framework included in cocoapods. I’d recommend selecting the BugsnagReactNative project in the Project Navigator sidebar, opening the Build Phases tab, and then adding Bugsnag.framework to “Link Binary with Libraries”.

<img width="997" alt="react-native-deps" src="https://cloud.githubusercontent.com/assets/333454/19321088/e35726ae-9068-11e6-979c-f70ba99b40ec.png">

I think the instructions weren’t clear that these steps are still necessary even after using cocoapods for installation. I’m updating the docs to clarify the process. Hopefully this helps!

**Comment by morelazers** [comment]
Hi - I don't see these frameworks available to link, I used CocoaPods to install Bugsnag.

**Comment by kattrali** [comment]
Hi @morelazers - I'd recommend checking that after installation you've opened MyProject.xcworkspace and not MyProject.xcodeproj, and if that does not fix the problem, open a new issue with your findings. Thanks!

**Comment by dwilt** [comment]
@kattrali for the record, I was never able to get this to work either. I ran into exactly what @morelazers is saying. I just gave up and installed https://github.com/SudoPlz/react-native-bugsnag

**Comment by kattrali** [comment]
Hi @dwilt, I had no idea. I updated the installation to not require the extra steps, and now an `react-native link` handles installing the native dependencies, starting with v1.0.1. The [documentation](https://docs.bugsnag.com/platforms/react-native/#installation) has also been updated accordingly.
