### ISSUE TITLE
Is there a recommended way to overwrite console.log to send breadcrumbs to BugSnag?

### ISSUE THREAD

**Issue by wootwoot1234** [bugsnag/bugsnag-react-native#82]
I'm using the following code in my project but wanted to know if overwriting console.log was already built in or if there is a better way to overwrite console.log?

    //-------------------------------------------------------------------------------------------------
    // Create a singleton instance of the bugsnag client so we don't have to duplicate our configuration
    // anywhere.
    //-------------------------------------------------------------------------------------------------
    // https://docs.bugsnag.com/platforms/react-native/#basic-configuration
    import Config from '../data/Config';
    import { Client, Configuration } from "bugsnag-react-native";

    const configuration = new Configuration();
    configuration.apiKey = Config.BUGSNAG_API_KEY;
    configuration.notifyReleaseStages = ['production'];

    const client = new Client(configuration);

    (function(){
        var _log = console.log;

        console.log = function(logMessage){
            client.leaveBreadcrumb(logMessage, {type: 'log'});
            _log.apply(console,arguments);
        };

    })();
    //-------------------------------------------------------------------------------------------------
    export default {
        client
    };

**Comment by kattrali** [comment]
@wootwoot1234 I don't think there is a preferred way to overwrite console.log at the moment; overwriting it can have unexpected consequences for looking up files/line numbers, which we encountered [when doing something similar for bugsnag-js](https://github.com/bugsnag/bugsnag-js/issues/156). Its something to revisit though.
