### ISSUE TITLE
Add metadata anytime, not only on crash report

### ISSUE THREAD

**Issue by brunolemos** [bugsnag/bugsnag-react-native#83]
AFAIK, you can only add metadata when using `notify`.
But I'd like to add metadata before that, the same way we can do `setUser` or `leaveBreadcrumb`.

Sentry has a [setExtraContext](https://docs.sentry.io/learn/context/#extra-context) method for that.
Does Bugsnag have something similar?

**Comment by kattrali** [comment]
You can add metadata by [registering callbacks](https://docs.bugsnag.com/platforms/react-native/customizing-error-reports/) at any time.
