### ISSUE TITLE
Fix: q.default.notify is not a function. (In 'q.default.notify(t)', 'q.default.notify' is undefined)

### ISSUE THREAD

**Issue by wootwoot1234** [bugsnag/bugsnag-react-native#85]
I keep getting the following error:

> q.default.notify is not a function. (In 'q.default.notify(t)', 'q.default.notify' is undefined)

I think it's because I'm passing `bugsnag.notify()` something other than an instance of an error.  In my defence, is because I use a ton of different react native modules and they don't all return errors as instances of an error and often as strings.

It would be great if `bugsnag.notify()` could take a string (and maybe other types) without crashing.  Maybe warn the developer that they passed something other than an error and an an example of how to fix it?

**Comment by kattrali** [comment]
Thanks for the report, @wootwoot1234. I'm not sure I understand how passing a non-error to `bugsnag.notify` would quite cause this problem, maybe its an issue with bindings somewhere along the call stack?

**Comment by wootwoot1234** [comment]
Test

**Comment by wootwoot1234** [comment]
You're right, not a setting issue.  This is the only repository I'm having trouble with.  Must be a GitHub.com issue.  I'm using safari now and it's working...  Anyway, back to the issue:

Now, I'm not sure either.  I spent the time after creating this issue looking deeper into the code and I'm still not sure.  Here's my code and the error I'm getting in bugsnag:

Here's my bugsnag.js file:

    import Config from '../data/Config';
    import { Client, Configuration } from "bugsnag-react-native";

    const configuration = new Configuration();
    if(Config.IS_UNLOCKED) {
        configuration.apiKey = Config.BUGSNAG_API_KEY_EDUCATOR;
    } else {
        configuration.apiKey = Config.BUGSNAG_API_KEY;
    }
    configuration.notifyReleaseStages = ['production'];

    const client = new Client(configuration);

    (function(){
        var _log = console.log;
        var _error = console.error;
        var _warning = console.warning;

        console.error = function(){
            var messages = [];
            arguments.forEach((argument) => {
                if(typeof argument == "object") {
                    messages.push(JSON.stringify(argument));
                } else {
                    messages.push(argument);
                }
            });
            client.leaveBreadcrumb("err: " + messages.join(' '), {type: 'error'});
            _error.apply(console, arguments);
        };

        console.log = function(){
            var messages = [];
            arguments.forEach((argument) => {
                if(typeof argument == "object") {
                    messages.push(JSON.stringify(argument));
                } else {
                    messages.push(argument);
                }
            });
            client.leaveBreadcrumb("log: " + messages.join(' '), {type: 'log'});
            _log.apply(console, arguments);
        };

        console.warning = function(){
            var messages = [];
            arguments.forEach((argument) => {
                if(typeof argument == "object") {
                    messages.push(JSON.stringify(argument));
                } else {
                    messages.push(argument);
                }
            });
            client.leaveBreadcrumb("warn: " + messages.join(' '), {type: 'warning'}); // not sure if I can make up my own type...
            _warning.apply(console, arguments);
        };
    })();
    //-------------------------------------------------------------------------------------------------
    export default {
        client
    };


and here's where I call `notify()`, I'm using the [react-native-in-app-utils](https://github.com/chirag04/react-native-in-app-utils/) module :


        InAppUtils.loadProducts(inAppPurchaseIds, (error, products) => {
            if(error) {
                Bugsnag.notify(error);
            }
            ...
        });

Finally,  Here' the error I'm getting in bugsnag:

> TypeError/Users/Tom/app/components/Main.js:112
> q.default.notify is not a function. (In 'q.default.notify(t)', 'q.default.notify' is undefined)

**Comment by wootwoot1234** [comment]
I'm going to try calling `notify()` like this:

    Bugsnag.notify(new Error(error));

Hopefully that will fix the problem because I only seem to get that error whenever I call `notify()` with something other than a instance of an error.  Do you have any other ideas of what might be causing the error?

**Comment by jmshal** [comment]
Something about the way you're exporting the `client` from your `bugsnag.js` file makes me feel like that's the actual issue.

Does it make a difference if you changed the last line to `export default client;`? Right now, I think the way `client` is being exported would mean you would have to do `Bugsnag.client.notify(...)` in order to get what you're after.

Just a hunch, as I haven't pulled out your snippet and tried it for myself yet.

**Comment by wootwoot1234** [comment]
Thanks for the idea.  The existing code is reporting errors so it doesn't really make sense to me why it would cause the error only sometimes but I'm willing to give it a shot.   :)

Update: I just tried removing the brackets and that works too.  I'll push it to production and see if it stops the above error.  Thanks for the help.

I still think it would be helpful if the `notify()` function accepted strings as well as errors.  Just a thought.

**Comment by jmshal** [comment]
I would recommend creating your own `notify` function which can handle strings & errors. Something like the following, because you'll likely want to remove the first line of the stacktrace, so it gets grouped with errors alike.

```js
// ...

function notify(message, ...args) {
  if (message instanceof Error) {
    return client.notify(message, ...args);
  } else {
    const err = new Error(message);
    const stack = err.stack.split('\n');
    stack.splice(1, 1);
    err.stack = stack.join('\n');
    return client.notify(err, ...args);
  }
}

export default {
  notify
};
```

I know it's a bit nasty, but it does solve the string-as-an-error issue.

**Comment by wootwoot1234** [comment]
I'll give that a shot.  Thanks!

I have another question.  How do I know if an error caused the app to crash or not?

**Comment by kattrali** [comment]
@wootwoot1234 calling `notify` sets the severity to `warning`, while a crashing error will have a `error` severity.

**Comment by wootwoot1234** [comment]
Ok, thanks!

**Comment by jmshal** [comment]
Hey @wootwoot1234, just a quick follow up. Did everything work out in the end?

**Comment by kattrali** [comment]
Closing this as solved. Feel free to reopen if the issue recurs, thanks all!
