### ISSUE TITLE
undefined is not an object (evaluating apiKeyOrConfig.constructor)

### ISSUE THREAD

**Issue by Taakn** [bugsnag/bugsnag-react-native#86]
Hello,

I am getting this error on Android RN 0.39.2 bugsnag 1.2.4 bugsnag.js line 140

Thanks

**Comment by kattrali** [comment]
Hi @Taakn, thanks for the report. Versions prior to 1.3.0 do not allow initialization without specifying the API key when creating a client. Can you retry with 1.3.0? Its a non-breaking upgrade from 1.2.4 and solves this issue. If you cannot upgrade, you'll need to create your Bugsnag client with an API key, like:

```js
const bugsnag = new Client('YOUR-API-KEY-HERE');
```

**Comment by Taakn** [comment]
Thanks a lot for your quick reply that fixed it. I cannot upgrade though. Now I had to remove `BugsnagReactNative.start(this);` and though the test error is appearing fine, the app crashing does not record anything. Is there anything else that I am missing?

**Comment by Taakn** [comment]
ok thanks again very much for your help I'm starting to see errors in the dashboard
