### ISSUE TITLE
Response to Issue

### ISSUE THREAD

**Issue by wootwoot1234** [bugsnag/bugsnag-react-native#87]
Here's my response to https://github.com/bugsnag/bugsnag-react-native/issues/85.  For some reason I can't comment on any issue I create.  Is there some setting you've enabled preventing users from responding?

Now, I'm not sure either.  I spent the time after creating this issue looking deeper into the code and I'm still not sure.  Here's my code and the error I'm getting in bugsnag:

Here's my bugsnag.js file:

    import Config from '../data/Config';
    import { Client, Configuration } from "bugsnag-react-native";

    const configuration = new Configuration();
    if(Config.IS_UNLOCKED) {
        configuration.apiKey = Config.BUGSNAG_API_KEY_EDUCATOR;
    } else {
        configuration.apiKey = Config.BUGSNAG_API_KEY;
    }
    configuration.notifyReleaseStages = ['production'];

    const client = new Client(configuration);

    (function(){
        var _log = console.log;
        var _error = console.error;
        var _warning = console.warning;

        console.error = function(){
            var messages = [];
            arguments.forEach((argument) => {
                if(typeof argument == "object") {
                    messages.push(JSON.stringify(argument));
                } else {
                    messages.push(argument);
                }
            });
            client.leaveBreadcrumb("err: " + messages.join(' '), {type: 'error'});
            _error.apply(console, arguments);
        };

        console.log = function(){
            var messages = [];
            arguments.forEach((argument) => {
                if(typeof argument == "object") {
                    messages.push(JSON.stringify(argument));
                } else {
                    messages.push(argument);
                }
            });
            client.leaveBreadcrumb("log: " + messages.join(' '), {type: 'log'});
            _log.apply(console, arguments);
        };

        console.warning = function(){
            var messages = [];
            arguments.forEach((argument) => {
                if(typeof argument == "object") {
                    messages.push(JSON.stringify(argument));
                } else {
                    messages.push(argument);
                }
            });
            client.leaveBreadcrumb("warn: " + messages.join(' '), {type: 'warning'}); // not sure if I can make up my own type...
            _warning.apply(console, arguments);
        };
    })();
    //-------------------------------------------------------------------------------------------------
    export default {
        client
    };

and here's where I call `notify()`, I'm using the [react-native-in-app-utils](https://github.com/chirag04/react-native-in-app-utils/) module :

        InAppUtils.loadProducts(inAppPurchaseIds, (error, products) => {
            if(error) {
                Bugsnag.notify(error);
            }
            ...
        });

Finally,  Here' the error I'm getting in bugsnag:

> TypeError/Users/Tom/app/components/Main.js:112
> q.default.notify is not a function. (In 'q.default.notify(t)', 'q.default.notify' is undefined)

**Comment by kattrali** [comment]
Gotcha, thanks for the added detail. Regarding commenting issues, as far as I know, there isn't any blanket way to prevent people from commenting, besides locking (which should be obvious to everyone?). Maybe its a bug in the GitHub UI, as it happens to me occasionally as a non-Chrome user.
