### ISSUE TITLE
Unable to use source maps

### ISSUE THREAD

**Issue by oryagel** [bugsnag/bugsnag-react-native#88]
Hi,
I uploaded source maps using the following module: https://www.npmjs.com/package/bugsnag-sourcemaps
That code that uses this module is the following:
```const path = require('path');
const upload = require('bugsnag-sourcemaps').upload;
 
upload({
  apiKey: 'OUR_KEY',
  appVersion: '1.0', // optional 
  minifiedUrl: 'http://localhost:8081/index.android.bundle', // supports wildcards 
  sourceMap: path.resolve(__dirname, '/Users/or/development/testing_bugsnag2/index.android.bundle.map'),
  minifiedFile: path.resolve(__dirname, '/Users/or/development/testing_bugsnag2/index.android.bundle'), // optional 
  overwrite: true // optional

}, function(err) {
  if (err) {
    throw new Error('Something went wrong! ' + err.message);
  }
  console.log('Sourcemap was uploaded successfully.');
});
```

The source maps are uploaded successfully and I  can see it in the project settings.
I integrated Bugsnag to an example react native app and when I throw an error I can see it in Bugsnag.
The problem is that the stacktrace refers to the bundled code even though I uploaded the source maps. 
I'm doing all the experiments in debug mode, the app version is 1.0.

What am I doing wrong?

Thanks

**Comment by kattrali** [comment]
Thanks for the report, @oryagel. Can you contact support so we can take a look at your account details and diagnose more thoroughly? Based on your snippet, it looks like rhis should work.

**Comment by oryagel** [comment]
It turns out that I needed to bump the app version. I'm not sure why, but when I changed the app version it worked.
