### ISSUE TITLE
Release Stage in non-development app

### ISSUE THREAD

**Issue by rmevans9** [bugsnag/bugsnag-react-native#90]
Following the directions here: https://docs.bugsnag.com/platforms/react-native/ you end up having Bugsnag process any types of crashes prior to Javascript setup. This typically isn't an issue unless you are overriding settings in your Javascript configuration (for example if you are overriding the releaseStage). This causes any errors that fully crash your app to report as Production issues even if they might be staging (or some other environment) issues.

If you remove the native start calls the exception logging works as expected however I suspect this could cause issues with getting exceptions logged from the native side.

Can someone with a better understanding of how bugsnag-react-native then I have weigh in here? 

- Should we be calling start from Android, iOS AND JavaScript? Or should we limit it to just Android and iOS OR JavaScript? NOTE: It looks like the call for creating the client in JavaScript DOES start up BugSnag. ref: https://github.com/bugsnag/bugsnag-react-native/blob/5ff75f4aa5cc1eaf7462a85af8f5674a1e09ca17/lib/Bugsnag.js#L23 && https://github.com/bugsnag/bugsnag-react-native/blob/5ff75f4aa5cc1eaf7462a85af8f5674a1e09ca17/cocoa/BugsnagReactNative.m#L227
- If we are to call Start in Android, iOS AND JavaScript - How should the releaseStage (and other configurations) be set?
- If we are to call Start in Android/iOS OR JavaScript - Would it be possible to state that more clearly here: https://docs.bugsnag.com/platforms/react-native/#basic-configuration

Thanks!

**Comment by kattrali** [comment]
Thanks for the detailed report, @rmevans9.

> Should we be calling start from Android, iOS AND JavaScript? Or should we limit it to just Android and iOS OR JavaScript? NOTE: It looks like the call for creating the client in JavaScript DOES start up Bugsnag.

If you aren't going to be using Bugsnag to capture JavaScript errors, just from Android and iOS is fine. Initializing from JS provides an error handler to capture JavaScript errors and unhandled rejections from Promises, as well as the ability to leave breadcrumbs and report non-fatal errors.

> If we are to call Start in Android, iOS AND JavaScript - How should the releaseStage (and other configurations) be set?

If you set release stage in iOS and Android natively, JavaScript initialization does not override those values and you should be all set!

Hopefully this makes more sense now!
