### ISSUE TITLE
Configuration changes after bugsnag object created.

### ISSUE THREAD

**Issue by ohtangza** [bugsnag/bugsnag-react-native#91]
I have two async events related to `bugsnag` client object.

1. CodePush.getUpdateMetadata() ==> which returns JS bundle id
2. Firebase.auth().onAuthStateChanged() ==> which returns user information

The returning sequence is so random in my case. Is there any way I can change the configuration of BugSnag? 

Or is it okay for me to create new instance everytime bugsnag's configuration is updated?

**Comment by kattrali** [comment]
Thanks for the report, @ohtangza.

> CodePush.getUpdateMetadata() ==> which returns JS bundle id

Updating `bugsnag.config.codeBundleId` asynchronously works.

> Firebase.auth().onAuthStateChanged() ==> which returns user information

In this case, you can call [`bugsnag.setUser`](https://docs.bugsnag.com/platforms/react-native/#identifying-users) to update the user information sent with reports. This can be done at any time.

**Comment by ohtangza** [comment]
Thanks for the kind response. Thanks!

**Comment by usrbowe** [comment]
@kattrali can this be as a code example in the documentation under [Codepush section](https://docs.bugsnag.com/platforms/react-native/configuration-options/#codebundleid)?

```
bugsnag.config.codeBundleId = codePush.getUpdateMetadata().then(update => update.label)
```

**Comment by bengourley** [comment]
Hey @usrbowe does that example work? It looks to me like it would set:

```js
bugsnag.config.codeBundleId = <Promise>
```

…rather than the value resolved by the promise. I think instead you'd want to do:

```js
codePush.getUpdateMetadata().then(update => {
  bugsnag.config.codeBundleId = update.label
})
```

Let me know you get on and we can consider adding this to the docs. Thanks!

**Comment by usrbowe** [comment]
@bengourley oh yeah, u right. The correct one is your example. My code would return Promise. 👍
