### ISSUE TITLE
Pods not Symlinking all Public Headers

### ISSUE THREAD

**Issue by dkpalmer** [bugsnag/bugsnag-react-native#92]
We recently switched over to pulling in all 3rd party modules as Cocoapods (vs native linking). I hit a snag when installing the Bugsnag Pod:

> .../AppDelegate.m:19:9: 'BugsnagConfiguration.h' file not found

Upon inspection, the only header listed in ios/Pods/Headers/Public/BugsnagReactNative is *BugsnagReactNative.h*. If I try re-ordering the `public_header_files` items, it appears that `pod install` is only looking at the first one (e.g. by default just pulls in *BugsnagReactNative.h*. If I swap in the vendor path first, I see all matching files symlinked.

Any thoughts on how to modify `public_header_files` to get all public headers properly symlinked?

Note, we have commented out the `use_frameworks!` option due to some other compatibility issues with the React pod.

**Comment by kattrali** [comment]
> Upon inspection, the only header listed in ios/Pods/Headers/Public/BugsnagReactNative is *BugsnagReactNative.h*. If I try re-ordering the `public_header_files` items, it appears that `pod install` is only looking at the first one (e.g. by default just pulls in *BugsnagReactNative.h*. If I swap in the vendor path first, I see all matching files symlinked.

Thanks for the report, @dkpalmer. How odd. It seems somewhat similar to [this CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/5790), though if we can work around it by reordering the public headers, then that's a reasonable fix for now. I'll look into this further.

**Comment by dkpalmer** [comment]
@kattrali Unfortunately, this still has an issue with BSGKSCrashReportWriter.h not being added as a Public header. The rest of the headers seem to be picked up by that first line, but not the second line. I believe  BugsnagReactNative.h is getting picked up by the Core subspec section.

**Comment by kattrali** [comment]
Well that's just unfortunate 😞 . Which version of Cocoapods? I'll try to get a more concise test case together for a report.

**Comment by dkpalmer** [comment]
$ pod --version
1.2.1

**Comment by dkpalmer** [comment]
In the interim I am manually patching the podspec w/ the following:

```
  s.public_header_files = 'cocoa/**/{BugsnagMetaData,BugsnagConfiguration,BugsnagBreadcrumb,BugsnagCrashReport,BSGKSCrashReportWriter}.h'
```
